CREATE TABLE DPA_TASK
(
  SYSTEM_ID           NUMBER                    NOT NULL,
  ID_RUOLO_MITT       NUMBER                    DEFAULT 0                     NOT NULL,
  ID_PEOPLE_MITT      NUMBER                    DEFAULT 0                     NOT NULL,
  ID_RUOLO_RECEIVER   NUMBER                    DEFAULT 0                     NOT NULL,
  ID_PEOPLE_RECEIVER  NUMBER                    DEFAULT 0                     NOT NULL,
  ID_PROFILE          NUMBER,
  ID_PROJECT          NUMBER,
  ID_PROFILE_REVIEW   NUMBER,
  DTA_EXPIRE          DATE,
  ID_TRASMISSIONE     NUMBER,
  ID_TRASM_SINGOLA    NUMBER,
  DTA_CLOSE           DATE,
  ID_RAGIONE_TRASM    NUMBER,
  DTA_ACCETTAZIONE  DATE,
  ID_TIPO_ATTO 	NUMBER
)


CREATE SEQUENCE SEQ_DPA_TASK INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;
