-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 21/02/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
--				CREAZIONE NUOVA TABELLA DPA_PREGRESSI 		
-- =============================================

DECLARE @CNT INT
  
SET @CNT = (SELECT COUNT(*) FROM SYS.tables WHERE name = 'DPA_PREGRESSI')    
  
IF (@CNT = 0)
BEGIN
	CREATE TABLE [DOCSADM].[DPA_PREGRESSI]
	(
		[SYSTEM_ID]				INT		IDENTITY(1,1)	NOT NULL,
		[ID_AMM]				INT						NULL,
		[ID_UTENTE_CREATORE]	INT						NULL,
		[ID_RUOLO_CREATORE]		INT						NULL,
		[DATA_ESECUZIONE]		DATETIME				NULL,
		[DATA_FINE]				DATETIME				NULL,
		[NUM_DOC]				INT						NULL,
		[DATA]					DATETIME				NULL,
		[DESCRIZIONE]			VARCHAR(1024)			NULL,
				
		PRIMARY KEY CLUSTERED 
		(
			[SYSTEM_ID] ASC
		)
		WITH 
		(
			PAD_INDEX  = OFF
			, STATISTICS_NORECOMPUTE  = OFF
			, IGNORE_DUP_KEY = OFF
			, ALLOW_ROW_LOCKS  = ON
			, ALLOW_PAGE_LOCKS  = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
PRINT 'CREATO TABELLA'
END 
ELSE
	PRINT 'TABELLA ESISTENTE'


