
-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 21/02/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
--				CREAZIONE NUOVA TABELLA DPA_ASS_ALLEGATO CON RELATIVI INDICI		
-- =============================================

DECLARE @CNT INT
  
SET @CNT = (SELECT COUNT(*) FROM SYS.tables WHERE name = 'DPA_ASS_ALLEGATO')    
  
IF (@CNT = 0)
BEGIN
	CREATE TABLE [DOCSADM].[DPA_ASS_ALLEGATO]
	(
		[SYSTEM_ID]				INT		IDENTITY(1,1)	NOT NULL,
		[ID_ITEM]				INT						NOT NULL,
		[ERRORE]				VARCHAR(1024)			NULL,
		[ESITO]					CHAR(1)					NULL,
		
		
		PRIMARY KEY CLUSTERED 
		(
			[SYSTEM_ID] ASC
		)
		WITH 
		(
			PAD_INDEX  = OFF
			, STATISTICS_NORECOMPUTE  = OFF
			, IGNORE_DUP_KEY = OFF
			, ALLOW_ROW_LOCKS  = ON
			, ALLOW_PAGE_LOCKS  = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
	
	
	CREATE NONCLUSTERED INDEX [IX_T_DPA_ASS_ALLEGATOK2] ON [DOCSADM].[DPA_ASS_ALLEGATO] 
	(
		[ID_ITEM] ASC
	)
	WITH 
	(
		PAD_INDEX  = OFF
		, STATISTICS_NORECOMPUTE  = OFF
		, SORT_IN_TEMPDB = OFF
		, IGNORE_DUP_KEY = OFF
		, DROP_EXISTING = OFF
		, ONLINE = OFF
		, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON
	) ON [PRIMARY]

END

