

DECLARE @CNT INT
  
SET @CNT = (SELECT COUNT(*) FROM SYS.tables WHERE name = 'DPA_REL_PEOPLE_EXTAPPS')    
  
IF (@CNT = 0)
BEGIN
	CREATE TABLE [DOCSADM].[DPA_REL_PEOPLE_EXTAPPS]
	(
		[ID_EXT_APP]				INT	NOT NULL,
		[ID_PEOPLE]				INT 	NOT NULL					
	) 
PRINT 'CREATO TABELLA DPA_REL_PEOPLE_EXTAPPS'
END 
ELSE
	PRINT 'TABELLA ESISTENTE'


