-----SOLO SU PAT ------
begin
INSERT INTO DPA_ANAGRAFICA_EVENTI (ID_EVENTO, VAR_COD_AZIONE, DESCRIZIONE, CHA_TIPO_EVENTO, Gruppo) 
VALUES ((SELECT MAX(ID_EVENTO) + 1 FROM DPA_ANAGRAFICA_EVENTI),'DOCUMENTO_REPERTORIATO','Repertoriazione','E','EVENT');

end;
/
COMMIT;