<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\EditProject-Actual.txt" />
    <None Remove="Resources\GetDocumentsInProjectByCodeProjectAndClassificationSchemeId-Actual.txt" />
    <None Remove="Resources\GetDocumentsInProjectByIdProject-Actual.txt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\GetDocumentsInProjectByCodeProjectAndClassificationSchemeId-Actual.txt" />
    <EmbeddedResource Include="Resources\GetDocumentsInProjectByIdProject-Actual.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.25" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0-release-24352-06" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.3.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2" />
    <PackageReference Include="Refit" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="Resources\EditProject-Actual.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pi3.App.Legacy.Pis.WebApi\Pi3.App.Legacy.Pis.WebApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Files.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Files.resx</DependentUpon>
    </Compile>
    <Compile Update="Messages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Messages.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Files.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Files.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Messages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>