<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <NoWarn>S1905;S1643</NoWarn>
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <None Remove="index.html" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.0.0" />
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.31.0" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.3.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.aac-main\Pi3.Infrastructure.AAC\Pi3.Infrastructure.AAC.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.itext-main\Pi3.Infrastructure.IText.ReportGenerator\Pi3.Infrastructure.IText.ReportGenerator.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativo\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativoAggregate.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.EF.TrasmissioneAggregate\Pi3.Infrastructure.Legacy.EF.TrasmissioneAggregate.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.tibco-main\pi3.infrastructure.tibco-main\Pi3.Infrastructure.Tibco\Pi3.Infrastructure.Tibco.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.DocumentFSRepository\Pi3.Infrastructure.Legacy.DocumentFSRepository.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.chilkat-main\Pi3.Infrastructure.Chilkat\Pi3.Infrastructure.Chilkat.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.bouncycastle-main\Pi3.Infrastructure.BouncyCastle\Pi3.Infrastructure.BouncyCastle.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
    <ProjectReference Include="..\DocsPaVO\DocsPaVO.csproj" />
    <ProjectReference Include="..\Pi3.App.Legacy.Mobile.ApiHandler\Pi3.App.Legacy.Mobile.ApiHandler.csproj" />
    <ProjectReference Include="..\Pi3.App.Legacy.Mobile.Models\Pi3.App.Legacy.Mobile.Models.csproj" />
    <ProjectReference Include="..\Pi3.App.Legacy.Mobile.Shared\Pi3.App.Legacy.Mobile.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Pi3.App.Legacy.Mobile.WebApi.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Helpers\AddressBook\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\LibroFirma\EseguiPassoAutomaticoResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EseguiPassoAutomaticoResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\LibroFirma\Exceptions\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\LibroFirma\LibroFirmaHandlerResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LibroFirmaHandlerResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\Spedizione\Exceptions\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\Spedizione\InteroperabilitaSemplificata\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Helpers\Spedizione\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Files.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Files.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SwaggerMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwaggerMessages.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\RabbitMQ\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Helpers\AddressBook\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\LibroFirma\EseguiPassoAutomaticoResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>EseguiPassoAutomaticoResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\LibroFirma\Exceptions\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\LibroFirma\LibroFirmaHandlerResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>LibroFirmaHandlerResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\Spedizione\Exceptions\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\Spedizione\InteroperabilitaSemplificata\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Helpers\Spedizione\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Files.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Files.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SwaggerMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SwaggerMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\RabbitMQ\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="xml\ImportExportQueryList.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\listaIstanze.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\oracleSequenceMaps.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\queryList_Oracle.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Model\Decorators\" />
  </ItemGroup>
  <ItemGroup />
</Project>