DECLARE
  CODICE VARCHAR2(200);
  DESCRIZIONE VARCHAR2(200);
  VALORE VARCHAR2(200);
  TIPO_CHIAVE VARCHAR2(200);
  VISIBILE VARCHAR2(200);
  MODIFICABILE VARCHAR2(200);
  GLOBALE VARCHAR2(200);
  MYVERSIONE_CD VARCHAR2(200);
  CODICE_OLD_WEBCONFIG VARCHAR2(200);
  FORZA_UPDATE VARCHAR2(200);
  RFU VARCHAR2(200);
BEGIN
  CODICE := 'BE_URL_BUILD_IOS';
  DESCRIZIONE := 'url della build ios rilasciata';
  VALORE := 'https://mobile.pitre.tn.it/';
  TIPO_CHIAVE := 'F';
  VISIBILE := '1';
  MODIFICABILE := '1';
  GLOBALE := '1';
  MYVERSIONE_CD := '5.2.4';
  CODICE_OLD_WEBCONFIG := NULL;
  FORZA_UPDATE := NULL;
  RFU := NULL;

  UTL_INSERT_CHIAVE_CONFIG(
    CODICE => CODICE,
    DESCRIZIONE => DESCRIZIONE,
    VALORE => VALORE,
    TIPO_CHIAVE => TIPO_CHIAVE,
    VISIBILE => VISIBILE,
    MODIFICABILE => MODIFICABILE,
    GLOBALE => GLOBALE,
    MYVERSIONE_CD => MYVERSIONE_CD,
    CODICE_OLD_WEBCONFIG => CODICE_OLD_WEBCONFIG,
    FORZA_UPDATE => FORZA_UPDATE,
    RFU => RFU
  );
--rollback; 

COMMIT;
END;

