
CREATE OR REPLACE FUNCTION GETSTATOINVIOMASKBYTYPEID
( DOCUMENTTYPEID IN VARCHAR2
) RETURN VARCHAR2 IS MASK VARCHAR2(16);
BEGIN
DECLARE 
DOCTYPE VARCHAR2(40);
BEGIN
SELECT TYPE_ID
INTO DOCTYPE
FROM DOCUMENTTYPES
WHERE system_id= documenttypeid;

IF(DOCTYPE='MAIL') THEN
MASK := 'AANNNNA';
END IF;

IF(DOCTYPE='INTEROPERABILITA') THEN
MASK := 'AAAAAAA';
END IF ;

IF(DOCTYPE='SIMPLIFIEDINTEROPERABILITY')THEN 
MASK := 'ANAAAAN';
END IF ;
  END;
  RETURN MASK;
END GETSTATOINVIOMASKBYTYPEID;
/


