--------------------------------------------------------
--  DDL for Index INDX_DPA_A_R_FASC1
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."INDX_DPA_A_R_FASC1" ON "ITCOLL_6GIU12"."DPA_A_R_OGG_CUSTOM_FASC" ("ID_TEMPLATE", "ID_OGGETTO_CUSTOM", "ID_RUOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 46137344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
