--------------------------------------------------------
--  DDL for Index INDX_SEC5
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."INDX_SEC5" ON "ITCOLL_6GIU12"."SECURITY" ("THING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 57671680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_NDX_COLL" ;
