--------------------------------------------------------
--  DDL for Index INDX_REG_FASC1
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."INDX_REG_FASC1" ON "ITCOLL_6GIU12"."DPA_REG_FASC" ("ID_TITOLARIO", "ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
