<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ProjectType>Local</ProjectType>
    <AssemblyKeyContainerName></AssemblyKeyContainerName>
    <AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
    <DefaultClientScript>JScript</DefaultClientScript>
    <DefaultHTMLPageLayout>Grid</DefaultHTMLPageLayout>
    <DefaultTargetSchema>IE50</DefaultTargetSchema>
    <DelaySign>false</DelaySign>
    <OutputType>Library</OutputType>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    <StartupObject></StartupObject>
    <SccProjectName></SccProjectName>
    <SccLocalPath></SccLocalPath>
    <SccAuxPath></SccAuxPath>
    <SccProvider></SccProvider>
    <PublishUrl>http://localhost/DocsPaUtils/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile></ConfigurationOverrideFile>
    <DocumentationFile></DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn></NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\</OutputPath>
    <BaseAddress>285212672</BaseAddress>
    <ConfigurationOverrideFile></ConfigurationOverrideFile>
    <DocumentationFile></DocumentationFile>
    <FileAlignment>4096</FileAlignment>
    <NoStdLib>false</NoStdLib>
    <NoWarn></NoWarn>
    <RegisterForComInterop>false</RegisterForComInterop>
    <RemoveIntegerChecks>false</RemoveIntegerChecks>
    <DebugType>none</DebugType>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocsPaVO\DocsPaVO.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>
  <PropertyGroup>
    <AssemblyTitle>DocsPaUtils</AssemblyTitle>
    <Description>Classi di utilità di appoggio alle funzionalità di DocsPA.</Description>
    <Company>Etnoteam S.p.A.</Company>
    <Product>DocsPA 3.0</Product>
    <Copyright>Copyright 2005 by Etnoteam S.p.A.</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SoapCore">
      <HintPath>librerie\SoapCore.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>