CREATE TABLE DPA_PHASES
(
  SYSTEM_ID           	 NUMBER      NOT NULL,
  DESCRIPTION     	 	 VARCHAR(100 BYTE)      NOT NULL
);


CREATE TABLE DPA_ASSOCIAZIONE_STATI_PHASES
(
  SYSTEM_ID           	 NUMBER      NOT NULL,
  ID_STATO    	 		 NUMBER  NOT NULL,
  ID_PHASES				 NUMBER  NOT NULL,
  ID_DIAGRAMMA			 NUMBER NOT NULL,
  CONSTRAINT STATO_PHASES_UNIQUE UNIQUE (ID_STATO, ID_PHASES)
);



