create or replace 
FUNCTION getPolicyVersamentoCounter(IDDOC VARCHAR)
RETURN VARCHAR IS
	COUNTER VARCHAR(100);
  
  item VARCHAR(100);
  
  CURSOR cur IS
    SELECT V.NUM_ESECUZIONE_POLICY
		FROM DPA_POLICY_PARER P, DPA_VERSAMENTI_POLICY V
		WHERE P.SYSTEM_ID=V.ID_POLICY AND V.ID_PROFILE=IDDOC
    ORDER BY V.DATA_ESECUZIONE_POLICY
    ;
BEGIN
COUNTER:=NULL;

OPEN cur;
LOOP
FETCH cur INTO item;
EXIT WHEN cur%NOTFOUND;

IF(COUNTER=NULL) THEN
COUNTER := item;
ELSE
COUNTER := COUNTER || item || '; ';
END IF;

END LOOP;
  
RETURN SUBSTR(COUNTER,1,LENGTH(COUNTER)-2);


END getPolicyVersamentoCounter;