-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 22/02/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
-- TIPO_COMPONENTI
-- =============================================

DECLARE @CNT		INT

SELECT @CNT = COUNT(*)
FROM SYS.tables
WHERE NAME = 'TIPO_COMPONENTI'   

IF (@CNT = 0)
BEGIN 
	CREATE TABLE [DOCSADM].[TIPO_COMPONENTI]
	(
		[CHA_TIPO_COMPONENTI]		CHAR(1)			NOT NULL,
		[DESCRIZIONE]				VARCHAR(128)	NOT NULL,
		
		
				
		PRIMARY KEY CLUSTERED 
		(
			[CHA_TIPO_COMPONENTI] ASC
		)
		WITH 
		(
			PAD_INDEX  = OFF
			, STATISTICS_NORECOMPUTE  = OFF
			, IGNORE_DUP_KEY = OFF
			, ALLOW_ROW_LOCKS  = ON
			, ALLOW_PAGE_LOCKS  = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
	
	INSERT INTO [DOCSADM].[TIPO_COMPONENTI] (CHA_TIPO_COMPONENTI,DESCRIZIONE)VALUES('0','Active X')
	
	INSERT INTO [DOCSADM].[TIPO_COMPONENTI] (CHA_TIPO_COMPONENTI,DESCRIZIONE)VALUES('1','Smart Client')
	
END

