ALTER TABLE DPA_SCHEMA_PROCESSO_FIRMA
ADD DTA_CREAZIONE DATETIME

UPDATE DPA_SCHEMA_PROCESSO_FIRMA SET DTA_CREAZIONE  = GETDATE()
WHERE DTA_CREAZIONE IS NULL

ALTER TABLE DPA_AREA_LAVORO
ADD VAR_MOTIVO VARCHAR(200) DEFAULT NULL

ALTER TABLE DPA_STATI
ADD ID_PROCESSO_FIRMA INT DEFAULT NULL

ALTER TABLE DPA_ISTANZA_PROCESSO_FIRMA
ADD CHA_CAMBIO_STATO_DIAG CHAR(1) DEFAULT '0'

ALTER TABLE DPA_PASSI
ADD CHA_STATO_AUTOMATICO_LF CHAR(1) DEFAULT '0'

CREATE TABLE DPA_ISTANZA_PROC_FIRMA_STO
(
 SYSTEM_ID INT primary key IDENTITY(1,1) NOT NULL,  
 ID_USER VARCHAR(255), 
 DOC_NUMBER INT, 
 ID_ISTANZA_PROCESSO INT,
 DTA_DATE DATETIME, 
 VAR_DESC_AZIONE VARCHAR(255), 
 ID_PEOPLE INT, 
 ID_RUOLO INT, 
 ID_PEOPLE_DELEGATO INT,
 CHA_CAMBIO_STATO_DIAG CHAR(1)
)

CREATE TABLE DPA_REPORT_PROCESSI_TICK
(
 SYSTEM_ID INT primary key IDENTITY(1,1) NOT NULL  , 
 ID_REPORT_PROCESSI INT,
 ID_PROCESSO INT, 
 NOME_PROCESSO VARCHAR(256), 
 ID_RUOLO_CREATORE INT, 
 ID_UTENTE_CREATORE INT,
 ID_PASSO INT,
 ID_RUOLO_COINVOLTO INT, 
 ID_UTENTE_COINVOLTO INT
)
