using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NttDataWA.Utils
{
    public enum WebConfigKeys
    {
        MULTI_LANGUAGES,
        LANGUAGES_PATH,
        LANGUAGES,
        EXECUTIONTIMEOUT,
        PROXY,
        PROXYURL,
        PROXYCREDENTIALS,
        PROXYUSERNAME,
        PROXYPASSWORD,
        PROXYDOMAIN,
        LANGUAGES_DIRECTION,
        LANGUAGES_LABEL,
        SHIBSSO,
        SSOURL,
        POLICY_AGENT_ENABLED,
        AUTENTICAZIONE_WINDOWS,
        ADMINISTERED_LOGIN_MODE,
        CHIAVE_TOKEN,
        STATIC_ROOT_PATH,
        AUTO_FORCE_LOGIN,
        FE_MAX_LENGTH_DESC_ALLEGATO,
        APPLICATION_NAME,
        COPYRIGHT_INFORMATION,
        DISABLE_LOGOUT_CLOSE_BUTTON,
        DOCUMENT_AUTOPREVIEW,
        ENABLE_UFFICIO_REF, 
        MEZZO_SPEDIZIONE,
        PROT_DATA_ORA_MODIFICA,
        CATENE_DOCUMENTALI_TRASVERSALI,
        USE_CODICE_OGGETTO,
        CODICE_APPLICAZIONE,
        VISUALIZZA_CODICE_MODELLI_TRASM,
        DiagrammiStato,
        LISTE_DISTRIBUZIONE,
        ProfilazioneDinamica,
        MITTENTE_DEFAULT,
        SET_DATA_VISTA_GRD,
        UT_TX_RUOLO_CHECKED,
        VIS_UNIFICATA,
        VISUALIZZA_NOTE_PROTOCOLLO,
        FILE_ACQ_SIZE_MAX,
        LENGTH_CAMPI_PROFILATI,
        ENABLE_CODBIS_SEGNATURA,
        DOCUMENT_PDF_CONVERT,
        DOCUMENT_PDF_CONVERT_ENABLED,
        TRUNCATESTRING,
        TRUNCATESTRING_MITDEST,
        NON_VISUALIZZA_FRECCIA_RISPOSTA,
        CERCA_DUPLICATI_PROTOCOLLO,
        CERCA_DUPLICATI_PROTOCOLLO_2,
        VISUALIZZA_ALERT_PROTOCOLLO_CREATO,
        FE_MAX_LENGTH_NOTE,
        VISUALIZZA_NOTIFICHE_PEC,
        AUTOCOMPLETE_MINIMUMPREFIXLENGTH,
        ABILITAZIONE_FLAG_RUBRICA,
        IMPORT_MASSIVO,
        ADOBE_ACROBAT_INTEGRATION,
        ADOBE_ACROBAT_INTEGRATION_CLASS_ID,
        SCAN_WITH_ADOBE_ACROBAT_INTEGRATION,
        ENABLE_CONVERT_PDF_ON_SIGN,
        RIPROPONI_AVANZATO_ENABLED,
        INOLTRA_DOC,
        SHOW_DOCUMENT_AS_PDF_FORMAT,
        StampaDescrizioneAmministrazioneInEtichetta,
        StampaClassificazioneInEtichetta,
        StampaFascicoloInEtichetta,
        URL_INIFILE_DISPOSITIVO_STAMPA,
        ATTIVA_CODICE_DESCRIZIONE_AMMINISTRAZIONE_MITTENTE,
        ProfilazioneDinamicaFasc,
        STATO_REG_APERTO,
        STATO_REG_CHIUSO,
        FILTRO_APPLICAZIONE,
        LITEDOCUMENT,
        LAYOUT,
        VISUALIZZA_OGGETTO_COMM_REF,
        ENABLE_TIMESTAMP_DOC,
        CERCA_SOTTOFASCICOLI,
        GV_EXPORT_ENABLE,
        MAX_DOC_CAN_IMPORT,
        ENABLE_OWNER_PROTO_FOR_IMPORT_PROCEDURES,
        MAX_PRJ_CAN_IMPORT,
        ORDINAMENTO_ORGANIGRAMMA,
        NO_BROWSER_CONTROL,
        LOGOUT_REDIRECT_URL,
        LABELS_PATH,
        DYMO_DOCNUMBER_PREFIX,
        FATTURAPA_XSL_URL,
        AUTENTICAZIONE_FEDERATA_SSO
    }

    public enum DBKeys
    {
		FE_MAX_LENGTH_OGGETTO,
        FE_RICEVUTA_PROTOCOLLO_PDF,
        FE_FASC_RAPIDA_REQUIRED,
        FE_NUOVO_FASC_DIRECT,
        FE_INTERNAL_PROTOCOL,
        FE_CEDI_DIRITTI_IN_RUOLO,
        FE_CEDI_DIRITTI_UTENTE,
        FE_KEY_WORD,
        ATIPICITA_DOC_FASC,
        FE_MAX_LENGTH_DESC_TRASM,
        FE_NEW_RUBRICA_VELOCE,
        FE_ENABLE_MITTENTI_MULTIPLI,
        ENABLE_RIFERIMENTI_MITTENTE,
        GESTIONE_REPERTORI,
        FE_TYPE_DOC_REQUIRED,
        FE_BLOCCA_CLASS,
        CHECK_MITT_INTEROPERANTE,
        CHECK_MAILBOX_INTEROPERANTE,
        FE_TAB_TRASM_ALL,
        ENABLE_UFFICIO_REF,
        FE_KEY_WORDS,
        CONVERSIONE_PDF_SINCRONA_LC,
        CONVERSIONE_PDF_LATO_SERVER,
        FE_MULTI_STAMPA_ETICHETTA,
        FE_SEDE_TRASM,
        FE_RIPROPONI_CON_CONOSCENZA,
        FE_FASC_PRIMARIA,
        MAX_ROW_SEARCHABLE,
        FE_PAGING_ROW_DOC,
        FE_PAGING_ROW_PROJECT,
        FE_FILTRO_ALLEGATI_ESTERNI,
        FE_MAX_LENGTH_DESC_FASC,
        FE_IS_PRESENT_NOTE,
        FE_PAGING_ROW_DOCINFASC,
        FE_CHECK_TITOLARIO_ATTIVO,
        FE_VERIFICA_NOME,
        FE_MODELLI_DELEGA,
        FE_EXPORT_DA_MODELLO,
        FE_PAGING_ROW_TRASM,
        ARCHIVIO_DEPOSITO,
        VIS_SEGNATURA_REPERTORI,
        FE_RENDER_PDF,
        FE_REQ_CONV_PDF,
        INTEROP_SERVICE_ACTIVE,
        FE_STAMPA_UNIONE,
        FE_TRANS_FORW,
        FE_ENABLE_AMMRF,
        FE_CHECK_DISABLE_CONTROL_REMOVE_NOTIFY,
        FE_GESTIONE_SCAMBIA_ALLEGATI,
        FE_ENABLE_CHECK_MEANS_SENDING,
        FE_INVOICE,
        FE_FULLTEXT_SEARCH,
        FE_PROSPETTI_R5,
        FE_AUTO_FORCE_LOGIN,
        FE_SIGN_WITH_HASH,
        FE_WA_CONSERVAZIONE,
        FE_LIBRO_FIRMA_COLUMN_RECIPIENT,
        FE_LIBRO_FIRMA_COLUMN_TYPOLOGY,
        FE_URL_XSL_RAPPORTO_VERS,
        FE_DISABLE_BTN_REMOVE_DOC_REP,
        FE_DISABLE_BTN_SWAP_DOC_REP,
        FE_SELEZIONI_SMISTAMENTO,
        FE_LIBRO_FIRMA,
        FE_RIC_DESC_ALLEGATI,
        FE_SIGN_WITH_HASH_SM,
        FE_MAX_SEL_LF,
        FE_MAX_SEL_SIZE_LF,
        FE_MAX_DOC_VERSAMENTO,
        FE_CREA_GRIGIO_DA_FASCICOLO,
        FE_CREA_RISPOSTA_DA_FASCICOLO,
        FE_CREA_FASC_CON_COD_TIT_DEL_DOC,
        BE_NUM_ULTIMI_DOC_VISUALIZZATI,
        FE_ENABLE_FILTER_EVENT,
        MAX_YEARS_SEARCHABLE,
        MAX_INTERVAL_DATE_SEARCHABLE,
        FE_TIPO_RUOLO_LIBRO_FIRMA,
        ENABLE_TASK,
        FE_FASC_REQUIRED_TIPI_DOC,
        FE_ENABLE_DATA_REPERTORIO,
        LOCK_COFIRMA,
        FE_ENABLE_DRAG_AND_DROP,
        FE_MAX_RECIPIENTS_TO_SEND,
        FE_SET_TIPO_FIRMA,
        ENABLE_FASCICOLO_PUBBLICO,
        FE_ENABLE_FLUSSO_AUTOMATICO,
        FE_RIC_REPERTORIO,
        FE_DISABLED_CODICE_IPA,
        BE_ENABLE_PORTALE_PROCEDIMENTI,
        FE_DO_BIG_FILE_MIN, FE_DO_BIG_FILE_MAX,
        FE_DO_SEND_BIG_FILE,
        ASPOSE_PDF_CONVERSION,
        BLOCCO_MODIFICHE_DOC_IN_LF,
        FE_DOMINI_HSM_FORZA_ANNIDATA,
        NOTIFICA_DEST_NO_INTEROP_OBB
    }

    public enum HMdiritti
	{
        HDdiritti_Waiting = 20,         // trasmissione con Workflow in attesa di ACCETTAZIONE / RIFIUTO
        HMdiritti_Read    = 45,         // solo lettura
        HMdiritti_Write   = 63,         // lettura + scrittura
		HMdiritti_Eredita = 63,         // eredita diritto
        HMdiritti_Proprietario = 255    // proprietario
    }

    public enum TypeProfiledFields
    {
        CORRISPONDENTE
    }

    public class Constans {
        public const string TYPE_NONE = "0";
        public const string TYPE_ACTIVEX = "1";
        public const string TYPE_SMARTCLIENT = "2";
        public const string TYPE_APPLET = "3";
        public const string TYPE_SOCKET = "4";
    }

    public class TipoFirma
    {
        public const String NESSUNA_FIRMA = "N";
        public const String ELETTORNICA = "E";
        public const String PADES = "P";
        public const String CADES = "C";
        public const String TSD = "T";
        public const String XADES = "X";
        public const String PADES_ELETTORNICA = "PE";
        public const String CADES_ELETTORNICA = "CE";
        public const String TSD_ELETTORNICA = "TE";
        public const String XADES_ELETTORNICA = "XE";
    }
}
