DROP TABLE DPA_HSMPIN;

CREATE TABLE DPA_HSMPIN
(
  PEOPLE_SYSTEM_ID NUMBER(10) NOT NULL,
  PIN VARCHAR2(128 BYTE) NOT NULL
)
TABLESPACE PITRE_INFOTN_DATA_COLL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;