<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DocsPaVO</AssemblyName>
    <RootNamespace>DocsPaVO</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="..\Pi3.App.Legacy.WebApi.Application\Pi3.App.Legacy.WebApi.Application.csproj" />
  </ItemGroup>
</Project>