CREATE TABLE DPA_AREA_ESIBIZIONE
(
  SYSTEM_ID                  NUMBER             NOT NULL,
  ID_AMM                     NUMBER,
  ID_PEOPLE                  NUMBER,
  ID_RUOLO_IN_UO             NUMBER,
  CHA_STATO                  CHAR(1 BYTE),   
  VAR_NOTE                   VARCHAR2(500 BYTE),
  VAR_DESCRIZIONE            VARCHAR2(250 BYTE),
  DATA_CREAZIONE             DATE, 
  DATA_CERTIFICAZIONE        DATE,
  DATA_CHIUSURA              DATE,
  DATA_RIFIUTO               DATE,
  VAR_NOTE_RIFIUTO           VARCHAR2(256 BYTE),
  ID_PEOPLE_CERTIFICATORE    NUMBER,
  VAR_MARCA_TEMPORALE        VARCHAR2(3000 BYTE),
  VAR_FIRMA_RESPONSABILE     VARCHAR2(1024 BYTE),
  CHA_CERTIFICAZIONE         CHAR(1 BYTE),
  VAR_FILE_CHIUSURA          CLOB,
  VAR_FILE_CHIUSURA_FIRMATO  CLOB,
  ID_PROFILE_CERTIFICAZIONE  NUMBER
)


CREATE TABLE DPA_ITEMS_ESIBIZIONE
(
  SYSTEM_ID                NUMBER               NOT NULL,
  ID_ESIBIZIONE            NUMBER,
  ID_PROFILE               NUMBER,
  ID_PROJECT               NUMBER,
  CHA_TIPO_DOC             CHAR(1 BYTE),
  VAR_OGGETTO              VARCHAR2(2000 BYTE),
  ID_REGISTRO              NUMBER,
  DATA_INS                 DATE,
  CHA_STATO                CHAR(1 BYTE),
  VAR_XML_METADATI         CLOB,
  SIZE_ITEM                NUMBER,
  COD_FASC                 VARCHAR2(64 BYTE),
  DOCNUMBER                NUMBER,
  CHA_TIPO_OGGETTO         CHAR(1 CHAR),
  VAR_TIPO_FILE            VARCHAR2(32 BYTE),
  NUMERO_ALLEGATI          NUMBER,
  CHA_ESITO                CHAR(1 BYTE),      
  VAR_TIPO_ATTO            VARCHAR2(64 BYTE),
  ID_CONSERVAZIONE	   NUMBER  
)