--------------------------------------------------------
--  DDL for Index COD_RUBRICA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITCOLL_6GIU12"."COD_RUBRICA" ON "ITCOLL_6GIU12"."DPA_CORR_GLOBALI" ("VAR_COD_RUBRICA", "ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 7340032 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
