--------------------------------------------------------
--  DDL for Index DR$INDX_OGG_TEXT$X
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$X" ON "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" ("TOKEN_TEXT", "TOKEN_TYPE", "TOKEN_FIRST", "TOKEN_LAST", "TOKEN_COUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS 2 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
