--------------------------------------------------------
--  DDL for Index INDX_UPPER_VAR_COD_RUBRICA
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."INDX_UPPER_VAR_COD_RUBRICA" ON "ITCOLL_6GIU12"."DPA_CORR_GLOBALI" (UPPER("VAR_COD_RUBRICA")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
