--------------------------------------------------------
--  DDL for Index IX_UT_NOME
--------------------------------------------------------

  CREATE UNIQUE INDEX "ITCOLL_6GIU12"."IX_UT_NOME" ON "ITCOLL_6GIU12"."UTENTI" ("NOME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
