if (not exists (select * from @db_user.DPA_LOCK where VAR_SEMAFORO='PROTOCOLLO'))
begin
  INSERT INTO @db_user.DPA_LOCK ( NUM_STATO, VAR_SEMAFORO ) VALUES ( 0, 'PROTOCOLLO')
end
GO

--APPS

if (not exists (select * from @db_user.APPS where DESCRIPTION='Physical Document'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES (NULL, 'Physical Document', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL, 'N', 'N', NULL, NULL) 
end



if (not exists (select * from @db_user.APPS where APPLICATION='FOLDER'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES (
'FOLDER', 'Profiled Folder', NULL, 0, NULL, 2, 'Y', 'N', 'ZZZ', 'Y', 'N', NULL
, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 'N', 'N', NULL, NULL) 
end


if (not exists (select * from @db_user.APPS where APPLICATION='LOTUS WORD PRO'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('LOTUS WORD PRO', 'Lotus Word Pro', 'N', NULL, 'N', 2, 'Y', 'N', 'LWP', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/lotus') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='MS OUTLOOK'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, [LANGUAGE], VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('MS OUTLOOK', 'Microsoft Outlook', 'N', NULL, 'N', 2, 'Y', 'N', 'MSG', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, NULL) 
end



if (not exists (select * from @db_user.APPS where APPLICATION='MS WORD'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('MS WORD', 'Microsoft Word', 'N', NULL, 'Y', 2, 'Y', 'N', 'DOC', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/msword') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='MS EXCEL'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('MS EXCEL', 'Microsoft Excel', 'N', NULL, 'N', 3, 'Y', 'N', 'XLS', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/vnd.ms-excel') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='DOCSIMAGE'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('DOCSIMAGE', 'Imaging', 'N', NULL, 'Y', 2, 'Y', 'N', 'TIF', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'image/tiff') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='ACROBAT'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('ACROBAT', 'Adobe Acrobat', 'N', NULL, 'N', 2, 'Y', 'N', 'PDF', 'Y', 'Y', NULL, 1, 938, NULL, 'N', NULL, NULL, NULL, NULL, 'N', 'N', NULL, 'application/pdf') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='L123-97'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('L123-97', 'Lotus 123-97', NULL, 5, 'Y', 2, 'Y', 'N', '123', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/lotus') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='QPW'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('QPW', 'Quattro Pro', NULL, NULL, 'Y', 2, 'Y', 'N', 'QPW', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/quattro') 
end




if (not exists (select * from @db_user.APPS where APPLICATION='MS PROJECT'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('MS PROJECT', 'Microsoft Project', 'N', NULL, 'Y', 3, 'Y', 'N', 'MPP', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'Y', NULL, 'application/vnd.ms-project') 
end




if (not exists (select * from @db_user.APPS where APPLICATION='WORDPERFECT'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('WORDPERFECT', 'WordPerfect', 'N', NULL, 'Y', 2, 'Y', 'N', 'WPD', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/wordpfct') 
end




if (not exists (select * from @db_user.APPS where APPLICATION='PRESENTATIONS'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('PRESENTATIONS', 'Presentations', 'N', NULL, 'Y', 2, 'Y', 'N', 'SHW', 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, NULL) 
end




if (not exists (select * from @db_user.APPS where APPLICATION='FAWIN'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) 
VALUES ('FAWIN', 'Full Authority for Windows', 'N', NULL, 'N', 2, 'N', 'N', 'TOA', 'N', 'N', NULL, 1, NULL, NULL, 'N', NULL, NULL, '0', NULL, 'N', 'N', NULL, 'application/fawin') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='CITERITE'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('CITERITE', 'CiteRite for Windows', 'N', NULL, 'N', 2, 'N', 'N', 'CIT', 'N', 'N'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '0', NULL, 'N', 'N', NULL, 'application/citerite') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='MS POWERPOINT'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('MS POWERPOINT', 'Microsoft PowerPoint', 'N', NULL, 'Y', 2, 'Y', 'N', 'PPT', 'Y'
, 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/vnd.ms-powerpoint') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='DELTAVIEW'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('DELTAVIEW', 'DeltaView', 'N', NULL, 'N', 2, 'Y', 'N', 'WDF', 'Y', 'Y', NULL
, 1, NULL, NULL, 'Y', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/dcwin') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='WEB PUBLISHING'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('WEB PUBLISHING', 'Hummingbird Web Publishing', 'N', NULL, 'N', 2, 'Y', 'N', 'WPP'
, 'Y', 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, NULL) 
end


if (not exists (select * from @db_user.APPS where APPLICATION='HTML'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('HTML', 'Web Publishing Browser (html)', 'N', NULL, 'N', 2, 'Y', 'N', 'HTML', 'Y'
, 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'text/html') 
end


if (not exists (select * from @db_user.APPS where APPLICATION='PUB BROWSER'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('PUB BROWSER', 'Web Publishing Browser (htm)', 'N', NULL, 'N', 2, 'Y', 'N', 'HTM', 'Y'
, 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'text/htm') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='PUB GIF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('PUB GIF', 'Web Publishing GIF', 'N', NULL, 'N', 2, 'Y', 'N', 'GIF', 'Y', 'Y'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'image/gif') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='PUB JPG'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('PUB JPG', 'Web Publishing JPG', 'N', NULL, 'N', 2, 'Y', 'N', 'JPG', 'Y', 'Y'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'image/jpg') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='PUB PNG'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('PUB PNG', 'Web Publishing PNG', 'N', NULL, 'N', 2, 'Y', 'N', 'PNG', 'Y', 'Y'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'image/png')
end


 
if (not exists (select * from @db_user.APPS where APPLICATION='PUB XML'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('PUB XML', 'Web Publishing XML', 'N', NULL, 'N', 2, 'Y', 'N', 'XML', 'Y', 'Y'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'image/xml') 
end



if (not exists (select * from @db_user.APPS where APPLICATION='VISIO'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('VISIO', 'Microsoft Visio', 'N', NULL, 'Y', 2, 'Y', 'N', 'VSD', 'Y', 'Y', NULL
, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'N', NULL, 'application/vnd.visio')
end



if (not exists (select * from @db_user.APPS where APPLICATION='AUTOCAD'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('AUTOCAD', 'AutoCAD DM Extension', 'N', NULL, 'Y', 3, 'Y', 'N', 'DWG', 'Y', 'Y'
, NULL, 1, NULL, NULL, 'N', NULL, NULL, '1', NULL, 'N', 'Y', NULL, 'application/dwg')
end



if (not exists (select * from @db_user.APPS where APPLICATION='RM'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('RM', 'DOCSRM Application - DO NOT DELETE', NULL, NULL, NULL, 2, 'Y', NULL, NULL
, NULL, 'N', NULL, NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL) 
end



if (not exists (select * from @db_user.APPS where APPLICATION='RM VIEW'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('RM VIEW', 'RM Report Viewer', NULL, 0, NULL, 2, 'Y', NULL, 'QRP', NULL, 'N'
, NULL, NULL, 0, 0, 'N', NULL, NULL, NULL, 'QRPRM Saved Reports', 'N', 'N', NULL
, NULL)
end




if (not exists (select * from @db_user.APPS where APPLICATION='RTF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('RTF', 'Rich Text Format', NULL, NULL, NULL, 2, 'Y', NULL, 'RTF', NULL, 'Y'
, NULL, NULL, 935, 0, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'application/rtf')
end



if (not exists (select * from @db_user.APPS where APPLICATION='GEN_TXT'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('GEN_TXT', 'GEN_TXT', NULL, NULL, NULL, 2, NULL, NULL, 'TXT', NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
end




if (not exists (select * from @db_user.APPS where APPLICATION='GEN_DOC.P7M'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('GEN_DOC.P7M', 'GEN_DOC.P7M', NULL, NULL, NULL, 2, NULL, NULL, 'DOC.P7M', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
end


 

if (not exists (select * from @db_user.APPS where APPLICATION='GEN_DOC.PDF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('GEN_DOC.PDF', 'GEN_DOC.PDF', NULL, NULL, NULL, 2, NULL, NULL, 'DOC.PDF', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
end


 
if (not exists (select * from @db_user.APPS where APPLICATION='GEN_TXT.PDF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('GEN_TXT.PDF', 'GEN_TXT.PDF', NULL, NULL, NULL, 2, NULL, NULL, 'TXT.PDF', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
end



if (not exists (select * from @db_user.APPS where APPLICATION='GEN_TIF.PDF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ('GEN_TIF.PDF', 'GEN_TIF.PDF', NULL, NULL, NULL, 2, NULL, NULL, 'TIF.PDF', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
end


if (not exists (select * from @db_user.APPS where APPLICATION='DIGITAL SIGNF'))
begin
INSERT INTO @db_user.APPS (APPLICATION, DESCRIPTION, COUNT_KEYS, TIMEOUT, VER_TOLERANT,
FILING_SCHEME, VALID_ON_PROFILE, READ_ONLY, DEFAULT_EXTENSION, OPEN_LAUNCH, ON_DESKTOP,
DOS_MONITORING, LANGUAGE, VIEWER, PRINTING, DISABLED, OUTPUT_EXTS, PDFCOMPAT, INTEGRATED,
FILE_TYPES, SUPER_APP, USE_UNCNAME, DIRMON_STUBCHECK, MIME_TYPE ) VALUES ( 
'DIGITAL SIGNF', 'Digital Sign Reader', 'N', NULL, 'N', 2, 'Y', 'N', 'P7M', 'Y'
, 'Y', NULL, 1, NULL, NULL, 'N', NULL, NULL, 1, NULL, 'N', 'N', NULL, 'application/pkcs7-mime')
end
GO



--documenttypes
if (not exists (select * from @db_user.DOCUMENTTYPES where TYPE_ID='LETTERA'))
begin
INSERT INTO @db_user.DOCUMENTTYPES ( TYPE_ID, DESCRIPTION, DISABLED, STORAGE_TYPE, RETENTION_DAYS,
MAX_VERSIONS, MAX_SUBVERSIONS, FULL_TEXT, TARGET_DOCSRVR, RET_2, RET_2_TYPE, KEEP_CRITERIA,
VERSIONS_TO_KEEP, CHA_TIPO_CANALE ) VALUES ( 'LETTERA', 'LETTERA', NULL, 'A', 0, 99, 26, 'N', 0, 0, 'A', 'L', 0, 'L')
end
GO


if (not exists (select * from @db_user.DOCUMENTTYPES where TYPE_ID='MAIL'))
begin
INSERT INTO @db_user.DOCUMENTTYPES (  TYPE_ID, DESCRIPTION, DISABLED, STORAGE_TYPE, RETENTION_DAYS,
MAX_VERSIONS, MAX_SUBVERSIONS, FULL_TEXT, TARGET_DOCSRVR, RET_2, RET_2_TYPE, KEEP_CRITERIA,
VERSIONS_TO_KEEP, CHA_TIPO_CANALE ) VALUES (  'MAIL', 'MAIL', NULL, 'A', 0, 99, 26, 'N', 0, 0, 'A', 'L', 0, 'M')
end
GO


--dpa_ragione_trasm
if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='PRIVACY'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'PRIVACY', 'N', '1', 'W', 'T', '0', 'Tale ragione puo'' essere utilizzata per dare la visibilita'' su un documento ad un ruolo o persona non estendendo la visibilita'' ai superiori gerarchici del destinatario'
, '0', NULL, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='APPROVAZIONE'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'APPROVAZIONE', 'W', '1', 'W', 'S', '0', 'Tale ragione puo'' essere utilizzata per sottoporre ai propri superiori gerarchici un documento per approvazione. E'' prevista una esplicita accettazione o rifiuto da parte del destinatario'
, '1', NULL, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='RISPOSTA'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'RISPOSTA', 'W', '0', 'W', 'S', '0', 'Ragione Risposta', '1', NULL
, 'R') 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='ASSEGNAZIONE'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'ASSEGNAZIONE', 'W', '1', 'W', 'I', '1', 'Tale ragione puo'' essere utilizzata per assegnare ai propri inferiorii gerarchici un documento . E'' prevista una esplicita accettazione o rifiuto da parte del destinatario'
, '1', NULL, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='INOLTRO'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'INOLTRO', 'N', '1', 'W', 'T', '0', 'Tale ragione puo'' essere utilizzata per dara la visibilita'' su un documento ad un utente o ruolo. I possibili destinatari sono tutti coloro che hanno visibilita'' sul registro'
, '1', NULL, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='VISIONE'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'VISIONE', 'N', '0', 'R', 'T', '0', 'Ragione Visione', '1', NULL
, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='ALLA FIRMA'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'ALLA FIRMA', 'W', '0', 'W', 'S', '0', 'Tale ragione puo'' essere utilizzata per sottoporre ai propri superiori gerarchici un documento da firmare. E'' prevista una esplicita accettazione o rifiuto da parte del destinatario'
, '1', NULL, NULL) 
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='CONCLUSIONE'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'CONCLUSIONE', 'W', '0', 'W', 'S', '0', 'Notifica conclusione delle attivita'''
, '1', NULL, 'C')
end
GO


if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='INTEROPERABILITA'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'INTEROPERABILITA', 'I', '0', 'W', 'T', '0', 'Ragione di trasmissione per interoperabilita''', '1',NULL , NULL)
end
GO

if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='PARILIVELLO'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'PARILIVELLO', 'N', '1', 'W', 'P', '0', 'Trasmissione a pari livello','0',NULL ,NULL)
end
GO

if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where VAR_DESC_RAGIONE='RIFIUTO'))
begin
INSERT INTO @db_user.DPA_RAGIONE_TRASM ( VAR_DESC_RAGIONE,
CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA,
ID_AMM, CHA_TIPO_RISPOSTA ) VALUES ( 'RIFIUTO', 'N', '0', 'W', 'T', '0', 'Rifiuta una trasmissione ricevuta','0',NULL ,NULL)
end
GO

-- dpa_tipo_funzione
if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='LETT'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO, VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'LETT', 'LETTURA', '1')
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='IBRI'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'IBRI', 'IBRIDO PER FIRMA E ALLEGATI', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='WORK'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'WORK', 'LAVORO', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='FASC'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'FASC', 'GESTIONE FASCICOLI', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='FIRMA'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) 
VALUES ( 'FIRMA', 'FIRMA', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='REG'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'REG', 'STATO REGISTRI', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='GEST_REG'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'GEST_REG', 'GESTIONE REGISTRI', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='PROR'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'PROR', 'PROTOCOLLAZIONE ORDINARIA', '1') 
end
GO


if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='PRAV'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'PRAV', 'PROTOCOLLAZIONE AVANZATA', '1') 
end
GO

if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='REPORT_TRASM'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE (VAR_COD_TIPO, VAR_DESC_TIPO_FUN, CHA_VIS ) 
VALUES ( 'REPORT_TRASM', 'REPORT TRASMISSIONI', '1') 
end
GO

if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='PRAU'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ( 'PRAU', 'PROTOCOLLAZIONE AUTOMATICA', '1')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_FUNZIONE where VAR_DESC_TIPO_FUN='PROTO_EME'))
begin
INSERT INTO @db_user.DPA_TIPO_FUNZIONE ( VAR_COD_TIPO,VAR_DESC_TIPO_FUN, CHA_VIS ) VALUES ('PROTO_EME', 'PROTOCOLLAZIONE DI EMERGENZA', '1')
end
GO

-- DPA_ANAGRAFICA_FUNZIONI
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_NUOVOPROT'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_NUOVOPROT', 'Abilita il sottomenu'' Nuovo Protocollo del menu'' Documenti', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_NUOVODOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_NUOVODOC', 'Abilita il sottomenu'' Nuovo Documento del menu'' Documenti', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CERCA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_CERCA', 'Abilita il sottomenu'' Cerca del menu'' Documenti', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROTOCOLLA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROTOCOLLA', 'Abilita il tab Protocollo nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MIT_RUBRICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MIT_RUBRICA', 'Usato solo per la protocollazione semplice', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MIT_DETTAGLI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MIT_DETTAGLI', 'Abilita il pulsante dei dettagli del mittente nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MIT_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MIT_MODIFICA', 'Abilita il pulsante della modifica dei dettagli del mittente nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MIT_STORIA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MIT_STORIA', 'Abilita il pulsante dei dati storici dei mittenti nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MII_RUBRICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MII_RUBRICA', 'Usato solo per la protocollazione semplice', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MII_DETTAGLI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MII_DETTAGLI', 'Abilita il pulsante dei dettagli del mittente intermedio nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MII_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MII_MODIFICA', 'Abilita il pulsante della modifica dei dettagli del mittente intermedio nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_MII_STORIA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_MII_STORIA', 'Abilita il pulsante dei dati storici dei mittenti intermedi nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_IN_PRO_VERIFICAPREC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_IN_PRO_VERIFICAPREC', 'Abilita il pulsante di verifica del precedente protocollo mittente', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_GET_ADL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_GET_ADL', 'Abilita il pulsante della selezione dei documenti protocollati da ADL nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_PROTOCOLLA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_PROTOCOLLA', 'Abilita il pulsante Protocolla nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_SALVA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_SALVA', 'Abilita il pulsante Salva nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_RIPROPONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_RIPROPONI', 'Abilita il pulsante Riproponi nella pagina di protocollazione', NULL)
end
GO

 
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_SE_STAMPA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_SE_STAMPA', 'Abilita il pulsante Stampa nella sezione segnatura nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_OG_OGGETTARIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_OG_OGGETTARIO', 'Abilita il pulsante di selezione di un oggetto nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_OG_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_OG_MODIFICA', 'Abilita il pulsante di modifica di un oggetto nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_OG_STORIA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_OG_STORIA', 'Abilita il pulsante della storia oggetto nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_RUBRICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_RUBRICA', 'Abilita il pulsante di selezione di un destinatario nella rubrica nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_DETTAGLI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_DETTAGLI', 'Abilita il pulsante del dettaglio dei destinatari presenti nella list box della pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_PIU'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_PIU', 'Abilita il pulsante di aggiunta di un destinatario nella pagina di protocollazione', NULL)
end
GO

 
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_MODIFICA', 'Abilita il pulsante di modifica del destinatario nella pagina di protocollazione', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_STORIA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_STORIA', 'Abilita il pulsante dei dati storici del destinatario nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROFILO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROFILO', 'Abilita il tab Profilo nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_STAMPASCHEDA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_STAMPASCHEDA', 'Abilita il pulsante Stampa nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ADD_ADL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ADD_ADL', 'Abilita il pulsante di aggiunta ADL nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_DOC_VISUALIZZA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_DOC_VISUALIZZA', 'Abilita il pulsante Visualizza di un documento acquisito o presente sul file-system', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_DOC_VISUALIZZAZOOM'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_DOC_VISUALIZZAZOOM', 'Abilita il pulsante Zoom di un documento acquisito o presente sul file-system', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_TAB_TRASMISSIONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_TAB_TRASMISSIONI', 'Abilita il tab Trasmissioni nella pagina di gestione di un fascicolo', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_NEW_FOLDER'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_NEW_FOLDER', 'Abilita il pulsante Aggiungi nella pagina di gestione di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_STAMPE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_STAMPE', 'Abilita il sottomenu'' Stampe e rapporti del menu'' Gestione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_REG_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_REG_MODIFICA', 'Abilita il pulsante Modifica nella pagina di gestione di un registro', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='TRAS_CERCA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'TRAS_CERCA', 'Abilita il sottomenu'' Cerca del menu'' Trasmissioni', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CLA_VIS_PROC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_CLA_VIS_PROC', 'Abilita il pulsante di visualizzazione dei fascicoli procedimentali con la classifica selezionata', NULL) 
end
GO



if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CLA_GET_ADL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_CLA_GET_ADL', 'Abilita il pulsante di visualizzazione dei fascicoli procedimentali in area di lavoro', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CLA_INSERISCI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_CLA_INSERISCI', 'Abilita il pulsante Inserisci nella pagina di classificazione di un documento', NULL) 
end
GO



if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRA_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_TRA_MODIFICA', 'Abilita il pulsante Modifica nelle pagine di trasmissione di un documento e di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRA_TRASMETTI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_TRA_TRASMETTI', 'Abilita il pulsante Trasmetti nelle pagine di trasmissione di un documento e di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_SPEDISCI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_SPEDISCI', 'Abilita il pulsante Spedisci nalla pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_AREA_LAV'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_AREA_LAV', 'Abilita il sottomenu'' Area di lavoro del menu'' Gestione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_ELIMINA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_ELIMINA', 'Abilita il pulsante di eliminazione dei destinatari presenti nella list box della pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='TRAS_NUOVA_DA_TEMPL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'TRAS_NUOVA_DA_TEMPL', 'Abilita il pulsante Nuova da template nella pagina di gestione delle trasmissioni', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='TRAS_SALVA_TEMPL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'TRAS_SALVA_TEMPL', 'Abilita il pulsante Salva template nella pagina di gestione delle trasmissioni', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_OUT_DES_TIPO_INVIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_OUT_DES_TIPO_INVIO', 'Abilita il pulsante di descrizione tipo di spedizione nella pagina di protocollazione', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_DTA_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_DTA_MODIFICA', 'Abilita il pulsante di modifica della data di arrivo nella pagina della protocollazione', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_ELIMINAPAROLE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_ELIMINAPAROLE', 'Abilita il pulsante di eliminazione delle parole chiave nella pagina della creazione del profilo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_PROTOCOLLAG'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_PROTOCOLLAG', 'Abilita il pulsante Protocolla in giallo nella pagina di protocollazione', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_ANNULLA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PROT_ANNULLA', 'Abilita il pulsante Cancella nella pagina di protocollazione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_DOCUMENTI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_DOCUMENTI', 'Abilita il menu ''Documenti', 'W') 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_RICERCA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_RICERCA', 'Abilita il menu'' Ricerca', 'R') 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_FASCICOLI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_FASCICOLI', 'Abilita il menu'' Fascicoli', 'W') 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_TRASMISSIONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_TRASMISSIONI', 'Abilita il menu'' Trasmissione', 'W') 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_GESTIONE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_GESTIONE', 'Abilita il menu'' Gestione', 'W') 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_OPZIONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_OPZIONI', 'Abilita il menu'' Opzioni', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='MENU_LOGOUT'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'MENU_LOGOUT', 'Abilita il menu'' Logout', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_REGISTRI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_REGISTRI', 'Abilita il sottomenu'' Registri del menu'' Gestione', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='OPZIONI_CAMBIA_PWD'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'OPZIONI_CAMBIA_PWD', 'Abilita il sottomenu'' Cambia password del menu'' Opzioni', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ALLEGATI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ALLEGATI', 'Abilita il Tab Allegati nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ALL_AGGIUNGI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ALL_AGGIUNGI', 'Abilita il pulsante Nuovo nella pagina di gestione degli allegati di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ALL_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ALL_MODIFICA', 'Abilita il pulsante Modifica nella pagina di gestione degli allegati di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ALL_RIMUOVI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ALL_RIMUOVI', 'Abilita il pulsante Rimuovi nella pagina di gestione degli allegati di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_ALL_SOSTITUISCI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_ALL_SOSTITUISCI', 'Abilita il pulsante Scambia nella pagina di gestione degli allegati di un documento', NULL) 
end
GO



if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_VERSIONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_VERSIONI', 'Abilita il tab Versioni nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_VER_NUOVA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_VER_NUOVA', 'Abilita il pulsante Nuovo nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_VER_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_VER_MODIFICA', 'Abilita il pulsante Modifica nella pagina di gestione delle versioni di un documento', NULL)
end
GO

 
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_VER_RIMUOVI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_VER_RIMUOVI', 'Abilita il pulsante Rimuovi nella pagina di gestione delle versioni di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CLASSIFICAZIONE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_CLASSIFICAZIONE', 'Abilita il Tab Classifica nella pagina di gestione di un documento', NULL) 
end
GO



if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRASMISSIONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_TRASMISSIONI', 'Abilita il tab Trasmissioni nella pagina di gestione di un documento', NULL)
end
GO

 
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRA_NUOVA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_TRA_NUOVA', 'Abilita il pulsante Nuovo nelle pagine di trasmissione di un documento e di un fascicolo', NULL)
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_CANCELLA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_CANCELLA', 'Abilita il pulsante Rimuovi nella pagina di ricerca di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_CLA_TITOLARIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 
'DO_CLA_TITOLARIO', 'Abilita il pulsante di visualizzazione del Titolario nella pagina di Classificazione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_OGGETTARIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_OGGETTARIO', 'Abilita il pulsante di selezione di un oggetto nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_SELEZIONA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_SELEZIONA', 'Abilita il pulsante di selezione di una parole chiave nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_VISIBILITA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_VISIBILITA', 'Abilita il pulsante di visibilita'' nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_SALVA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_SALVA', 'Abilita il pulsante Salva nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_RIMUOVI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_RIMUOVI', 'Abilita il pulsante Rimuovi nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PRO_PREDISPONI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_PRO_PREDISPONI', 'Abilita il pulsante Predisponi nella pagina di gestione di un documento', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_DOC_ACQUISISCI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_DOC_ACQUISISCI', 'Abilita il pulsante di acquisizione di un file-documento tramite lo scanner o file-system', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_GESTIONE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_GESTIONE', 'Abilita il sottomenu'' Gestione fascicolo del menu'' Fascicoli', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_TAB_DOCUMENTO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_TAB_DOCUMENTO', 'Abilita il tab Documenti nella pagina di gestione di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_ADD_ADL'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_ADD_ADL', 'Abilita il pulsante Aggiungi area lavoro nella pagina di gestione di un fascicolo', NULL) 
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_MOD_FASCICOLO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_MOD_FASCICOLO', 'Abilita il pulsante Modifica nella pagina di gestione di un fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRA_STAMPA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE, CHA_TIPO_FUNZ ) 
VALUES ( 'DO_TRA_STAMPA', 'Abilita il pulsante di stampa delle trasmissioni relative ad un documento indipendentemente dalla visibilita''', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_DOC_FIRMA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_DOC_FIRMA', 'Abilita il pulsante della firma di un documento acquisito o presente sul file-system', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_APRICHIUDI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_APRICHIUDI', 'Abilita il pulsante Chiudi e riapri fascicolo nella pagina di gestione di un fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_DEL_FOLDER'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_DEL_FOLDER', 'Abilita il pulsante Rimuovi nella pagina di gestione di un fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_INS_DOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_INS_DOC', 'Abilita il pulsante Inserisci da area di lavoro nella pagina di gestione di un fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_MOD_FOLDER'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'FASC_MOD_FOLDER', 'Abilita il pulsante Modifica nella pagina di gestione di un fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_CASELLA_IST'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_CASELLA_IST', 'Abilita il pulsante Casella istituzionale nella pagina di gestione di un registro', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_REG_C_STATO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_REG_C_STATO', 'Abilita il pulsante Cambia stato nella pagina di gestione di un registro', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_REG_STAMPA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'GEST_REG_STAMPA', 'Abilita il pulsante Stampa nella pagina di gestione di un registro', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='PROTO_IN'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'PROTO_IN', 'Abilita la protocollazione in ingresso nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='PROTO_OUT'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'PROTO_OUT', 'Abilita la protocollazione in uscita nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_DOC_ADD_PAROLA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_DOC_ADD_PAROLA', 'Abilita il pulsante che consente di aggiungere una parola chiave dalla popup delle parole chiave', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='PROTO_EME'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('PROTO_EME', 'Abilita i ruoli alla creazione dei protocolli di emergenza', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='PROTO_OWN'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('PROTO_OWN', 'Abilita la protocollazione interna nella pagina di protocollazione e nelle pagine di ricerca dei documenti', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='FASC_NUOVO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('FASC_NUOVO', 'Abilita l''inserimento di un nuovo fascicolo', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_PROSPETTI'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('GEST_PROSPETTI', 'Abilita il pulsante per la gestione dei Prospetti Riepilogativi', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TRASM_SET_VISTE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('DO_TRASM_SET_VISTE', 'Abilita il pulsante Elimina trasmissioni nel risultato della ricerca delle COSE DA FARE', NULL) 
end
GO
---3.2.0
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='GEST_ORGANIGRAMMA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) values('GEST_ORGANIGRAMMA','Abilita il sottomenù Organigramma del menù Gestione per la visualizzazione e stampa dell''organigramma',NULL)
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='STAMPA_REG_UO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) values('STAMPA_REG_UO','Abilita la stampa dei protocolli filtrata per uo',NULL)
end
GO
-----
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_SMISTA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ( 'DO_SMISTA', 'Abilita il pulsante di smistamento documenti nella sezione COSE DA FARE > Documenti', NULL) 
end
GO
--fine 3.2.0

--POPOLAMENTO DPA_ANAGRAFICA LOG

if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='LOGIN'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('LOGIN', 'Accesso all''applicazione DocsPA', 'UTENTE', 'LOGIN')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='LOGOFF'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('LOGOFF','Effettuata la Logoff all''applicazione DocsPA','UTENTE','LOGOFF')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='AGG_PROT'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('AGG_PROT','Aggiunto un nuovo protocollo','DOCUMENTO','DOCUMENTOPROTOCOLLA')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='DOC_PROT'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('DOC_PROT','Protocollato un documento gia'' esistente','DOCUMENTO','DOCUMENTOPROTOCOLLA2')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='AGG_DOC_GRIGIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('AGG_DOC_GRIGIO','Inserito un documento grigio','DOCUMENTO','DOCUMENTOADDDOCGRIGIA')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='DEL_DOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('DEL_DOC','Rimosso un documento','DOCUMENTO','DOCUMENTOEXECRIMUOVISCHEDA')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='UPD_DOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('UPD_DOC','Modificato un documento','DOCUMENTO','DOCUMENTOSAVEDOCUMENTO')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='ANNULLA_PROTO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('ANNULLA_PROTO','Annullato un protocollo','DOCUMENTO','DOCUMENTOEXECANNULLAPROT')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='OPEN_DET_DOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('OPEN_DET_DOC','Aperto dettaglio di un documento','DOCUMENTO','DOCUMENTOGETDETTAGLIODOCUMENTO')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='ADD_ALLEGATO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('ADD_ALLEGATO','Aggiunto un nuovo allegato ad un documento','ALLEGATO','DOCUMENTOAGGIUNGIALLEGATO')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='ADD_VERSION'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('ADD_VERSION','Aggiunta una nuova versione ad un documento','DOCUMENTO','DOCUMENTOAGGIUNGIVERSIONE')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='TRASM_DOC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('TRASM_DOC','Trasmesso un documento','TRASMISSIONE','TRASMISSIONEEXECUTETRASM')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='NEW_FASC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('NEW_FASC','Creato un nuovo fascicolo','FASCICOLO','FASCICOLAZIONENEWFASCICOLO')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='NEW_FOLDER_FASC'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('NEW_FOLDER_FASC','Creato un nuovo folder in un fascicolo','FOLDER','FASCICOLAZIONENEWFOLDER')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='STATO_REG'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('STATO_REG','Cambiato stato al registro','REGISTRO','REGISTRICAMBIASTATO')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='STAMP_REG'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('STAMP_REG','Stampato Registro','REGISTRO','REGISTRIDISTAMPA')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='GET_FILE'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('GET_FILE','Visualizza un documento','DOCUMENTO','DOCUMENTOGETFILE')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='GET_FIRMA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('GET_FIRMA','Acquisizione di un documento Firmato','DOCUMENTO','DOCUMENTOPUTFILE')
end
GO
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='STAMPA_ETICHETTA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG VALUES ('STAMPA_ETICHETTA','Stampata etichetta di un documento','DOCUMENTO','DOCUMENTOSTAMPAETICHETTA')
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='CHECK_CASELLA'))
begin
Insert into @db_user.DPA_ANAGRAFICA_LOG
   (VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO)
 Values
   ('CHECK_CASELLA', 'Controllo casella istituzionale', 'INTEROPERABILITA', 'INTEROPERABILITARICEZIONE')
end
GO

if (not exists (select * from  @db_user.DPA_ANAGRAFICA_LOG
 where VAR_CODICE='SPEDIZIONE_DOCUMENTO'))
begin
Insert into @db_user.DPA_ANAGRAFICA_LOG
   (VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO)
 Values
   ('SPEDIZIONE_DOCUMENTO', 'Spedizione documento', 'INTEROPERABILITA', 'INTEROPERABILITASPEDIZIONE')
end
GO

--FINE POPOLAMENTO DPA_ANAGRAFICA LOG

-- TIPO ATTO
if (not exists (select * from @db_user.DPA_TIPO_ATTO where VAR_DESC_ATTO='DECRETO'))
begin
INSERT INTO @db_user.DPA_TIPO_ATTO ( VAR_DESC_ATTO ) VALUES ( 'DECRETO')
end
GO

 
if (not exists (select * from @db_user.DPA_TIPO_ATTO where VAR_DESC_ATTO='DELIBERA'))
begin
INSERT INTO @db_user.DPA_TIPO_ATTO ( VAR_DESC_ATTO ) VALUES ( 'DELIBERA') 
end
GO
-- FINE TIPO ATTO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TITOLARIO'))
begin
insert into @db_user.dpa_funzioni(COD_FUNZIONE,VAR_DESC_FUNZIONE,ID_TIPO_FUNZIONE)
select 'GEST_RUBRICA','GEST_RUBRICA', SYSTEM_ID from @db_user.dpa_tipo_funzione where var_cod_tipo='PROR'
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_TITOLARIO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI (COD_FUNZIONE,VAR_DESC_FUNZIONE)
VALUES ('GEST_RUBRICA','Abilita il sottomenu'' Rubrica dal menu'' Gestione')
end
GO

INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI (COD_FUNZIONE,VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ)
VALUES('DO_TITOLARIO','Abilita l''inserimento di un nuovo nodo di titolario',NULL)
go

--mancavano in sql
if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_MIT_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) VALUES ('DO_PROT_MIT_MODIFICA','Abilita il pulsante di modifica di un mittente nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_MIT_INT_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
VALUES ('DO_PROT_MIT_INT_MODIFICA','Abilita il pulsante di modifica di un mittente intermedio nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_DEST_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
VALUES ('DO_PROT_DEST_MODIFICA','Abilita il pulsante di modifica di un destinatario intermedio nella pagina di protocollazione', NULL) 
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI where COD_FUNZIONE='DO_PROT_DESTCC_MODIFICA'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
VALUES ('DO_PROT_DESTCC_MODIFICA','Abilita il pulsante di modifica di un destinatarioCC intermedio nella pagina di protocollazione', NULL) 
end
GO
---

-- profilazione dinamica
if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Campo di testo'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Campo di testo','CampoDiTesto')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Casella di selezione'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Casella di selezione','CasellaDiSelezione')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Selezione esclusiva'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Selezione esclusiva','SelezioneEsclusiva')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Menu a tendina'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Menu a tendina','MenuATendina')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Contatore'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Contatore','Contatore')
end
GO

if (not exists (select * from @db_user.DPA_TIPO_OGGETTO where tipo='Data'))
begin
INSERT INTO @db_user.DPA_TIPO_OGGETTO (Tipo, Descrizione)
VALUES('Data','Data')
end
GO

--3.2.1
if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='BLOCCO_DOCUMENTO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG (VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO)
VALUES ('BLOCCO_DOCUMENTO', 'Blocco', 'DOCUMENTO', 'CHECKOUTDOCUMENT')
end
GO

if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='RILASCIO_DOCUMENTO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG (VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO)
VALUES ('RILASCIO_DOCUMENTO', 'Rilascio del blocco', 'DOCUMENTO', 'CHECKINDOCUMENT')
end
GO


if (not exists (select * from @db_user.DPA_ANAGRAFICA_LOG where VAR_CODICE='ANNULLA_BLOCCO_DOCUMENTO'))
begin
INSERT INTO @db_user.DPA_ANAGRAFICA_LOG (VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO)
VALUES ('ANNULLA_BLOCCO_DOCUMENTO', 'Annullamento del blocco', 'DOCUMENTO', 'UNDOCHECKOUTDOCUMENT')
end
GO
--END 3.2.1
if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where (VAR_DESC_RAGIONE='COMPETENZA' and ID_AMM IS NULL)))
	begin
		INSERT INTO @db_user.DPA_RAGIONE_TRASM (VAR_DESC_RAGIONE, CHA_TIPO_RAGIONE, CHA_VIS , CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA, CHA_TIPO_RISPOSTA )
		VALUES ('COMPETENZA', 'W', '1', 'W', 'I', '0', 'Invia trasmissioni per competenza nella funzionalità di smistamento.', '1', 'C');
	end
GO

if (not exists (select * from @db_user.DPA_RAGIONE_TRASM where (VAR_DESC_RAGIONE='CONOSCENZA' and ID_AMM IS NULL)))
	begin
	INSERT INTO @db_user.DPA_RAGIONE_TRASM (VAR_DESC_RAGIONE, CHA_TIPO_RAGIONE, CHA_VIS , CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA, CHA_TIPO_RISPOSTA )
	VALUES ('CONOSCENZA', 'W', '1', 'R', 'I', '0', 'Invia trasmissioni per conoscenza nella funzionalità di smistamento.', '1', 'C');
	end
GO

--3.7

if (not exists(select * from @db_user.DPA_TODOLIST))
BEGIN
	delete from DPA_TODOLIST
END
GO

if (not exists(select * from @db_user.DPA_TODOLIST))
BEGIN
INSERT INTO @db_user.DPA_TODOLIST
SELECT dt.system_id, 
       dtu.id_trasm_singola, 
       dtu.system_id, 
       dt.dta_invio, 
       dt.id_people, 
       dt.id_ruolo_in_uo, 
       dtu.id_people, 
       dts.id_ragione, 
       dt.var_note_generali, 
       dts.var_note_sing, 
       dts.dta_scadenza, 
       dt.id_profile, 
       dt.id_project, 
       convert(INT,@db_user.vardescribe(dts.id_corr_globale, 'ID_GRUPPO')) AS id_ruolo_dest, 
       CONVERT(INT,@db_user.vardescribe(dt.id_profile, 'PROF_IDREG')) AS id_registro, 
       dts.cha_tipo_trasm 
  FROM DPA_TRASM_UTENTE dtu, 
       DPA_TRASM_SINGOLA dts,
         DPA_TRASMISSIONE dt 
 WHERE dtu.id_trasm_singola = dts.system_id 
       AND dts.id_trasmissione = dt.system_id 
       AND dtu.cha_in_todolist = 1
       AND dtu.cha_valida = '1' 
       AND dt.dta_invio IS NOT NULL
END
GO

if (not exists (select * from @db_user.APPS where DEFAULT_EXTENSION='DOCX'))
	begin
		 INSERT INTO @db_user.APPS (  APPLICATION, DESCRIPTION, FILING_SCHEME, DEFAULT_EXTENSION, MIME_TYPE ) 
		 VALUES (  'GEN_DOCX', 'GEN_DOCX', 2, 'DOCX', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'); 
	end
	else 
	UPDATE @db_user.APPS SET MIME_TYPE = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' WHERE UPPER(DEFAULT_EXTENSION) = 'DOCX';
GO


if (not exists (select * from @db_user.APPS where DEFAULT_EXTENSION='XLSX'))
	begin
		INSERT INTO @db_user.APPS ( APPLICATION, DESCRIPTION, FILING_SCHEME, DEFAULT_EXTENSION, MIME_TYPE ) 
		VALUES (  'GEN_XLSX', 'GEN_XLSX', 2, 'XLSX', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); 
	end
	else 
	UPDATE @db_user.APPS SET MIME_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' WHERE UPPER(DEFAULT_EXTENSION) = 'XLSX';
GO

if not exists(select * from @db_user.dpa_tipo_oggetto_fasc where Descrizione='Corrispondente')
BEGIN
insert into @db_user.dpa_tipo_oggetto_fasc VALUES('Corrispondente','Corrispondente')
END
GO

if not exists(select * from @db_user.dpa_tipo_oggetto where Descrizione='Corrispondente')
BEGIN
insert into @db_user.dpa_tipo_oggetto VALUES('Corrispondente','Corrispondente')
END
GO

if not exists (select * from @db_user.dpa_anagrafica_funzioni where cod_funzione = 'DO_DOC_SE_GRIGIO')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni( cod_funzione,var_desc_funzione,cha_tipo_funz)
values('DO_DOC_SE_GRIGIO', 'Abilita il pulsante Stampa nella pagina del profilo del documento',null)
END
GO

---3.7.7

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_FUNZIONI] where COD_FUNZIONE='DO_MODIFICA_MIT_TRASM'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_FUNZIONI] ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
VALUES ('DO_MODIFICA_MIT_TRASM', 'Abilita la modifica del mittente di una trasmissione nella pagina di Nuova Trasmissione', NULL);
END
GO

--3.8

if (not exists (select * from @db_user.DPA_ANAGRAFICA_FUNZIONI WHERE COD_FUNZIONE='DO_MODIFICA_MIT_TRASM'))
begin
	INSERT INTO @db_user.DPA_ANAGRAFICA_FUNZIONI (COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
	VALUES ('DO_MODIFICA_MIT_TRASM', 'Abilita la modifica del mittente di una trasmissione nella pagina di Nuova Trasmissione', NULL);
end
GO


update @db_user.dpa_ragione_trasm set 
VAR_TESTO_MSG_NOTIFICA_DOC='Le e'' stato trasmesso un documento con:'+CHAR(13)+CHAR(10)+
'RAGIONE: RAG_TRASM'+CHAR(13)+CHAR(10)+
'DESTINATARIO: DEST_TRASM'+CHAR(13)+CHAR(10)+
'SEGNATURA/ID: SEGN_ID_DOC'+CHAR(13)+CHAR(10)+
'OGGETTO: OGG_DOC'+CHAR(13)+CHAR(10)+
'NOTE GENERALI: NOTE_GEN'+CHAR(13)+CHAR(10)+
'NOTE INDIVIDUALI: NOTE_IND'+CHAR(13)+CHAR(10),
VAR_TESTO_MSG_NOTIFICA_FASC='Le e'' stato trasmesso un fascicolo con:'+CHAR(13)+CHAR(10)+
'RAGIONE: RAG_TRASM'+CHAR(13)+CHAR(10)+
'DESTINATARIO: DEST_TRASM'+CHAR(13)+CHAR(10)+
'CODICE: COD_FASC'+CHAR(13)+CHAR(10)+
'DESCRIZIONE: DESC_FASC'+CHAR(13)+CHAR(10)+
'NOTE GENERALI: NOTE_GEN'+CHAR(13)+CHAR(10)+
'NOTE INDIVIDUALI: NOTE_IND'+CHAR(13)+CHAR(10)
GO

if not exists(select * from @db_user.dpa_anagrafica_funzioni where cod_funzione='FASC_NUOVO_PRIVATO')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni (cod_funzione,var_desc_funzione) 
values ('FASC_NUOVO_PRIVATO','Abilita il check privato nella pagina di creazione di un fascicolo')
END
GO

if not exists(select * from @db_user.dpa_anagrafica_funzioni where cod_funzione='DO_PROTO_PRIVATO')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni (cod_funzione,var_desc_funzione) 
values ('DO_PROTO_PRIVATO','Abilita il check privato nella pagina di protocollazione')
END
GO

if not exists(select * from @db_user.dpa_anagrafica_funzioni where cod_funzione='DO_CREA_PRIVATO')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni (cod_funzione,var_desc_funzione) 
values ('DO_CREA_PRIVATO','Abilita il check privato nella pagina di profilazione')
END
GO

if not exists(select * from @db_user.dpa_anagrafica_funzioni where cod_funzione='DO_PROTO_PRIVATO_SEMPL')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni (cod_funzione,var_desc_funzione) 
values ('DO_PROTO_PRIVATO_SEMPL','Abilita il check privato nella pagina di protocollazione semplificata')
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_FUNZIONI] where COD_FUNZIONE='DO_MODIFICA_MIT_TRASM'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_FUNZIONI] ( COD_FUNZIONE, VAR_DESC_FUNZIONE,CHA_TIPO_FUNZ ) 
VALUES ('DO_MODIFICA_MIT_TRASM', 'Abilita la modifica del mittente di una trasmissione nella pagina di Nuova Trasmissione', NULL);
END
GO

if (NOT exists (select * from @db_user.DPA_DOCSPA ))
	begin
        INSERT INTO @db_user.DPA_DOCSPA ( dta_install, id_versions_I ) VALUES ( GETDATE(), '3.8' ) ;
    END        
GO

IF ((SELECT COUNT(*) FROM @db_user.DPA_DOCSPA where id_versions_I IS NULL AND id_versions_u IS NOT NULL)=0)
BEGIN
	INSERT INTO @db_user.DPA_DOCSPA (dta_update, id_versions_u ) VALUES ( GETDATE(), '3.8' );
END
GO
  
if (exists (select * from @db_user.DPA_DOCSPA where id_versions_u IS NOT NULL ))
	begin
        UPDATE @db_user.DPA_DOCSPA SET dta_update = GETDATE() , 
		id_versions_U = '3.8' WHERE id_versions_I IS NULL;      
    END
GO

if exists(select * from syscolumns where name='CHA_RF' and id in 
		(select id from sysobjects where name='DPA_EL_REGISTRI' and xtype='U'))
begin		
	UPDATE @db_user.DPA_EL_REGISTRI SET CHA_RF = 0 where CHA_RF is null;
end
GO


if not exists(select * from @db_user.dpa_anagrafica_funzioni where cod_funzione='DO_CREA_PERSONALE')
BEGIN
insert into @db_user.dpa_anagrafica_funzioni (cod_funzione,var_desc_funzione) 
values ('DO_CREA_PERSONALE','Abilita il check personale nella pagina di profilazione')
END
GO

if (not exists (select * from [@db_user].[DPA_TIPO_FUNZIONE] where VAR_COD_TIPO='DOC_RIS'))
BEGIN
INSERT INTO [@db_user].[DPA_TIPO_FUNZIONE](VAR_COD_TIPO, VAR_DESC_TIPO_FUN, CHA_VIS)
VALUES ('DOC_RIS', 'DOCUMENTAZIONE RISERVATA', '1'); 
END
GO


DECLARE @syscurrTipoFunz INT;
BEGIN


DECLARE currTipoFunz -- CURSORE CHE PRENDE L'ID
CURSOR LOCAL FOR
	SELECT SYSTEM_ID 
	FROM @db_user.DPA_TIPO_FUNZIONE 
	WHERE VAR_COD_TIPO='DOC_RIS'

OPEN currTipoFunz
FETCH NEXT FROM currTipoFunz
INTO @syscurrTipoFunz

WHILE @@FETCH_STATUS = 0

BEGIN

if (not exists (select * from [@db_user].[DPA_FUNZIONI] where COD_FUNZIONE='DO_FASC_PRIVATO'))
BEGIN
INSERT INTO [@db_user].[DPA_FUNZIONI](COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES ('DO_FASC_PRIVATO', 'DO_FASC_PRIVATO', @syscurrTipoFunz);
END

if (not exists (select * from [@db_user].[DPA_FUNZIONI] where COD_FUNZIONE='DO_PROTO_PRIVATO'))
BEGIN
INSERT INTO [@db_user].[DPA_FUNZIONI] (COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES ('DO_PROTO_PRIVATO', 'DO_PROTO_PRIVATO', @syscurrTipoFunz); 
END

if (not exists (select * from [@db_user].[DPA_FUNZIONI] where COD_FUNZIONE='DO_CREA_PRIVATO'))
BEGIN
INSERT INTO [@db_user].[DPA_FUNZIONI] (COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES ('DO_CREA_PRIVATO', 'DO_CREA_PRIVATO', @syscurrTipoFunz); 
END

if (not exists (select * from [@db_user].[DPA_FUNZIONI] where COD_FUNZIONE='DO_PROTO_PRIVATO_SEMPL'))
BEGIN
INSERT INTO [@db_user].[DPA_FUNZIONI] (COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES ('DO_PROTO_PRIVATO_SEMPL', 'DO_PROTO_PRIVATO_SEMPL', @syscurrTipoFunz); 
END

if (not exists (select * from [@db_user].[DPA_FUNZIONI] where COD_FUNZIONE='DO_CREA_PERSONALE'))
BEGIN
INSERT INTO [@db_user].[DPA_FUNZIONI] (COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES ('DO_CREA_PERSONALE', 'DO_CREA_PERSONALE', @syscurrTipoFunz); 
END


FETCH NEXT FROM currTipoFunz 
INTO @syscurrTipoFunz
END
CLOSE currTipoFunz
DEALLOCATE currTipoFunz
END
GO

if not exists (select * from dbo.sysobjects where id = object_id(N'[@db_user].[DPA_TIPO_FASC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE @db_user.DPA_TIPO_FASC(
SYSTEM_ID INT IDENTITY PRIMARY KEY, 
VAR_DESC_FASC VARCHAR(255), 
ID_AMM INT, 
ABILITATO_SI_NO INT, 
IN_ESERCIZIO VARCHAR(255), 
PATH_MOD_1 VARCHAR(255), 
EXT_MOD_1 VARCHAR(10), 
PATH_MOD_2 VARCHAR(255), 
EXT_MOD_2 VARCHAR(10), 
GG_SCADENZA INT, 
GG_PRE_SCADENZA INT
)
END
GO

if not exists (select * from dbo.sysobjects where id = object_id(N'[@db_user].[DPA_TIPO_OGGETTO_FASC]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE @db_user.DPA_TIPO_OGGETTO_FASC(
SYSTEM_ID INT IDENTITY PRIMARY KEY,
Tipo VARCHAR(255),
Descrizione VARCHAR(255)
)
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Campo di testo','CampoDiTesto')
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Casella di selezione','CasellaDiSelezione')
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Selezione esclusiva','SelezioneEsclusiva')
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Menu a tendina','MenuATendina')
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Contatore','Contatore')
INSERT INTO @db_user.DPA_TIPO_OGGETTO_FASC VALUES('Data','Data')
END
GO


if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_funzioni] where cod_funzione='GEST_DOC_CESTINO'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_funzioni] (cod_funzione, VAR_DESC_funzione) 
VALUES ('GEST_DOC_CESTINO', 'Abilita il sottomenù Rimuovi documento del menù gestione'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_funzioni] where cod_funzione='SVUOTA_CESTINO'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_funzioni] (cod_funzione, VAR_DESC_funzione) 
VALUES ('SVUOTA_CESTINO', 'Abilita alla rimozione fisica di tutti i documenti grigi/predisposti'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_funzioni] where cod_funzione='TODOLIST_RIMUOVIDOC'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_funzioni](cod_funzione, VAR_DESC_funzione) 
VALUES ('TODOLIST_RIMUOVIDOC', 'Abilita alla rimozione di un documento selezionandolo dalla todolist'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_LOG] where VAR_CODICE='CESTINA_DOC'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_LOG](var_codice, var_descrizione, var_oggetto, var_metodo)
VALUES ('CESTINA_DOC', 'Cestinato documento grigio/predisposto', 'DOCUMENTO', 'DOCUMENTOEXECCESTINA'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_LOG] where VAR_CODICE='RIATTIVA_DOC'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_LOG](var_codice, var_descrizione, var_oggetto, var_metodo)
VALUES ('RIATTIVA_DOC', 'Riattivato documento grigio/predisposto', 'DOCUMENTO', 'DOCUMENTORIATTIVADOC'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_LOG] where VAR_CODICE='SVUOTA_CESTINO'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_LOG](var_codice, var_descrizione, var_oggetto, var_metodo)
VALUES ('SVUOTA_CESTINO', 'Eliminati tutti i documenti dal cestino', 'DOCUMENTO', 'SVUOTACESTINO'); 
END
GO

if (not exists (select * from [@db_user].[DPA_ANAGRAFICA_LOG] where VAR_CODICE='ELIMINA_DOC'))
BEGIN
INSERT INTO [@db_user].[DPA_ANAGRAFICA_LOG](var_codice, var_descrizione, var_oggetto, var_metodo)
VALUES ('ELIMINA_DOC', 'Eliminato un documento dal cestino', 'DOCUMENTO', 'ELIMINADOC'); 
END
GO

if not exists(select * from syscolumns where name='CHA_IN_ADL' and id in (select id from sysobjects where name='DPA_SALVA_RICERCHE' and xtype='U'))
BEGIN
ALTER TABLE @db_user.DPA_SALVA_RICERCHE ADD CHA_IN_ADL varchar(1) NOT NULL  DEFAULT 0
END
GO

