<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.12</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Graph" Version="5.56.0" />
    <PackageReference Include="MimeKit" Version="4.7.1">
      <!--<PackageReference Include="MimeKit" Version="4.7.1" PrivateAssets="all" >-->
      <!--<ExcludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</ExcludeAssets>-->
    </PackageReference>
    <PackageReference Include="RestSharp" Version="112.0.0" />
    <ProjectReference Include="..\..\..\core\pi3.core\Pi3.Core\Pi3.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Services\Email\BoxScanner\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\BoxScanner\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\Sender\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\Sender\UrlResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UrlResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Services\Email\BoxScanner\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\BoxScanner\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\Sender\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\Sender\UrlResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>UrlResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>