-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 06/03/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
-- GETTIPORUOLO
-- =============================================

CREATE FUNCTION [DOCSADM].[GETTIPORUOLO]
(
	@IDGRUPPO	INT
)
RETURNS VARCHAR(256)
AS 
BEGIN 
	DECLARE @RISULTATO	INT
	
	SELECT @RISULTATO = F.VAR_DESC_RUOLO
	FROM DOCSADM.DPA_CORR_GLOBALI D
		, DOCSADM.DPA_TIPO_RUOLO F
	WHERE D.ID_GRUPPO = @IDGRUPPO
		AND F.SYSTEM_ID = D.ID_TIPO_RUOLO
		
	RETURN @RISULTATO

END

