-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 08/03/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
-- SET_MEZZO_INTEROP_FOR_RC:
-- importando il corrispondente da RC il mezzo di spedizione deve essere MAIL se sono settati solo i campo email.
-- oppure INTEROPERABILITA se sono settati i campi VAR_COD_AOO, COM_AMM E EMAIL oppure LETTERE se nessuno dei campi è settato.
-- =============================================

CREATE PROCEDURE [DOCSADM].[SET_MEZZO_INTEROP_FOR_RC]
AS
BEGIN
	DECLARE @INTEROP			INT
	DECLARE @MAIL				INT
	DECLARE @LETTERA			INT
	
	DECLARE @SYSTEM_ID			INT
	DECLARE @VAR_CODICE_AMM		VARCHAR(32)
	DECLARE @VAR_CODICE_AOO		VARCHAR(16)
	DECLARE @VAR_EMAIL			VARCHAR(128)
	
	DECLARE C CURSOR FOR
	SELECT SYSTEM_ID, VAR_CODICE_AMM, VAR_CODICE_AOO, VAR_EMAIL
	FROM DOCSADM.DPA_CORR_GLOBALI
	WHERE CHA_TIPO_CORR IN ('C','S')
		AND CHA_TIPO_IE = 'E'
	ORDER BY SYSTEM_ID
	
	OPEN C
	
	FETCH NEXT FROM C
	INTO @SYSTEM_ID,@VAR_CODICE_AMM,@VAR_CODICE_AOO,@VAR_EMAIL
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN 
		SELECT @INTEROP = SYSTEM_ID 
		FROM DOCSADM.DOCUMENTTYPES
		WHERE DESCRIPTION = 'INTEROPERABILITA'
		
		SELECT @LETTERA = SYSTEM_ID 
		FROM DOCSADM.DOCUMENTTYPES
		WHERE DESCRIPTION = 'LETTERA'
		
		SELECT @MAIL = SYSTEM_ID 
		FROM DOCSADM.DOCUMENTTYPES
		WHERE DESCRIPTION = 'MAIL'
		
		IF(@VAR_EMAIL IS NOT NULL)
		BEGIN
			IF(@VAR_CODICE_AOO IS NOT NULL)
			BEGIN
				IF(@VAR_CODICE_AMM IS NOT NULL)
				BEGIN
					-- CASO INTEROP
					DELETE
					FROM DOCSADM.DPA_T_CANALE_CORR
					WHERE ID_CORR_GLOBALE = @SYSTEM_ID
					
					INSERT INTO DOCSADM.DPA_T_CANALE_CORR
					(
						ID_CORR_GLOBALE
						,ID_DOCUMENTTYPE
						,CHA_PREFERITO
					)
					VALUES
					(
						@SYSTEM_ID
                      , @INTEROP
                      ,'1'
					)
				END
				ELSE		--@VAR_EMAIL NOT NULL, @VAR_CODICE_AOO NOT NULL MA @VAR_CODICE_AMM NULL, QUINDI  MAIL
				BEGIN
					DELETE
					FROM DOCSADM.DPA_T_CANALE_CORR
					WHERE ID_CORR_GLOBALE = @SYSTEM_ID
					
					INSERT INTO DOCSADM.DPA_T_CANALE_CORR
					(
						ID_CORR_GLOBALE
						,ID_DOCUMENTTYPE
						,CHA_PREFERITO
					)
					VALUES
					(
						@SYSTEM_ID
                      , @MAIL
                      ,'1'
					)
				END
			END
			ELSE		--@VAR_EMAIL NOT NULL MA @VAR_CODICE_AOO NULL QUINDI  MAIL
			BEGIN
				DELETE
				FROM DOCSADM.DPA_T_CANALE_CORR
				WHERE ID_CORR_GLOBALE = @SYSTEM_ID
					
				INSERT INTO DOCSADM.DPA_T_CANALE_CORR
				(
					ID_CORR_GLOBALE
					,ID_DOCUMENTTYPE
					,CHA_PREFERITO
				)
				VALUES
				(
					@SYSTEM_ID
                    , @MAIL
                    ,'1'
				)
			END
		END
		ELSE		--@VAR_EMAIL NULL OR EMPTY SICURAMENTE LETTERA
		BEGIN
			DELETE
			FROM DOCSADM.DPA_T_CANALE_CORR
			WHERE ID_CORR_GLOBALE = @SYSTEM_ID
				
			INSERT INTO DOCSADM.DPA_T_CANALE_CORR
			(
				ID_CORR_GLOBALE
				,ID_DOCUMENTTYPE
				,CHA_PREFERITO
			)
			VALUES
			(
				@SYSTEM_ID
                , @LETTERA
                ,'1'
			)
		END
	END
	
	CLOSE C
	DEALLOCATE C
END
 