ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA  
MODIFY (CHA_TIPO_VISIBILITA CHAR(2 BYTE) );

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA 
ADD (CHA_NOTIFICA_CONCLUSO CHAR(1) DEFAULT 0 );

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA 
ADD (CHA_NOTIFICA_INTERROTTO CHAR(1) DEFAULT 0 );

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA 
ADD (CHA_NOTIFICA_ERRORE CHAR(1) DEFAULT 1 );

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA 
ADD (DTA_INIZIO DATE);

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA 
ADD (DTA_FINE DATE);

ALTER TABLE DPA_ANAGRAFICA_EVENTI 
ADD (CHA_IGNORA_ORDINE CHAR(1) DEFAULT 0 );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (CHA_FACOLTATIVO CHAR(1) DEFAULT 0 );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (ID_TIPOLOGIA NUMBER );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (ID_STATO_DIAGRAMMA NUMBER );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (ID_TIPOLOGIA NUMBER );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (ID_STATO_DIAGRAMMA NUMBER );

ALTER TABLE DPA_SCHEMA_PROCESSO_FIRMA
ADD (ID_STATO_INTERRUZIONE NUMBER);

ALTER TABLE DPA_ISTANZA_PROCESSO_FIRMA 
ADD (ID_STATO_INTERRUZIONE NUMBER);

ALTER TABLE DPA_TRASM_UTENTE 
ADD (CHA_RIMOZIONE_DELEGATO CHAR(1));

ALTER TABLE PEOPLE 
ADD (CHA_DI_SISTEMA CHAR(1) DEFAULT 0 );