CREATE TABLE DPA_VERSAMENTO
(
SYSTEM_ID    int NOT NULL,
ID_PROFILE    int,
ID_PEOPLE    int,
ID_RUOLO    int,
ID_AMM        int,
CHA_STATO    VARCHAR(2),
DTA_INVIO    DATE,
VAR_FILE_RISPOSTA    NVARCHAR(max),
CHA_WARNING    VARCHAR(1),
VAR_FILE_METADATI    NVARCHAR(max)
);
