// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: EUPL-1.2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.DocumentoAmministrativo.WebApi.Application.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.DocumentoAmministrativo.WebApi.Application.Exceptions.ErrorDescriptions", typeof(ErrorDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice modello {0} non è per un documento amministrativo.
        /// </summary>
        internal static string CodiceModelloNonDocumento {
            get {
                return ResourceManager.GetString("CodiceModelloNonDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il codice modello {0} non è nel formato riochiesto.
        /// </summary>
        internal static string CodiceModelloNonValido {
            get {
                return ResourceManager.GetString("CodiceModelloNonValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codice modello {0} non trovato..
        /// </summary>
        internal static string CodiceModelloNotFound {
            get {
                return ResourceManager.GetString("CodiceModelloNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentBlob non trovato..
        /// </summary>
        internal static string DocumentBlobNotFound {
            get {
                return ResourceManager.GetString("DocumentBlobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento amministrativo non trovato..
        /// </summary>
        internal static string DocumentoAmministrativoNotFound {
            get {
                return ResourceManager.GetString("DocumentoAmministrativoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File già acquisito per il documento amministrativo..
        /// </summary>
        internal static string FileGiaAcquisito {
            get {
                return ResourceManager.GetString("FileGiaAcquisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun file acquisito per il documento amministrativo..
        /// </summary>
        internal static string FileNonAcquisito {
            get {
                return ResourceManager.GetString("FileNonAcquisito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppo {0} non trovato.
        /// </summary>
        internal static string GruppoNotFound {
            get {
                return ResourceManager.GetString("GruppoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Documento non valido.
        /// </summary>
        internal static string IdDocumentoAmministrativoNonValido {
            get {
                return ResourceManager.GetString("IdDocumentoAmministrativoNonValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione Aggregato non valido.
        /// </summary>
        internal static string InvalidAggregationDescription {
            get {
                return ResourceManager.GetString("InvalidAggregationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista link non trovata nelle risorse.
        /// </summary>
        internal static string LinksListNotFound {
            get {
                return ResourceManager.GetString("LinksListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OggettoCustom {0] non trovato.
        /// </summary>
        internal static string OggettoCustomNotFound {
            get {
                return ResourceManager.GetString("OggettoCustomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallito il lookup basato sul nome della classificazione &apos;{0}&apos; e Tipologia Fascicolo &apos;{1)&apos;.
        /// </summary>
        internal static string PianoConservazioneLookupFailed {
            get {
                return ResourceManager.GetString("PianoConservazioneLookupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro con codice {0} non trovato.
        /// </summary>
        internal static string RegistroNotFound {
            get {
                return ResourceManager.GetString("RegistroNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Campo {0} non trovato, controllare i dati immessi.
        /// </summary>
        internal static string TipoCampoNotFound {
            get {
                return ResourceManager.GetString("TipoCampoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Fascicolo {0] non trovato.
        /// </summary>
        internal static string TipoFascicoloNotFound {
            get {
                return ResourceManager.GetString("TipoFascicoloNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titolario non trovato.
        /// </summary>
        internal static string TitolarioNotFound {
            get {
                return ResourceManager.GetString("TitolarioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasmissione non trovata.
        /// </summary>
        internal static string TrasmissioneNotFound {
            get {
                return ResourceManager.GetString("TrasmissioneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadId non trovato..
        /// </summary>
        internal static string UploadIdNotFound {
            get {
                return ResourceManager.GetString("UploadIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nella trasmissione sono stati definiti sia utenti che gruppi.
        /// </summary>
        internal static string UsersAndGroupsDefined {
            get {
                return ResourceManager.GetString("UsersAndGroupsDefined", resourceCulture);
            }
        }
    }
}
