CREATE TABLE DPA_UPLOAD_FILE
   (	ID_PEOPLE INT NOT NULL, 
	FILE_HASH NVARCHAR(1000) NOT NULL, 
	SENDER_NAME NVARCHAR(100), 
	SENDER_PATH NVARCHAR(2000), 
	FILE_NAME NVARCHAR(500), 
	FILE_SIZE INT, 
	FILE_PART INT, 
	TOTAL_PART INT, 
	START_DATE DATE, 
	END_DATE DATE, 
	FILE_PATH NVARCHAR(2000), 
	NUM_ORDER INT, 
	ID_RUOLO INT, 
	FILE_DESCRIPTION NVARCHAR(150),
	UNICSTR NVARCHAR(2000)
   );