SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


CREATE VIEW   @db_user.RDE_Registro
AS
SELECT     SYSTEM_ID AS IdRegistroRemoto, VAR_DESC_REGISTRO AS Descrizione, VAR_CODICE AS Codice
FROM         @db_user.DPA_EL_REGISTRI

GO


SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO