
UPDATE DPA_PROCESSO_FIRMA_VISIBILITA
SET CHA_NOTIFICA_CONCLUSO = '1', CHA_NOTIFICA_INTERROTTO = '1'
WHERE CHA_TIPO_VISIBILITA = 'M';

UPDATE DPA_ANAGRAFICA_EVENTI
SET CHA_IGNORA_ORDINE = '1'
WHERE VAR_COD_AZIONE IN ('DOC_VERIFIED', 'DOC_STEP_OVER');

UPDATE DPA_PROCESSO_FIRMA_VISIBILITA V
SET DTA_INIZIO = TO_DATE('01/01/2000 00:00:00','dd/mm/yyyy  HH24:mi:ss' );

-- INSERIMENTO EVENTI DI LIBRO FIRMA
INSERT INTO DPA_ANAGRAFICA_EVENTI (ID_EVENTO, VAR_COD_AZIONE, DESCRIZIONE, CHA_TIPO_EVENTO, Gruppo, CHA_IGNORA_ORDINE, CHA_AUTOMATICO) 
VALUES ((select MAX(ID_EVENTO) FROM DPA_ANAGRAFICA_EVENTI) + 1,'DOC_CAMBIO_STATO','Cambio stato del documento','E','EVENT', '1', '1');

-- INSERIMENTO RAGIONE TRASMISSIONE 
INSERT INTO DPA_RAGIONE_TRASM (SYSTEM_ID, VAR_DESC_RAGIONE, CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA, CHA_TIPO_RISPOSTA, ID_AMM, VAR_NOTIFICA_TRASM, VAR_TESTO_MSG_NOTIFICA_DOC, CHA_CEDE_DIRITTI, CHA_MANTIENI_LETT, CHA_MANTIENI_SCRITT, CHA_RAG_SISTEMA, CHA_PROC_RES )
(SELECT SEQ.NEXTVAL, 'NOTIFICA_DOCUMENTO_NON_CONFORME', 'N', '0','W', 'T',	'0', 'Ragione di trasmissione per notificare un documento contenente file non conforme', '0', 'C',	a.system_id, 'ED',
'Si trasmette il documento SEGN_ID_DOC 
oggetto: OGG_DOC
con ragione: RAG_TRASM
',
'N', 0,	0,	1, 'NON_CONFORME'
  FROM dpa_amministra a
  WHERE NOT EXISTS (SELECT 'X' FROM DPA_RAGIONE_TRASM WHERE VAR_DESC_RAGIONE = 'NOTIFICA_DOCUMENTO_NON_CONFORME' AND ID_AMM = A.SYSTEM_ID)
);

INSERT INTO DPA_RAGIONE_TRASM (SYSTEM_ID, VAR_DESC_RAGIONE, CHA_TIPO_RAGIONE, CHA_VIS, CHA_TIPO_DIRITTI, CHA_TIPO_DEST, CHA_RISPOSTA, VAR_NOTE, CHA_EREDITA, CHA_TIPO_RISPOSTA, ID_AMM, VAR_NOTIFICA_TRASM, VAR_TESTO_MSG_NOTIFICA_DOC, CHA_CEDE_DIRITTI, CHA_MANTIENI_LETT, CHA_MANTIENI_SCRITT, CHA_RAG_SISTEMA, CHA_PROC_RES )
VALUES (SEQ.NEXTVAL, 'NOTIFICA_DOCUMENTO_NON_CONFORME', 'N', '0','W', 'T',	'0', 'Ragione di trasmissione per notificare un documento contenente file non conforme', '0', 'C',	null, 'ED',
'Si trasmette il documento SEGN_ID_DOC 
oggetto: OGG_DOC
con ragione: RAG_TRASM
',
'N', 0,	0,	1, 'NON_CONFORME'
);