UPDATE DPA_EL_REGISTRI
SET VAR_BOX_MAIL_ELABORATE = 'INBOX/' || VAR_BOX_MAIL_ELABORATE,
VAR_MAIL_NON_ELABORATE = 'INBOX/' || VAR_MAIL_NON_ELABORATE
WHERE UPPER(VAR_TIPO_CONNESSIONE) = 'IMAP';

COMMIT;


UPDATE DPA_MAIL_REGISTRI
SET VAR_BOX_MAIL_ELABORATE = 'INBOX/' || VAR_BOX_MAIL_ELABORATE,
VAR_MAIL_NON_ELABORATE = 'INBOX/' || VAR_MAIL_NON_ELABORATE
WHERE UPPER(VAR_TIPO_CONNESSIONE) = 'IMAP';

COMMIT;