//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using LcEmulatorServices;

namespace LcEmulatorServices.Interfaces
{
    // 
    // This source code was auto-generated by wsdl, Version=4.0.30319.1.
    // 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GeneratePdfServiceSoapBinding", Namespace = "http://adobe.com/idp/services")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExportPDFResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatePDFResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HtmlToPdfResult))]
    public interface IGeneratePdfServiceSoapBinding
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CreatePDF", RequestNamespace = "http://adobe.com/idp/services", ResponseNamespace = "http://adobe.com/idp/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace = "http://xml.apache.org/xml-soap", IsNullable = false)]
        mapItem[] CreatePDF(BLOB inputDocument, string fileName, string fileTypeSettings, string pdfSettings, string securitySettings, BLOB settingsDocument, BLOB xmpDocument);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HtmlToPDF", RequestNamespace = "http://adobe.com/idp/services", ResponseNamespace = "http://adobe.com/idp/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace = "http://xml.apache.org/xml-soap", IsNullable = false)]
        mapItem[] HtmlToPDF(string inputURL, string fileTypeSettings, string securitySettings, BLOB settingsDocument, BLOB xmpDocument);

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ExportPDF", RequestNamespace = "http://adobe.com/idp/services", ResponseNamespace = "http://adobe.com/idp/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace = "http://xml.apache.org/xml-soap", IsNullable = false)]
        mapItem[] ExportPDF(BLOB inputDocument, string fileName, string formatType, BLOB settingsDocument);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://adobe.com/idp/services")]
    public partial class ExportPDFResult
    {

        private BLOB convertedDocumentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BLOB convertedDocument
        {
            get
            {
                return this.convertedDocumentField;
            }
            set
            {
                this.convertedDocumentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://adobe.com/idp/services")]
    public partial class CreatePDFResult
    {

        private BLOB createdDocumentField;

        private BLOB logDocumentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BLOB createdDocument
        {
            get
            {
                return this.createdDocumentField;
            }
            set
            {
                this.createdDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BLOB logDocument
        {
            get
            {
                return this.logDocumentField;
            }
            set
            {
                this.logDocumentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://adobe.com/idp/services")]
    public partial class HtmlToPdfResult
    {

        private BLOB createdDocumentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BLOB createdDocument
        {
            get
            {
                return this.createdDocumentField;
            }
            set
            {
                this.createdDocumentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.apache.org/xml-soap")]
    public partial class mapItem
    {

        private object keyField;

        private object valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public object key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public object value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}