create or replace FUNCTION EsisteDestinatarioMaiSpedito (p_idProfile INT )
   RETURN INT IS  retValue   INT;
BEGIN
	BEGIN		
		SELECT CASE 
		   WHEN EXISTS(SELECT 'X'
					FROM DPA_DOC_ARRIVO_PAR D 
					JOIN DPA_CORR_GLOBALI G ON D.ID_MITT_DEST = G.SYSTEM_ID
					JOIN DOCUMENTTYPES T ON T.SYSTEM_ID = D.ID_DOCUMENTTYPES
					WHERE D.ID_PROFILE = p_idProfile AND D.CHA_TIPO_MITT_DEST IN ('D', 'C', 'F')
					AND G.CHA_TIPO_IE = 'E' AND T.CHA_TIPO_CANALE IN ('I', 'M', 'S') 
					AND NOT EXISTS (
					SELECT 'X'
					FROM DPA_SEND_STO S
					WHERE S.ID_PROFILE = D.ID_PROFILE AND S.ID_CORR_GLOBALE = G.SYSTEM_ID AND S.ID_DOCUMENTTYPE = T.SYSTEM_ID )
					AND ROWNUM = 1)
		   THEN 1
		   ELSE 0
		END INTO retValue
		FROM DUAL;
	END;	
	RETURN retValue;
END; 