<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>39992838-ddfa-4074-b3b4-5133b3ff1fd3</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.30.1" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.7.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="9.0.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.aac\Pi3.Infrastructure.AAC\Pi3.Infrastructure.AAC.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\DomainEventHandlers\" />
    <Folder Include="Application\Exceptions\" />
    <Folder Include="Application\Queries\Corrispondenti\SearchIpa\Models\Request\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pi3.App.RubricaComune.Infrastructure.EF.Oracle\Pi3.App.RubricaComune.Infrastructure.EF.Oracle.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Application\Commands\Corrispondenti\Create\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Application\Queries\Corrispondenti\GetById\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Application\Queries\Corrispondenti\GetEmails\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Application\Queries\Corrispondenti\SearchIpa\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Application\Commands\Corrispondenti\Create\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Application\Queries\Corrispondenti\GetById\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Application\Queries\Corrispondenti\GetEmails\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Application\Queries\Corrispondenti\SearchIpa\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Pi3.App.RubricaComune.WebApi.Tests" />
  </ItemGroup>
</Project>