CREATE TABLE DPA_UPLOAD_FILE
   (	ID_PEOPLE NUMBER NOT NULL ENABLE, 
	FILE_HASH VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	SENDER_NAME VARCHAR2(100 BYTE), 
	SENDER_PATH VARCHAR2(2000 BYTE), 
	FILE_NAME VARCHAR2(500 BYTE), 
	FILE_SIZE NUMBER, 
	FILE_PART NUMBER, 
	TOTAL_PART NUMBER, 
	START_DATE DATE, 
	END_DATE DATE, 
	FILE_PATH VARCHAR2(2000 BYTE), 
	NUM_ORDER NUMBER, 
	ID_RUOLO NUMBER, 
	FILE_DESCRIPTION VARCHAR2(150 BYTE), 
	UNICSTR VARCHAR2(2000 BYTE)
   );