-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 05/03/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
-- =============================================


DECLARE @db_user	VARCHAR(1024)
SET @db_user = 'DOCSADM'


-- INSERIMENTO NELLA PEOPLE DI UNA NUOVA COLONNA CHA_TIPO_COMPONENTI 

DECLARE @COUNT INT

SET @COUNT = (SELECT COUNT(*) FROM SYS.columns WHERE name = 'CHA_TIPO_COMPONENTI' AND OBJECT_ID = (SELECT OBJECT_ID FROM SYS.tables WHERE name = 'PEOPLE'))

IF (@COUNT = 0)
BEGIN 
             
	EXECUTE DOCSADM.utl_add_column '3.25',@db_user,'PEOPLE','CHA_TIPO_COMPONENTI','CHAR(1)','0 NOT NULL',NULL,NULL,NULL
	
END


UPDATE DOCSADM.PEOPLE SET CHA_TIPO_COMPONENTI = ISNULL(IS_ENABLED_SMART_CLIENT,'0') WHERE ISNULL(IS_ENABLED_SMART_CLIENT,'0') != '0'

	
EXECUTE DOCSADM.utl_add_foreign_key '3.25',@db_user,'TIPO_COMPONENTI','CHA_TIPO_COMPONENTI','PEOPLE','CHA_TIPO_COMPONENTI',NULL,NULL

