--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Desktop\Function_ITCOLL\ANNUALEDOCTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ATLEASTONECARTACEO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ATLEASTONEFIRMATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKGESTIONEARCHIVIO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKSECURITY.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKSECURITYDOCUMENTO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKSECURITYPROPRIETARIO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKSECURITYUO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CHECKVISIBILITAARCHIVIO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CLASSCAT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CODFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CODRFAPPARTENZA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CODRFAPPARTENZARUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CODRFAPPARTENZARUOLOCORRGLOB.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CORRCAT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CORRCAT_ADDRESS.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\CORRCATBYTIPO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\COUNTALLEGATI_BY_DOCNUMBER.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DESCUO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DEST_IN_LISTA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DEST_IN_RF.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCCLASSCOMPTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCCLASSCOMPTABLEFUNCTION_NEW.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCCLASSTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCCLASSTABLEFUNCTION_NEW.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCSEDETABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DOCUOTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DPA_GETMAXDTAINVIOFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\DPA_VALORE_OGGETTO_TIPO_ATTO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ESISTENOTAVISIBILE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FASCICOLITABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FASCICOLIVTETABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FASCICOLIVTTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FULLTEXT_ONVAR_DESC_CORR.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FULLTEXT_ONVAR_PROF_OGG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FULLTEXT_ONVAR_PROF_OGGETTO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FULLTEXT_ONVAR_PROF_OGGETTO_1.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\FULLTEXT_ONVAR_PROF_OGG_NEW.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GENUMDOCINFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GENUMDOCINFASC2.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GENUMDOCPROTINFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GENUMDOCPROTINFASCRF.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETACCESSRIGHTS.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCHACARTACEO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCHACONSENTICLASS.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCHAFIRMATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCHAIMCONVPDF.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCHAIMG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODAMM.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODFIS.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODREG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODREGCORCAT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUBRICACORR.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUBRICAIDPAREMT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUBRICARUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUOLOBYIDCORR.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODRUOLORIF.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODTIPOFUNZ.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODTIPORUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODTIT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCODUO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCONTATOREDOC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCONTATOREDOCIDOBJ.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCONTATOREDOCORDINAMENTO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCONTATOREFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCONTATOREFASCCONTATORE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCORRDESCRIPTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETCOUNTNOTE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDATAARRIVODOC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDATEONLY.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDESCCORR.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDESCRUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDESCTIPODOC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDESCTIPOFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDESCTITOLARIO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDIAGRAMMISTATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDOCFASCICOLATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDOCNAMEORCODFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDOCPRINCIPALE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETDTAINVIO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETESITOPUBBLICAZIONE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETFASCPRIMARIA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETFLAGNOTIFICA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETFOLDERGEN.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETFUNCTCORCAT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETGIACENZADDTODOLIST.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIDAMM.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIDRUOLORIF.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIFMODELLOAUTORIZZATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIFMODELLOAUTORIZZATO_OLD.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIMG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETIMPRONTA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETINADL.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETINCONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETINCONSERVAZIONENOSEC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETLONG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETMAXVER.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETMAXVER_MENO1.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETNOMERUOLOBYSYSID.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETNOTEOLD.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETNUMLIVRUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETNUMMITTENTIMODELLITRASM.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETNUMPROTOSTAMPA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETPEOPLENAME.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETPEOPLENAMEBYUSERID.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETPEOPLEUSERID.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETPROTOCOLLATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETREGDESCR.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETREGISTROSTAMPA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETROLETYPEDESCRIPTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSEDOCFASCICOLATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSEDOCTRASMCONRAG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSEMITTDEST.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSEOGGATTIVO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSERIMUOVIBILE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSESOLOMITTDESTOCC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETSTATODELEGA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETTESTOULTIMANOTA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETTIPORUOLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETTRANSREASONDESC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETUO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETUTENTICORCAT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETVALCAMPOPROFDOC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETVALCAMPOPROFDOCORDER.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETVALPROFOBJPRJ.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETVALPROFOBJPRJORDER.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\GETVISIBILITA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\HAS_CHILDREN.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\HASVERSIONSFULLVISIBILITY.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\INTEROPTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISALLEGATO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISCORRISPONDENTEINTERNO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISNONPROT.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISPREDISPOSTO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISPROTOCOLLO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISPROTOCOLLOARRIVO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISPROTOCOLLOINTERNO.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISPROTOCOLLOPARTENZA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISSTAMPAREG.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISVALIDMODELLOTRASMISSIONE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\ISVERSIONVISIBLE.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\MENSILEDOCTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\MENSILEFASCICOLITABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\NOALLEGATI.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\OGG_SEARCH.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\POP.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\POPDPAASSRUOLOOGGCUSTOMFASC.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\POPOLATEDPAASSRUOLOOGGCUSTOM.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\TEMPIMEDICOMPATTATABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\TEMPIMEDITABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\TMP_GET_ELAPSED.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\UTENTEHASQUALIFICA.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\UTL_ISVALORE_LT_COLUMN.sql
@C:\Users\Francesco\Desktop\Function_ITCOLL\VARDESCRIBE.sql
