// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: EUPL-1.2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.Legacy.Mobile.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.Legacy.Mobile.WebApi.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAB9AAAAJYCAYAAAA6431rAAABGXpUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjalVJRksMgCP33FHsEBAQ9jq06szfo8YsGt0m+usyILw9BfCT01+8IP9OIOXDSLEUEzLhwwWogw2GP5SPw8ssagDp74UPKgAuhUWQ7HYGCXqwbb5g8ofglcZ/fhTaI1VD6BJ7V+ceVb34B5nshD1A8bp69rwQvRHjwkb1B70hK1svTxhOulj8rAXdWBCEZ0lUkKSpLEkZQlWI4WzQrKwcFJao4cNixKjqFx75SGw47ngQVsFnSMA/SZYnNeyC7ozthxQu3ZK8hxE6RwDxRPp5JcyWqtkfz9o0TKdVA06p9xDU5sH8B54Apn4bg4Czu3w5b7Jv9R5ezLOFbXcIbtxuUgIxG7ggAAAF8aUNDUGljYwAAeJx9kT1Iw1AUhU9TRZGKggFFHDJUJ7uoiGOpYhEslLZCqw4mL/2DJg1Jiouj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trasparenteB64RemotePdfStamp {
            get {
                return ResourceManager.GetString("trasparenteB64RemotePdfStamp", resourceCulture);
            }
        }
    }
}
