using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace StampaRegistri.DocsPaWR25
{
	[GeneratedCode("System.Xml", "2.0.50727.42"), XmlType(Namespace = "http://localhost")]
	[Serializable]
	public enum FiltriDocumento
	{
		TIPO,
		REGISTRO,
		OGGETTO,
		ID_OGGETTO,
		MITT_DEST,
		ID_MITT_DEST,
		VIS_STORICO_MITT_DEST,
		NUM_PROTOCOLLO,
		NUM_PROTOCOLLO_DAL,
		NUM_PROTOCOLLO_AL,
		DATA_PROT_IL,
		DATA_PROT_SUCCESSIVA_AL,
		DATA_PROT_PRECEDENTE_IL,
		TIPO_DOCUMENTO,
		MITTENTE_INTERMEDIO,
		ID_MITTENTE_INTERMEDIO,
		DATA_PROT_MITTENTE_IL,
		DATA_PROT_MITTENTE_SUCCESSIVA_AL,
		DATA_PROT_MITTENTE_PRECEDENTE_IL,
		DATA_ARRIVO_IL,
		DATA_ARRIVO_SUCCESSIVA_AL,
		DATA_ARRIVO_PRECEDENTE_IL,
		PROTOCOLLO_MITTENTE,
		DA_PROTOCOLLARE,
		MANCANZA_IMMAGINE,
		MANCANZA_ASSEGNAZIONE,
		MANCANZA_FASCICOLAZIONE,
		DATA_CREAZIONE_IL,
		DATA_CREAZIONE_SUCCESSIVA_AL,
		DATA_CREAZIONE_PRECEDENTE_IL,
		PAROLE_CHIAVE,
		DOCNUMBER,
		DOCNUMBER_DAL,
		DOCNUMBER_AL,
		TIPO_ATTO,
		FIRMATARIO_NOME,
		FIRMATARIO_COGNOME,
		NUM_PROTO_EMERGENZA,
		DATA_PROTO_EMERGENZA_IL,
		SEGNATURA,
		ID_CATEGORIA_ATTO,
		NUM_PROG_CATEGORIA_ATTO,
		NUM_PROG_CATEGORIA_ATTO_DAL,
		NUM_PROG_CATEGORIA_ATTO_AL,
		NUM_OGGETTO,
		COMMISSIONE_REF,
		ANNO_PROTOCOLLO,
		NOTE,
		ANNULLATO,
		EVIDENZA,
		VISUALIZZA_TOP_N_DOCUMENTI
	}
}
