CREATE TABLE DPA_CLASSIFICAZIONE_TIPI_DOC
(
  ID_AMM           		 NUMBER      NOT NULL,
  TIPO_DOC     	 		 VARCHAR(100 BYTE)      NOT NULL,
  CHA_FASC_OBBLIGATORIA  CHAR(1)     DEFAULT 0  NOT NULL
);
