BEGIN

	EXECUTE IMMEDIATE 'ALTER TABLE
	DPA_TIPO_ATTO
	ADD (CHA_INVIO_CONSERVAZIONE varchar2(1))';

	EXECUTE IMMEDIATE 'ALTER TABLE
	DPA_OGGETTI_CUSTOM
	ADD (CHA_CONSOLIDAMENTO varchar2(1))';

	EXECUTE IMMEDIATE 'ALTER TABLE
	DPA_OGGETTI_CUSTOM
	ADD (CHA_CONSERVAZIONE varchar2(1))';
	
	EXECUTE IMMEDIATE 'ALTER TABLE
	DPA_OGGETTI_CUSTOM
	ADD (CHA_CONS_REPERTORIO varchar2(1))';
	
	COMMIT;

END;