CREATE TABLE INST_ACC
(
  SYSTEM_ID  NUMBER(10, 0) NOT NULL ,
  DESCRIPTION VARCHAR2(2000 CHAR) NOT NULL,
  DTA_CREAZIONE DATE NOT NULL ,
  DTA_CHIUSURA  DATE ,
  ID_PEOPLE_PROPRIETARIO NUMBER(10, 0) NOT NULL ,
  ID_GRUPPO_PROPRIETARIO NUMBER(10, 0) NOT NULL,
  ID_RICHIEDENTE NUMBER(10, 0),
  DTA_RICHIESTA DATE ,
  ID_DOCUMENTO_RICHIESTO NUMBER(10, 0),
  NOTE VARCHAR2(2000 CHAR) ,
  CHA_STATO_DOWNLOAD_INOLTRO CHAR(1 CHAR) DEFAULT '0' ,
  ID_PROFILE_DOWNLOAD NUMBER(10, 0) DEFAULT 0
);


CREATE TABLE INST_ACC_DOC
(
  SYSTEM_ID NUMBER(10, 0) NOT NULL ,
  ID_INST_ACC NUMBER(10, 0) NOT NULL,
  DOCNUMBER NUMBER(10, 0) ,
  ID_PROJECT NUMBER(10, 0) ,
  ID_PARENT NUMBER(10, 0) ,			
  TIPO_RICHIESTA VARCHAR2(256 CHAR),
  ENABLE CHAR(2 BYTE)			
);


CREATE TABLE INST_ACC_ATT
(
  SYSTEM_ID  NUMBER(10, 0),
  ID_INST_ACC_DOC NUMBER(10, 0) NOT NULL ,
  ID_ATTACH NUMBER(10, 0) NOT NULL ,
  ENABLE CHAR(2 BYTE)
);


CREATE SEQUENCE SEQ_INST_ACC START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ;

CREATE SEQUENCE SEQ_INST_ACC_DOC START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ;

CREATE SEQUENCE SEQ_INST_ACC_ATT START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 ;

ALTER TABLE DPA_TIPO_ATTO ADD (IS_TYPE_INSTANCE  CHAR(1 CHAR) DEFAULT 0 );



 INSERT
  INTO DPA_ANAGRAFICA_LOG VALUES
    (
      seq.nextval,
      'CREATED_FILE_ZIP_INSTANCE_ACCESS',
      'Creazione del file zip contentente documenti dell''istanza di accesso',
      'DOCUMENTO',
      'CREATED_FILE_ZIP_INSTANCE_ACCESS',
      'ONE',
      NULL,
      '1',
      '1',
      'S_PRODUCER_EVENT',
      'BLUE'--,
      --0,
      --0
    );
	
	
 INSERT
  INTO DPA_ANAGRAFICA_LOG VALUES
    (
      seq.nextval,
      'FAILED_CREATING_FILE_ZIP_INSTANCE_ACCESS',
      'Fallita la creazione del file zip contentente documenti dell''istanza di accesso',
      'DOCUMENTO',
      'FAILED_CREATING_FILE_ZIP_INSTANCE_ACCESS',
      'ONE',
      NULL,
      '1',
      '1',
      'S_PRODUCER_EVENT',
      'RED'--,
      --0,
      --0
    );
--Aumenta la dimensione della colonna Comments perchè quando crea la dichiarazione di conformità
--con un documento il cui oggetto è superiore a 20, diventa allegato e schianta
ALTER TABLE VERSIONS MODIFY COMMENTS VARCHAR2(2000 CHAR);

COMMIT;