--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_AMMINISRAZIONI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_AMMINISTRAZIONI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_APPS.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DISPOSITIVI_STAMPA.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_A_R_OGG_CUSTOM_DOC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_A_R_OGG_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASS_DIAGRAMMI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASS_DOC_MAIL_INTEROP.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASS_INDX_SIS.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASSOCIAZIONE_TEMPLATES.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASSOCIAZIONE_VALORI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASS_TEMPLATES_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ASS_VALORI_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CHIAVI_CONFIG.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CHIAVI_CONFIG_TEMPLATE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CONS_VERIFICA.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CONTATORI_DOC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CONTATORI_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CONV_PDF_SERVER.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_CORR_ABILITATI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DATA_ARRIVO_STO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DETT_POLICY_ESECUZIONE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DIAGRAMMI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DIAGRAMMI_STATO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DIAGRAMMI_STO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_DISSERVIZI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_FRIEND_APPLICATION.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_GRIDS.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_INDX_SIS.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_ITEMS_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_LDAP_SYNC_HISTORY.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_LETTERE_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_LISTE_DISTR.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_MAIL_CORR_ESTERNI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_MAIL_REGISTRI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_MODELLI_MITT_DEST.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_MODELLI_TRASM.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_NOTIFICA.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_OGG_CUSTOM_COMP.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_OGG_CUSTOM_COMP_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_OGGETTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_OGGETTI_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_PASSI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_PEOPLEGROUPS_QUALIF.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_POLICY_ESECUZIONE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_PROFIL_FASC_STO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_PROFIL_STO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_PROTO_TIT.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_QUALIFICHE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_RISCONTRI_CLASSIFICA.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_SALVA_RICERCHE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_STAMPA_REPERTORI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_STATI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TEMPLATES.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TEMPLATES_COMPONENT.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIMESTAMP_DOC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIPO_ATTO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIPO_NOTIFICA.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIPO_OGGETTO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TIPO_OGGETTO_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_TRASM_DIAGR.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_VIS_MAIL_REGISTRI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_VIS_TIPO_DOC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_VIS_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_DPA_VOCI_MENU_ADMIN.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_ER.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_INSTALL_LOG.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_NOTIFICATIONCHANNEL.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_NOTIFICATIONINSTANCES.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_NOTIFICATIONITEM.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_NOTIFICATIONITEMCATEGORIES.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_PGU.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_POLICY_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_PUBBLICAZIONI_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_PUBLISHER.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQROLEHISTORY.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_SUBSCRIBER.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_SUPPORTO.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_UT.sql
@C:\Users\Francesco\Desktop\Sequenze_ITCOLL\SEQ_UTL_SYSTEM_LOG.sql
