// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: AGPL-3.0-or-later
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.Legacy.Pis.WebApi.Application.Commands.Documents.SpedisciDocumento {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.Legacy.Pis.WebApi.Application.Commands.Documents.SpedisciDocumento.ErrorD" +
                            "escriptions", typeof(ErrorDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canale preferenziale per il destinatario non di tipo MAIL o INTEROPERABILITA&apos;, impossibile spedire il documento.
        /// </summary>
        public static string CanalePreferenzialeNonSupportato {
            get {
                return ResourceManager.GetString("CanalePreferenzialeNonSupportato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile spedire il documento ad un destinatario non interoperante.
        /// </summary>
        public static string DestinatarioNonInteroperante {
            get {
                return ResourceManager.GetString("DestinatarioNonInteroperante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo  {0} ({1}) disabilitato alla ricezione di trasmissioni.
        /// </summary>
        public static string DestinatarioTrasmissioneDisabilitata {
            get {
                return ResourceManager.GetString("DestinatarioTrasmissioneDisabilitata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario de lla trasmissione  {0} ({1}) occasionale.
        /// </summary>
        public static string DestinatarioTrasmissioneOccasionale {
            get {
                return ResourceManager.GetString("DestinatarioTrasmissioneOccasionale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile procedere con la spedizione poichè è attivo un processo di firma per il documento con id {0}..
        /// </summary>
        public static string DocumentoInLibroFirmaPassoNonAtteso {
            get {
                return ResourceManager.GetString("DocumentoInLibroFirmaPassoNonAtteso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento con id {0} non protocollato in uscita.
        /// </summary>
        public static string DocumentoNonProtocollatoInUscita {
            get {
                return ResourceManager.GetString("DocumentoNonProtocollatoInUscita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento non salvato.
        /// </summary>
        public static string DocumentoNonSalvato {
            get {
                return ResourceManager.GetString("DocumentoNonSalvato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider non gestito.
        /// </summary>
        public static string ProviderNonGestito {
            get {
                return ResourceManager.GetString("ProviderNonGestito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spedizione non effettuata: è necessario selezionare un registro/rf prima di effettuare la spedizione.
        /// </summary>
        public static string RegistroNotFound {
            get {
                return ResourceManager.GetString("RegistroNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile effettuare la spedizione. E&apos; necessario selezionare il registro/rf del mittente.
        /// </summary>
        public static string RegistroRFMittenteNotFound {
            get {
                return ResourceManager.GetString("RegistroRFMittenteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manca un ruolo di riferimento per la UO: {0} ({1}).
        /// </summary>
        public static string RuoloRiferimentoNotFound {
            get {
                return ResourceManager.GetString("RuoloRiferimentoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per poter procedere con la spedizione è necessario che il mittente sia configurato correttamente.
        /// </summary>
        public static string SenderNotInteroperable {
            get {
                return ResourceManager.GetString("SenderNotInteroperable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;applicazione del sigillo sul file segnatura.xml: non è stato possibile procedere con la spedizione.
        /// </summary>
        public static string SigilloFileSegnaturaXMLNonApplicato {
            get {
                return ResourceManager.GetString("SigilloFileSegnaturaXMLNonApplicato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun utente per il ruolo {0} ({1}).
        /// </summary>
        public static string UtentiRuoloNotFound {
            get {
                return ResourceManager.GetString("UtentiRuoloNotFound", resourceCulture);
            }
        }
    }
}
