--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Viste_ITCOLL\DPA_V_DOC_TRASM.sql
@C:\Users\Francesco\Viste_ITCOLL\DPA_V_DOCUMENTI.sql
@C:\Users\Francesco\Viste_ITCOLL\DPA_V_LOGS.sql
@C:\Users\Francesco\Viste_ITCOLL\DPA_V_TXFASC.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_AUTORIZZAZIONE.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_AUTORIZZAZIONE_2.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_REGISTRO.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_REGISTRO_2.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_UTENTE.sql
@C:\Users\Francesco\Viste_ITCOLL\RDE_UTENTE_2.sql
@C:\Users\Francesco\Viste_ITCOLL\VS01_DOC_CREATI_DA_UT_DELL_RF.sql
@C:\Users\Francesco\Viste_ITCOLL\VS02_UT_NELL_RF.sql
@C:\Users\Francesco\Viste_ITCOLL\VS04_BIS_ANNULLATI.sql
@C:\Users\Francesco\Viste_ITCOLL\VS04_DOC_IN_OUT_INT_GRI.sql
@C:\Users\Francesco\Viste_ITCOLL\VS05_PERC_DOC_ACQUISITI.sql
@C:\Users\Francesco\Viste_ITCOLL\VS06_DOC_SENZA_ALLEGATI.sql
@C:\Users\Francesco\Viste_ITCOLL\VS07_NUM_DOC_CON_ALLEGATI.sql
@C:\Users\Francesco\Viste_ITCOLL\VS08_NUM_DOC_CON_CORR_OCCAS.sql
@C:\Users\Francesco\Viste_ITCOLL\VS09_NUM_VISUALIZ_FILES.sql
@C:\Users\Francesco\Viste_ITCOLL\VS10_NUM_DOC_NON_TRASMES.sql
@C:\Users\Francesco\Viste_ITCOLL\VS11A_GIACENZA_MEDIA_CON_WF.sql
@C:\Users\Francesco\Viste_ITCOLL\VS11B_GIACENZA_MEDIA_SENZA_WF.sql
@C:\Users\Francesco\Viste_ITCOLL\VS12_N_TRASM_OLDER_THAN_30.sql
@C:\Users\Francesco\Viste_ITCOLL\VS13_NUM_MEDIO_DOC_IN_FASC.sql
@C:\Users\Francesco\Viste_ITCOLL\V_TRASMISSIONE.sql
@C:\Users\Francesco\Viste_ITCOLL\V_VISIBILITA_PROT.sql
