<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Core\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Core\**" />
    <None Remove="Application\**" />
    <None Remove="Core\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LinqKit.Core" Version="1.2.5" />
    <PackageReference Include="MediatR" Version="12.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.chilkat\Pi3.Infrastructure.Chilkat\Pi3.Infrastructure.Chilkat.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.itext\Pi3.Infrastructure.IText.ReportGenerator\Pi3.Infrastructure.IText.ReportGenerator.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy\Pi3.Infrastructure.Legacy.DocumentFSRepository\Pi3.Infrastructure.Legacy.DocumentFSRepository.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativo\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativoAggregate.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy\Pi3.Infrastructure.Legacy.EF.Oracle\Pi3.Infrastructure.Legacy.EF.Oracle.csproj" />
    <ProjectReference Include="..\..\..\infrastructure\pi3.infrastructure.legacy\Pi3.Infrastructure.Legacy.EF.Services\Pi3.Infrastructure.Legacy.EF.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Infrastructure\AggregateModels\DocumentBlobAggregate\Files.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Files.resx</DependentUpon>
    </Compile>
    <Compile Update="Infrastructure\Services\OracleDbContextFactory\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Infrastructure\Services\StampaRepertori\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Infrastructure\Services\StampaRepertori\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Infrastructure\AggregateModels\DocumentBlobAggregate\Files.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Files.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Infrastructure\Services\OracleDbContextFactory\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Infrastructure\Services\StampaRepertori\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Infrastructure\Services\StampaRepertori\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="AppSettings.Test.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AppSettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>