ALTER TABLE DPA_SCHEMA_PROCESSO_FIRMA
ADD (DTA_CREAZIONE DATE);

UPDATE DPA_SCHEMA_PROCESSO_FIRMA SET DTA_CREAZIONE  = SYSDATE
WHERE DTA_CREAZIONE IS NULL;
/
COMMIT;

ALTER TABLE DPA_AREA_LAVORO
ADD (VAR_MOTIVO VARCHAR(200) DEFAULT NULL);

ALTER TABLE DPA_STATI
ADD (ID_PROCESSO_FIRMA NUMBER DEFAULT NULL);

ALTER TABLE DPA_ISTANZA_PROCESSO_FIRMA
ADD (CHA_CAMBIO_STATO_DIAG CHAR(1) DEFAULT '0');

ALTER TABLE DPA_PASSI
ADD (CHA_STATO_AUTOMATICO_LF CHAR(1) DEFAULT '0');

CREATE TABLE DPA_ISTANZA_PROC_FIRMA_STO
(
 SYSTEM_ID NUMBER NOT NULL, 
 ID_USER VARCHAR2(255 BYTE), 
 DOC_NUMBER NUMBER, 
 ID_ISTANZA_PROCESSO NUMBER,
 DTA_DATE DATE, 
 VAR_DESC_AZIONE VARCHAR2(255 BYTE), 
 ID_PEOPLE NUMBER, 
 ID_RUOLO NUMBER, 
 ID_PEOPLE_DELEGATO NUMBER,
 CHA_CAMBIO_STATO_DIAG CHAR(1)
);

CREATE SEQUENCE SEQ_DPA_ISTANZA_PROC_FIRMA_STO INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCACHE;


CREATE TABLE DPA_REPORT_PROCESSI_TICK
(
 SYSTEM_ID NUMBER NOT NULL, 
 ID_REPORT_PROCESSI NUMBER,
 ID_PROCESSO NUMBER, 
 NOME_PROCESSO VARCHAR2(256), 
 ID_RUOLO_CREATORE NUMBER, 
 ID_UTENTE_CREATORE NUMBER,
 ID_PASSO NUMBER,
 ID_RUOLO_COINVOLTO NUMBER, 
 ID_UTENTE_COINVOLTO NUMBER
);

CREATE SEQUENCE SEQ_DPA_REPORT_PROCESSI_TICK INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCACHE;