CREATE FUNCTION [DOCSADM].[MAIL_E_NOTE_CORR_ESTERNI]
(
@myId_Corr INTEGER
)
RETURNS VARCHAR(8000)
AS
BEGIN
	DECLARE @Risultato VARCHAR(8000) 
	
	SELECT @Risultato=STUFF((
	  SELECT '; ' + ME.VAR_EMAIL + (CASE WHEN NULLIF(ME.VAR_NOTE,'') IS NULL THEN ' ' ELSE '##' + ME.VAR_NOTE + '##' END)
	  from DOCSADM.DPA_MAIL_CORR_ESTERNI ME where ME.ID_CORR=B.ID_CORR
	  for xml path('')
	  ),1,2,'')
	  from DOCSADM.DPA_MAIL_CORR_ESTERNI B
	  WHERE B.ID_CORR=@myId_Corr
	  GROUP BY B.ID_CORR
	
	
	
	RETURN @Risultato
	
END
GO

