-- MIBACT : colonne modificate per migrazione DB.

ALTER TABLE DPA_CORR_GLOBALI ALTER COLUMN VAR_COGNOME VARCHAR (256);

ALTER TABLE DPA_CORR_GLOBALI ALTER COLUMN VAR_CODICE_AOO VARCHAR (32);

ALTER TABLE DPA_DETT_GLOBALI ALTER COLUMN VAR_CITTA VARCHAR (256);

ALTER TABLE DPA_DETT_GLOBALI ALTER COLUMN VAR_PROVINCIA VARCHAR (50);