--------------------------------------------------------
--  DDL for Table DOCUMENTTYPES
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DOCUMENTTYPES" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"TYPE_ID" VARCHAR2(32 BYTE), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"DISABLED" VARCHAR2(1 BYTE), 
	"STORAGE_TYPE" VARCHAR2(1 BYTE), 
	"RETENTION_DAYS" NUMBER(10,0), 
	"MAX_VERSIONS" NUMBER(10,0), 
	"MAX_SUBVERSIONS" NUMBER(10,0), 
	"FULL_TEXT" VARCHAR2(1 BYTE), 
	"TARGET_DOCSRVR" NUMBER(10,0), 
	"RET_2" NUMBER(10,0), 
	"RET_2_TYPE" VARCHAR2(1 BYTE), 
	"KEEP_CRITERIA" VARCHAR2(1 BYTE), 
	"VERSIONS_TO_KEEP" NUMBER(10,0), 
	"CHA_TIPO_CANALE" VARCHAR2(1 BYTE), 
	DELETED" CHAR(1 BYTE)
   ) ;
