--------------------------------------------------------
--  DDL for Table DPA_CHIAVI_CONF_BKP20110909
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" 
   (	"SYSTEM_ID" NUMBER, 
	"ID_AMM" NUMBER, 
	"VAR_CODICE" VARCHAR2(32 BYTE), 
	"VAR_DESCRIZIONE" VARCHAR2(512 BYTE), 
	"VAR_VALORE" VARCHAR2(128 BYTE), 
	"CHA_TIPO_CHIAVE" VARCHAR2(1 BYTE), 
	"CHA_VISIBILE" VARCHAR2(1 BYTE), 
	"CHA_MODIFICABILE" VARCHAR2(1 BYTE), 
	"CHA_GLOBALE" VARCHAR2(1 BYTE), 
	"VAR_CODICE_OLD_WEBCONFIG" VARCHAR2(64 BYTE)
   ) ;
