--------------------------------------------------------
--  DDL for Table DPA_DELEGHE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_DELEGHE" 
   (	"SYSTEM_ID" NUMBER, 
	"ID_PEOPLE_DELEGANTE" NUMBER, 
	"ID_RUOLO_DELEGANTE" NUMBER, 
	"ID_PEOPLE_DELEGATO" NUMBER, 
	"ID_RUOLO_DELEGATO" NUMBER, 
	"DATA_DECORRENZA" DATE, 
	"DATA_SCADENZA" DATE, 
	"CHA_IN_ESERCIZIO" CHAR(1 BYTE), 
	"COD_PEOPLE_DELEGANTE" VARCHAR2(64 BYTE), 
	"COD_RUOLO_DELEGANTE" VARCHAR2(128 BYTE), 
	"COD_PEOPLE_DELEGATO" VARCHAR2(64 BYTE), 
	"COD_RUOLO_DELEGATO" VARCHAR2(128 BYTE), 
	"ID_UO_DELEGATO" NUMBER
   ) ;
