--------------------------------------------------------
--  DDL for Table DPA_FORMATI_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" 
   (	"SYSTEM_ID" NUMBER(*,0), 
	"ID_AMMINISTRAZIONE" NUMBER(*,0), 
	"FILE_TYPE_USED" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"FILE_EXTENSION" VARCHAR2(10 BYTE), 
	"MAX_FILE_SIZE" NUMBER(*,0) DEFAULT 0, 
	"MAX_FILE_SIZE_ALERT_MODE" NUMBER(*,0) DEFAULT 2, 
	"CONTAINS_FILE_MODEL" NUMBER(*,0) DEFAULT 0, 
	"DOCUMENT_TYPE" NUMBER(*,0) DEFAULT 0, 
	"FILE_TYPE_SIGNATURE" NUMBER(*,0), 
	"FILE_TYPE_PRESERVATION" NUMBER(*,0), 
	"FILE_TYPE_VALIDATION" NUMBER(*,0)
   ) ;
