--------------------------------------------------------
--  DDL for Table DPA_CONFIG_CACHE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_CONFIG_CACHE" 
   (	"IDAMMINISTRAZIONE" VARCHAR2(100 BYTE), 
	"CACHING" NUMBER(*,0), 
	"MASSIMA_DIMENSIONE_CACHING" FLOAT(126), 
	"MASSIMA_DIMENSIONE_FILE" FLOAT(126), 
	"DOC_ROOT_SERVER" VARCHAR2(255 BYTE), 
	"ORA_INIZIO_CACHE" VARCHAR2(10 BYTE), 
	"ORA_FINE_CACHE" VARCHAR2(10 BYTE), 
	"URLWSCACHING" VARCHAR2(500 BYTE), 
	"URL_WS_CACHING_LOCALE" VARCHAR2(500 BYTE), 
	"DOC_ROOT_SERVER_LOCALE" VARCHAR2(255 BYTE)
   ) ;
