--------------------------------------------------------
--  DDL for Table DPA_TRASM_UTENTE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_TRASM_UTENTE" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"ID_TRASM_SINGOLA" NUMBER(10,0), 
	"ID_PEOPLE" NUMBER(10,0), 
	"DTA_VISTA" DATE, 
	"DTA_ACCETTATA" DATE, 
	"DTA_RIFIUTATA" DATE, 
	"DTA_RISPOSTA" DATE, 
	"CHA_VISTA" VARCHAR2(1 BYTE), 
	"CHA_ACCETTATA" VARCHAR2(1 BYTE), 
	"CHA_RIFIUTATA" VARCHAR2(1 BYTE), 
	"VAR_NOTE_ACC" VARCHAR2(250 BYTE), 
	"VAR_NOTE_RIF" VARCHAR2(250 BYTE), 
	"CHA_VALIDA" VARCHAR2(1 BYTE), 
	"ID_TRASM_RISP_SING" NUMBER(10,0), 
	"CHA_IN_TODOLIST" CHAR(1 BYTE) DEFAULT '1', 
	"DTA_RIMOZIONE_TODOLIST" DATE, 
	"ID_PEOPLE_DELEGATO" NUMBER(10,0), 
	"CHA_VISTA_DELEGATO" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CHA_ACCETTATA_DELEGATO" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CHA_RIFIUTATA_DELEGATO" VARCHAR2(1 BYTE) DEFAULT 0
   ) ;
