--------------------------------------------------------
--  DDL for Table DPA_STATO_INVIO
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_STATO_INVIO" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"ID_CORR_GLOBALE" NUMBER(10,0), 
	"ID_PROFILE" NUMBER(10,0), 
	"ID_DOC_ARRIVO_PAR" NUMBER(10,0), 
	"ID_CANALE" NUMBER(10,0), 
	"DTA_SPEDIZIONE" DATE, 
	"VAR_INDIRIZZO" VARCHAR2(128 BYTE), 
	"VAR_CAP" VARCHAR2(5 BYTE), 
	"VAR_CITTA" VARCHAR2(64 BYTE), 
	"CHA_INTEROP" VARCHAR2(1 BYTE), 
	"VAR_PROVINCIA" VARCHAR2(2 BYTE), 
	"ID_DOCUMENTTYPE" NUMBER(10,0), 
	"VAR_SERVER_SMTP" VARCHAR2(64 BYTE), 
	"NUM_PORTA_SMTP" NUMBER(10,0), 
	"VAR_CODICE_AOO" VARCHAR2(16 BYTE), 
	"VAR_CODICE_AMM" VARCHAR2(64 BYTE), 
	"VAR_PROTO_DEST" VARCHAR2(128 BYTE), 
	"DTA_PROTO_DEST" DATE, 
	"VAR_MOTIVO_ANNULLA" VARCHAR2(256 BYTE), 
	"CHA_ANNULLATO" VARCHAR2(1 BYTE), 
	"VAR_PROVVEDIMENTO" VARCHAR2(256 BYTE)
   ) ;
