--------------------------------------------------------
--  DDL for Table DPA_MODELLI_TRASM
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_MODELLI_TRASM" 
   (	"SYSTEM_ID" NUMBER, 
	"ID_AMM" NUMBER, 
	"NOME" VARCHAR2(256 BYTE), 
	"CHA_TIPO_OGGETTO" VARCHAR2(1 BYTE), 
	"ID_REGISTRO" NUMBER, 
	"VAR_NOTE_GENERALI" VARCHAR2(250 BYTE), 
	"ID_PEOPLE" NUMBER, 
	"SINGLE" VARCHAR2(1 BYTE), 
	"CHA_CEDE_DIRITTI" CHAR(1 BYTE) DEFAULT 0, 
	"ID_PEOPLE_NEW_OWNER" NUMBER, 
	"ID_GROUP_NEW_OWNER" NUMBER, 
	"CODICE" VARCHAR2(16 BYTE), 
	"NO_NOTIFY" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"CHA_MANTIENI_LETTURA" CHAR(1 BYTE)
   ) ;
