--------------------------------------------------------
--  DDL for Table ELEMENTIRUBRICA
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" 
   (	"ID" NUMBER(*,0), 
	"CODICE" NVARCHAR2(50), 
	"DESCRIZIONE" NVARCHAR2(255), 
	"DATACREAZIONE" DATE, 
	"DATAULTIMAMODIFICA" DATE, 
	"IDUTENTECREATORE" NUMBER(*,0), 
	"INDIRIZZO" NVARCHAR2(255), 
	"TELEFONO" NVARCHAR2(20), 
	"FAX" NVARCHAR2(20), 
	"CITTA" NVARCHAR2(50), 
	"CAP" NVARCHAR2(5), 
	"PROVINCIA" NVARCHAR2(2), 
	"NAZIONE" NVARCHAR2(50), 
	"AOO" NVARCHAR2(255), 
	"TIPOCORRISPONDENTE" VARCHAR2(5 BYTE), 
	"IDAMMINISTRAZIONE" NUMBER, 
	"CHA_PUBBLICATO" NVARCHAR2(1)
   ) ;
