--------------------------------------------------------
--  DDL for Table MV_PROSPETTI_DOCUMENTICLASS
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."MV_PROSPETTI_DOCUMENTICLASS" 
   (	"ID_AMM" NUMBER(10,0), 
	"ID_TITOLARIO" NUMBER, 
	"ID_REGISTRO" NUMBER(10,0), 
	"PROTO_MONTH" DATE, 
	"CREATION_MONTH" DATE, 
	"VAR_SEDE" VARCHAR2(64 BYTE), 
	"NVL_CHA_IN_CESTINO" VARCHAR2(1 BYTE), 
	"CHA_TIPO_PROTO" VARCHAR2(1 BYTE), 
	"FLAG_ANNULLATO" NUMBER, 
	"FLAG_NUM_PROTO" NUMBER, 
	"FLAG_DTA_PROTO" NUMBER, 
	"DISTINCT_COUNT" NUMBER, 
	"NOT_DISTINCT_COUNT" NUMBER
   ) ;
