--------------------------------------------------------
--  DDL for Table PUBBLICAZIONI_DOCUMENTI
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."PUBBLICAZIONI_DOCUMENTI" 
   (	"SYSTEM_ID" NUMBER, 
	"ID_TIPO_DOCUMENTO" NUMBER, 
	"ID_PROFILE" NUMBER, 
	"ID_USER" NUMBER, 
	"ID_RUOLO" NUMBER, 
	"DATA_DOC_PUBBLICATO" DATE, 
	"DATA_PUBBLICAZIONE_DOCUMENTO" DATE, 
	"ESITO_PUBBLICAZIONE" VARCHAR2(1 BYTE), 
	"ERRORE_PUBBLICAZIONE" VARCHAR2(255 BYTE)
   ) ;
