--------------------------------------------------------
--  DDL for Table PUBLISHER_INSTANCES
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" 
   (	"ID" NUMBER, 
	"INSTANCENAME" NVARCHAR2(50), 
	"IDADMIN" NUMBER, 
	"SUBSCRIBERSERVICEURL" NVARCHAR2(1000), 
	"LASTEXECUTIONDATE" DATE, 
	"EXECUTIONCOUNT" NUMBER(*,0), 
	"PUBLISHEDOBJECTS" NUMBER(*,0), 
	"STARTEXECUTIONDATE" DATE, 
	"ENDEXECUTIONDATE" DATE, 
	"LASTLOGID" NUMBER, 
	"STARTLOGDATE" DATE, 
	"EXECUTIONTYPE" VARCHAR2(50 BYTE), 
	"EXECUTIONTICKS" VARCHAR2(100 BYTE), 
	"TOTALEXECUTIONCOUNT" NUMBER(*,0), 
	"TOTALPUBLISHEDOBJECTS" NUMBER(*,0), 
	"MACHINENAME" NVARCHAR2(50), 
	"PUBLISHERSERVICEURL" NVARCHAR2(1000)
   ) ;
