--------------------------------------------------------
--  DDL for Table REMOTE_LIBRARIES
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."REMOTE_LIBRARIES" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"LIBRARY_NAME" VARCHAR2(20 BYTE), 
	"LIBRARY_DESC" VARCHAR2(80 BYTE), 
	"DISABLED" VARCHAR2(1 BYTE), 
	"ORACLE_MIXED_CASE" NUMBER(10,0), 
	"OWNER" VARCHAR2(80 BYTE), 
	"DATABASE_ENGINE" NUMBER(10,0), 
	"OPERATING_SYSTEM" NUMBER(10,0), 
	"SERVER_LOCATION" VARCHAR2(128 BYTE), 
	"DATABASE_NAME" VARCHAR2(18 BYTE), 
	"LIB_LOGIN_UNAME" VARCHAR2(30 BYTE), 
	"SQL_PASSWORD" VARCHAR2(250 BYTE), 
	"SHADOW_DOCS" VARCHAR2(1 BYTE), 
	"PRESHADOW" VARCHAR2(1 BYTE), 
	"DEFAULT_SEARCH" VARCHAR2(1 BYTE), 
	"BRIDGED" VARCHAR2(1 BYTE), 
	"LIBRARY_GROUP" VARCHAR2(10 BYTE), 
	"LIB_LOGIN_SCHEME" VARCHAR2(1 BYTE)
   ) ;
