--------------------------------------------------------
--  DDL for Table SIMPINTEROPRECEIVEDMESSAGE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."SIMPINTEROPRECEIVEDMESSAGE" 
   (	"PROFILEID" NUMBER, 
	"MESSAGEID" VARCHAR2(1000 BYTE), 
	"RECEIVEDPRIVATE" NUMBER, 
	"RECEIVEDDATE" DATE, 
	"SUBJECT" VARCHAR2(4000 BYTE), 
	"SENDERDESCRIPTION" VARCHAR2(4000 BYTE), 
	"SENDERURL" VARCHAR2(2000 BYTE), 
	"SENDERADMINISTRATIONCODE" VARCHAR2(2000 BYTE), 
	"AOOCODE" VARCHAR2(2000 BYTE), 
	"RECORDNUMBER" NUMBER, 
	"RECORDDATE" DATE, 
	"RECEIVERCODE" VARCHAR2(2000 BYTE)
   ) ;
