// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using InformaticaTrentinaPCL.iOS.Helper;
using InformaticaTrentinaPCL.Utils;
using UIKit;

namespace InformaticaTrentinaPCL.iOS.TabBar.Document.Action.Root.Storyboard
{
    public partial class ControllerNote : UIViewController,IUITextViewDelegate
	{
        public Action<SupporTypeAction,String> Callback;
        public String placeholder = Utility.LanguageConvert("tetx_view_note");
        public Action<nfloat,nfloat> CallbackChangeHeightNote;

		public ControllerNote (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            textview.Delegate = this;
            viewfooter.BackgroundColor = Colors.COLOR_SEARCH_FOOTER;
            textview.Text = placeholder;
            textview.TextColor = Colors.COLOR_SEARCH_FOOTER;
        }

        [Export("textViewShouldBeginEditing:")]
        public bool ShouldBeginEditing(UITextView textView)
        {
            textview.Text = textview.Text == placeholder ? "" : textview.Text;
            textview.TextColor = UIColor.DarkGray;
          
            Keyboard.CUSTOM_Y = 0;
            if (Utility.IsTablet() && UIApplication.SharedApplication.StatusBarOrientation.IsLandscape())
            {
                Keyboard.CUSTOM_Y = 150;
            }

            if (Callback != null)
            {
                Callback(SupporTypeAction.UPDATE_TEXT_NOTE, textView.Text);
            }

            return true;
        }

        [Export("textView:shouldChangeTextInRange:replacementText:")]
        public bool ShouldChangeText(UITextView textView, NSRange range, string text)
        {
            if (text != "\n")
            {
                NSString newString = ((NSString)textView.Text).Replace(range, (NSString)text);
                textView.Text = newString;
            }

        

            if (CallbackChangeHeightNote != null)
            {
                try
                {
                    var y = textview.Superview.Superview.Frame.Y;
                    Console.WriteLine(y);
                    Console.WriteLine(textview.ContentSize.Height);
                    CallbackChangeHeightNote(y, textview.ContentSize.Height);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
                                       
            if (Callback != null)
            {
                Callback(SupporTypeAction.UPDATE_TEXT_NOTE,textView.Text);
            }

            if (text == "\n")
                textview.EndEditing(true);

            return false;
        }


	}
}
