CREATE OR REPLACE FUNCTION @db_user.GetCodReg(idREG NUMBER)
RETURN VARCHAR2 IS risultato VARCHAR2(16);

BEGIN
begin

SELECT VAR_CODICE INTO risultato FROM DPA_EL_REGISTRI WHERE SYSTEM_ID = idREG;

EXCEPTION
WHEN OTHERS THEN
risultato:='';
end;
RETURN risultato;
END GetCodReg;
/