CREATE OR REPLACE FUNCTION @db_user.getInScarto (IDPROFILE number,Idproject number, idPeople number, idGruppo number)

RETURN INT IS risultato INT;
res_appo INT;
idRuoloInUo NUMBER;
BEGIN
begin

SELECT DPA_CORR_GLOBALI.SYSTEM_ID INTO idRuoloInUo FROM DPA_CORR_GLOBALI WHERE DPA_CORR_GLOBALI.ID_GRUPPO = idGruppo;

SELECT COUNT(DPA_ITEMS_SCARTO.SYSTEM_ID) INTO risultato FROM DPA_AREA_SCARTO, DPA_ITEMS_SCARTO WHERE 
DPA_ITEMS_SCARTO.ID_SCARTO=DPA_AREA_SCARTO.SYSTEM_ID AND ID_PROJECT = Idproject
AND DPA_ITEMS_SCARTO.CHA_STATO ='N'
AND DPA_AREA_SCARTO.ID_PEOPLE=idPeople AND 
DPA_AREA_SCARTO.ID_RUOLO_IN_UO = idRuoloInUo;

IF (risultato > 0) THEN
risultato := 1;
ELSE
risultato:=0;
END IF;

EXCEPTION
WHEN NO_DATA_FOUND THEN risultato := 0;
WHEN OTHERS THEN risultato := 0;
end;
RETURN risultato;
END getInScarto;
/
