CREATE PROCEDURE SP_NEW_AMM_ADD_DEFAULT
@idamm INT
AS
BEGIN
declare @ammRiferimento int = 10
 
--TIPI RUOLO
INSERT INTO DPA_TIPO_RUOLO ([ID_AMM]
      ,[ID_PARENT]
      ,[VAR_CODICE]
      ,[NUM_LIVELLO]
      ,[VAR_DESC_RUOLO])
SELECT @idamm as ID_AMM,[ID_PARENT]
      ,[VAR_CODICE]
      ,[NUM_LIVELLO]
      ,[VAR_DESC_RUOLO] FROM [DPA_TIPO_RUOLO] WHERE ID_AMM = @ammRiferimento
 
--TIPO DOCUMENTO
INSERT INTO DPA_TIPO_ATTO (VAR_DESC_ATTO, ID_AMM, Abilitato_SI_NO, In_Esercizio, Path_Mod_1, Ext_Mod_1, Path_Mod_2, Ext_mod_2, GG_SCADENZA, GG_PRE_SCADENZA, CHA_PRIVATO, PATH_ALL_1, EXT_ALL_1, PATH_MOD_SU, IPERDOCUMENTO, COD_MOD_TRASM, COD_CLASS, Path_Mod_Exc, NUM_MESI_CONSERVAZIONE, PATH_XSD_ASSOCIATO, PESO, CHA_INVIO_CONSERVAZIONE, IS_TYPE_INSTANCE, ID_CONTESTO_PROCEDURALE)
SELECT VAR_DESC_ATTO, @idamm, Abilitato_SI_NO, In_Esercizio, Path_Mod_1, Ext_Mod_1, Path_Mod_2, Ext_mod_2, GG_SCADENZA, GG_PRE_SCADENZA, CHA_PRIVATO, PATH_ALL_1, EXT_ALL_1, PATH_MOD_SU, IPERDOCUMENTO, COD_MOD_TRASM, COD_CLASS, Path_Mod_Exc, NUM_MESI_CONSERVAZIONE, PATH_XSD_ASSOCIATO, PESO, CHA_INVIO_CONSERVAZIONE, IS_TYPE_INSTANCE, ID_CONTESTO_PROCEDURALE FROM DPA_TIPO_ATTO 
WHERE ID_AMM = @ammRiferimento AND Abilitato_SI_NO = 1
 
--TIPO OGGETTO
INSERT INTO DPA_OGGETTI_CUSTOM (Descrizione, Orizzontale_Verticale, Campo_Obbligatorio, Multilinea, Numero_Di_Linee, Numero_Di_Caratteri, Campo_Di_Ricerca, ID_TIPO_OGGETTO, RESET_ANNO, FORMATO_CONTATORE, ID_R_DEFAULT, 
RICERCA_CORR, CAMPO_COMUNE, CHA_TIPO_TAR, CONTA_DOPO, REPERTORIO, DA_VISUALIZZARE_RICERCA, FORMATO_ORA, TIPO_LINK, TIPO_OBJ_LINK, CONFIG_OBJ_EST, MODULO_SOTTOCONTATORE, CHA_CONSOLIDAMENTO, CHA_CONSERVAZIONE, CHA_CONS_REPERTORIO)
SELECT DPA_OGGETTI_CUSTOM.Descrizione, DPA_OGGETTI_CUSTOM.Orizzontale_Verticale, DPA_OGGETTI_CUSTOM.Campo_Obbligatorio, DPA_OGGETTI_CUSTOM.Multilinea, DPA_OGGETTI_CUSTOM.Numero_Di_Linee, DPA_OGGETTI_CUSTOM.Numero_Di_Caratteri, 
DPA_OGGETTI_CUSTOM.Campo_Di_Ricerca, DPA_OGGETTI_CUSTOM.ID_TIPO_OGGETTO, DPA_OGGETTI_CUSTOM.RESET_ANNO, DPA_OGGETTI_CUSTOM.FORMATO_CONTATORE, DPA_OGGETTI_CUSTOM.ID_R_DEFAULT, DPA_OGGETTI_CUSTOM.RICERCA_CORR, DPA_OGGETTI_CUSTOM.CAMPO_COMUNE, 
DPA_OGGETTI_CUSTOM.CHA_TIPO_TAR, DPA_OGGETTI_CUSTOM.CONTA_DOPO, DPA_OGGETTI_CUSTOM.REPERTORIO, DPA_OGGETTI_CUSTOM.DA_VISUALIZZARE_RICERCA, DPA_OGGETTI_CUSTOM.FORMATO_ORA, DPA_OGGETTI_CUSTOM.TIPO_LINK, DPA_OGGETTI_CUSTOM.SYSTEM_ID, 
DPA_OGGETTI_CUSTOM.CONFIG_OBJ_EST, DPA_OGGETTI_CUSTOM.MODULO_SOTTOCONTATORE, DPA_OGGETTI_CUSTOM.CHA_CONSOLIDAMENTO, DPA_OGGETTI_CUSTOM.CHA_CONSERVAZIONE, DPA_OGGETTI_CUSTOM.CHA_CONS_REPERTORIO
FROM DPA_TIPO_ATTO INNER JOIN DPA_OGG_CUSTOM_COMP 
ON DPA_TIPO_ATTO.SYSTEM_ID = DPA_OGG_CUSTOM_COMP.ID_TEMPLATE 
INNER JOIN DPA_OGGETTI_CUSTOM ON DPA_OGG_CUSTOM_COMP.ID_OGG_CUSTOM = DPA_OGGETTI_CUSTOM.SYSTEM_ID
WHERE ID_AMM = @ammRiferimento
 
--RELAZIONE TIPO DOCUMENTO TIPO OGGETTO
INSERT INTO DPA_OGG_CUSTOM_COMP (ID_TEMPLATE, ID_OGG_CUSTOM, POSIZIONE, Enabledhistory, CAMPO_XML_ASSOC, OPZIONI_XML_ASSOC)
SELECT D.SYSTEM_ID, B.SYSTEM_ID as ID_OGG_CUSTOM, A.POSIZIONE, A.Enabledhistory, A.CAMPO_XML_ASSOC, A.OPZIONI_XML_ASSOC 
FROM DPA_OGG_CUSTOM_COMP A INNER JOIN DPA_OGGETTI_CUSTOM B 
ON A.ID_OGG_CUSTOM = B.TIPO_OBJ_LINK
INNER JOIN DPA_TIPO_ATTO C ON A.ID_TEMPLATE = C.SYSTEM_ID
INNER JOIN DPA_TIPO_ATTO D ON C.VAR_DESC_ATTO = D.VAR_DESC_ATTO
WHERE D.ID_AMM = @idamm AND C.ID_AMM = @ammRiferimento
 
--PULIZIA CAMPO APPOGGIO
UPDATE DPA_OGGETTI_CUSTOM SET TIPO_OBJ_LINK = null WHERE SYSTEM_ID IN 
(SELECT ID_OGG_CUSTOM FROM DPA_OGG_CUSTOM_COMP INNER JOIN DPA_TIPO_ATTO 
ON DPA_OGG_CUSTOM_COMP.ID_TEMPLATE = DPA_TIPO_ATTO.SYSTEM_ID AND DPA_TIPO_ATTO.ID_AMM = @idamm) 
 
END
GO
 
