-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 05/03/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
-- GETUO
-- =============================================

CREATE FUNCTION [DOCSADM].[GETUO]
(
	@IDRUOLO	INT
)
RETURNS VARCHAR(256)
AS
BEGIN
	DECLARE @RISULTATO	VARCHAR(256)
	
	SELECT @RISULTATO = C.VAR_DESC_CORR
	FROM DOCSADM.DPA_CORR_GLOBALI C
	WHERE C.SYSTEM_ID IN (SELECT ID_UO FROM DOCSADM.DPA_CORR_GLOBALI WHERE SYSTEM_ID = @IDRUOLO)

	RETURN @RISULTATO
END

