--------------------------------------------------------
--  DDL for Procedure CARICA_FORMATO_DOCUMENTI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ITCOLL_6GIU12"."CARICA_FORMATO_DOCUMENTI" IS

CURSOR currAmm IS
select system_id
from dpa_amministra ORDER BY system_id DESC;


BEGIN
FOR currentAmm in currAmm
LOOP

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='PDF');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES (seq.nextval, currentAmm.system_id, 1, 'Adobe Acrobat', 'PDF', 0, 2, 0, 0);
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='TXT');
IF ( cnt != 0 ) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	(seq.nextval, currentAmm.system_id, 1, 'File di testo', 'TXT', 0, 2, 0, 0);
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='P7M');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	(seq.nextval, currentAmm.system_id, 1, 'File firmati digitalmente', 'P7M', 0,	2, 	0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='BMP');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Immagine Bitmap', 'BMP', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='JPG');
IF (cnt != 0)
THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Immagine JPG', 'JPG', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='TIF');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Immagine TIF', 'TIF', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='TIFF');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Immagine TIFF', 'TIFF', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='PPT');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	(  seq.nextval, currentAmm.system_id, 1, 'Microsoft PowerPoint', 'PPT', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='DOC');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	(  seq.nextval,currentAmm.system_id, 1, 'Microsoft Word', 'DOC', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='XLS');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (	SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	(  seq.nextval, currentAmm.system_id, 1, 'Microsoft Excel',  'XLS', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='RTF');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (	SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Rich Text Format', 'RTF', 0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='HTM');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (	SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval,currentAmm.system_id, 1, 'Web Publishing Browser (htm)', 'HTM',	0, 2, 0, 0 );
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FORMATI_DOCUMENTO WHERE (FILE_EXTENSION='HTML');
IF (cnt != 0) THEN
INSERT INTO DPA_FORMATI_DOCUMENTO (	SYSTEM_ID, ID_AMMINISTRAZIONE, FILE_TYPE_USED, DESCRIPTION, FILE_EXTENSION, MAX_FILE_SIZE, MAX_FILE_SIZE_ALERT_MODE, CONTAINS_FILE_MODEL, DOCUMENT_TYPE)
VALUES	( seq.nextval, currentAmm.system_id, 1, 'Web Publishing Browser (html)', 'HTML', 0, 2, 0, 0 );
END IF;
END;

END;






END LOOP;
commit;

END; 

/
