--------------------------------------------------------
--  DDL for Procedure CARICA_DOCUMENTI_RISERVATI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ITCOLL_6GIU12"."CARICA_DOCUMENTI_RISERVATI" IS

CURSOR currAmm IS
select system_id
from dpa_amministra ORDER BY system_id DESC;


BEGIN
FOR currentAmm in currAmm
LOOP


BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FUNZIONI WHERE (COD_FUNZIONE='DO_FASC_PRIVATO' AND ID_AMM IS NULL);
IF (cnt != 0) THEN
INSERT INTO DPA_FUNZIONI ( ID_AMM, SYSTEM_ID, COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES (currentAmm.system_id, seq.nextval, 'DO_FASC_PRIVATO', 'DO_FASC_PRIVATO', (SELECT SYSTEM_ID FROM DPA_TIPO_FUNZIONE WHERE VAR_COD_TIPO='DOC_RIS' AND ID_AMM=currentAmm.system_id));
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FUNZIONI WHERE (COD_FUNZIONE='DO_PROTO_PRIVATO'AND ID_AMM IS NULL);
IF (cnt != 0) THEN
INSERT INTO DPA_FUNZIONI ( ID_AMM, SYSTEM_ID, COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES (currentAmm.system_id, seq.nextval, 'DO_PROTO_PRIVATO', 'DO_PROTO_PRIVATO', (SELECT SYSTEM_ID FROM DPA_TIPO_FUNZIONE WHERE VAR_COD_TIPO='DOC_RIS' AND ID_AMM=currentAmm.system_id));
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FUNZIONI WHERE (COD_FUNZIONE='DO_CREA_PRIVATO' AND ID_AMM IS NULL);
IF (cnt != 0) THEN
INSERT INTO DPA_FUNZIONI ( ID_AMM, SYSTEM_ID, COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES (currentAmm.system_id, seq.nextval, 'DO_CREA_PRIVATO', 'DO_CREA_PRIVATO', (SELECT SYSTEM_ID FROM DPA_TIPO_FUNZIONE WHERE VAR_COD_TIPO='DOC_RIS' AND ID_AMM=currentAmm.system_id));
END IF;
END;
END;

BEGIN
DECLARE cnt INT;
BEGIN
SELECT COUNT(*) INTO cnt FROM DPA_FUNZIONI WHERE (COD_FUNZIONE='DO_PROTO_PRIVATO_SEMPL' AND ID_AMM IS NULL);
IF (cnt != 0) THEN
INSERT INTO DPA_FUNZIONI ( ID_AMM, SYSTEM_ID, COD_FUNZIONE, VAR_DESC_FUNZIONE, ID_TIPO_FUNZIONE )
VALUES (currentAmm.system_id, seq.nextval, 'DO_PROTO_PRIVATO_SEMPL', 'DO_PROTO_PRIVATO_SEMPL', (SELECT SYSTEM_ID FROM DPA_TIPO_FUNZIONE WHERE VAR_COD_TIPO='DOC_RIS' AND ID_AMM=currentAmm.system_id));
END IF;
END;
END;

END LOOP;
commit;

END; 

/
