 CREATE TABLE @db_user.DPA_ASS_RUOLO_STATI_DIAGRAMMA 
(
  SYSTEM_ID NUMBER(10, 0) NOT NULL 
, ID_GRUPPO NUMBER(10, 0) NOT NULL 
, ID_DIAGRAMMA NUMBER(38, 0) NOT NULL 
, ID_STATO NUMBER(38, 0) NOT NULL 
, CHA_NOT_VIS VARCHAR2(1) DEFAULT '1' NOT NULL 
, CONSTRAINT DPA_ASS_RUOLO_STATI_DIAGR_PK PRIMARY KEY 
  (
    SYSTEM_ID 
  )
  ENABLE 
);
/