/*
***                        ATTENZIONE                       ***
*** Script convertito da Oracle a SQL Server ma non testato ***
*** Testare prima di utilizzare                             ***
*/

CREATE TABLE DPA_CONFIG_ALERT_CONS
(
SYSTEM_ID							INT IDENTITY(1,1) NOT NULL,
ID_AMM								INT,

VAR_SERVER_SMTP						VARCHAR(64 BYTE),
NUM_PORTA_SMTP						INT,
CHA_SMTP_SSL						CHAR(1 BYTE),
VAR_USER_MAIL						VARCHAR(128 BYTE),
VAR_PWD_MAIL						VARCHAR(128 BYTE),
VAR_MAIL_NOTIFICA					CHAR(500 BYTE),
VAR_MAIL_DESTINATARIO				VARCHAR(128 BYTE),

CHA_ALERT_LEGGIBILITA_SCADENZA		CHAR(1 BYTE),
NUM_LEGG_SCADENZA_TERMINE			INT,
NUM_LEGG_SCADENZA_TOLLERANZA		INT,

CHA_ALERT_LEGGIBILITA_MAX_DOC		CHAR(1 BYTE),
NUM_LEGGIBILITA_MAX_DOC_PERC		INT,

CHA_ALERT_LEGGIBILITA_SING			CHAR(1 BYTE),
NUM_LEGG_SING_MAX_OPER				INT,
NUM_LEGG_SING_PERIODO_MON			INT,

CHA_ALERT_DOWNLOAD					CHAR(1 BYTE),
NUM_DOWNLOAD_MAX_OPER				INT,
NUM_DOWNLOAD_PERIODO_MON			INT,

CHA_ALERT_SFOGLIA					CHAR(1 BYTE),
NUM_SFOGLIA_MAX_OPER				INT,
NUM_SFOGLIA_PERIODO_MON				INT
)