//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NttDataWA.ClientBigfile {
    
    
    public partial class DownloadClientBigfile {
        
        /// <summary>
        /// PnlLtlDownloadFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PnlLtlDownloadFile;
        
        /// <summary>
        /// LtlDownloadFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal LtlDownloadFile;
        
        /// <summary>
        /// ClientBigfileOk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NttDatalLibrary.CustomButton ClientBigfileOk;
        
        /// <summary>
        /// ClientBigfileClose control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NttDatalLibrary.CustomButton ClientBigfileClose;
    }
}
