SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE PROCEDURE @db_user.SP_INS_MODELLI_DEST_NOTIFICA

AS

DECLARE @VAR_ID_MITT_DEST INT
DECLARE @VAR_ID_PEOPLE INT
DECLARE @VAR_ID_MODELLO INT


BEGIN

DECLARE cursorINS CURSOR FOR
SELECT
MMD.SYSTEM_ID,
PG.PEOPLE_SYSTEM_ID,
MMD.ID_MODELLO
FROM @db_user.DPA_CORR_GLOBALI CG, @db_user.DPA_MODELLI_MITT_DEST MMD, @db_user.PEOPLEGROUPS PG
WHERE CG.SYSTEM_ID = MMD.ID_CORR_GLOBALI
AND CG.ID_GRUPPO = PG.GROUPS_SYSTEM_ID
AND MMD.CHA_TIPO_MITT_DEST = 'D'
AND MMD.CHA_TIPO_URP = 'R'
AND PG.DTA_FINE IS NULL
AND MMD.SYSTEM_ID NOT IN (SELECT DISTINCT ID_MODELLO_MITT_DEST FROM @db_user.DPA_MODELLI_DEST_CON_NOTIFICA)
ORDER BY MMD.ID_MODELLO

BEGIN
OPEN cursorINS
FETCH NEXT FROM cursorINS
INTO @VAR_ID_MITT_DEST, @VAR_ID_PEOPLE, @VAR_ID_MODELLO

WHILE @@FETCH_STATUS = 0

BEGIN

INSERT INTO @db_user.DPA_MODELLI_DEST_CON_NOTIFICA
(ID_MODELLO_MITT_DEST,
ID_PEOPLE,
ID_MODELLO)
VALUES
(@VAR_ID_MITT_DEST,
@VAR_ID_PEOPLE,
@VAR_ID_MODELLO)

FETCH NEXT FROM cursorINS
INTO @VAR_ID_MITT_DEST, @VAR_ID_PEOPLE, @VAR_ID_MODELLO
END

CLOSE cursorINS
DEALLOCATE cursorINS
END
END
GO


SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO