--------------------------------------------------------
--  DDL for Function GETINCONSERVAZIONE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "ITCOLL_6GIU12"."GETINCONSERVAZIONE" (IDPROFILE number,Idproject number, typeID char, idPeople number, idGruppo number)

RETURN INT IS risultato INT;
res_appo INT;
idRuoloInUo NUMBER;
BEGIN
begin

SELECT DPA_CORR_GLOBALI.SYSTEM_ID INTO idRuoloInUo FROM DPA_CORR_GLOBALI WHERE DPA_CORR_GLOBALI.ID_GRUPPO = idGruppo;

IF (typeID = 'D' AND Idproject is null ) THEN
SELECT COUNT(DPA_ITEMS_CONSERVAZIONE.SYSTEM_ID) INTO risultato FROM DPA_AREA_CONSERVAZIONE, DPA_ITEMS_CONSERVAZIONE WHERE
DPA_ITEMS_CONSERVAZIONE.ID_CONSERVAZIONE=DPA_AREA_CONSERVAZIONE.SYSTEM_ID AND ID_PROFILE = IDPROFILE
AND DPA_ITEMS_CONSERVAZIONE.CHA_STATO ='N' AND DPA_AREA_CONSERVAZIONE.ID_PEOPLE=idPeople AND
DPA_AREA_CONSERVAZIONE.ID_RUOLO_IN_UO = idRuoloInUo  AND ID_PROJECT IS  NULL;
ELSE
IF (typeID = 'D' AND Idproject is NOT null ) THEN
SELECT COUNT(DPA_ITEMS_CONSERVAZIONE.SYSTEM_ID) INTO risultato FROM DPA_AREA_CONSERVAZIONE, DPA_ITEMS_CONSERVAZIONE WHERE
DPA_ITEMS_CONSERVAZIONE.ID_CONSERVAZIONE=DPA_AREA_CONSERVAZIONE.SYSTEM_ID AND ID_PROFILE = IDPROFILE
AND DPA_ITEMS_CONSERVAZIONE.CHA_STATO ='N' AND DPA_AREA_CONSERVAZIONE.ID_PEOPLE=idPeople AND
DPA_AREA_CONSERVAZIONE.ID_RUOLO_IN_UO = idRuoloInUo  AND ID_PROJECT =Idproject;
END IF;END IF;
IF (typeID = 'F') THEN
SELECT COUNT(DPA_ITEMS_CONSERVAZIONE.SYSTEM_ID) INTO risultato FROM DPA_AREA_CONSERVAZIONE, DPA_ITEMS_CONSERVAZIONE WHERE
DPA_ITEMS_CONSERVAZIONE.ID_CONSERVAZIONE=DPA_AREA_CONSERVAZIONE.SYSTEM_ID AND ID_PROJECT = Idproject
AND DPA_ITEMS_CONSERVAZIONE.CHA_STATO ='N'
AND DPA_AREA_CONSERVAZIONE.ID_PEOPLE=idPeople AND
DPA_AREA_CONSERVAZIONE.ID_RUOLO_IN_UO = idRuoloInUo;

END IF;

IF (risultato > 0) THEN
risultato := 1;
ELSE
risultato:=0;
END IF;


EXCEPTION
WHEN NO_DATA_FOUND THEN risultato := 0;
WHEN OTHERS THEN risultato := 0;
end;
RETURN risultato;
END getInConservazione; 

/
