ALTER TABLE COMPONENTS ADD (ID_PEOPLE_PUTFILE NUMBER(10,0) DEFAULT NULL);
COMMENT ON COLUMN COMPONENTS.ID_PEOPLE_PUTFILE IS 'SYSTEM_ID DELLA PEOPLE CHE HA ACQUISITO IL FILE';


ALTER TABLE COMPONENTS ADD (DTA_FILE_ACQUIRED DATE DEFAULT NULL);
COMMENT ON COLUMN COMPONENTS.DTA_FILE_ACQUIRED IS 'Data di acquisizione del file';