CREATE TABLE DPA_DESCRIZIONI_FASC
(
 SYSTEM_ID INT primary key IDENTITY(1,1) NOT NULL, 
 VAR_DESCRIZIONE VARCHAR(2000),
 VAR_CODICE VARCHAR(50),
 ID_REGISTRO INT,
 ID_AMM INT
)

ALTER TABLE DPA_MAIL_REGISTRI 
ADD VAR_MESSAGE_SEND_MAIL VARCHAR(2000) 

ALTER TABLE DPA_MAIL_REGISTRI 
ADD CHA_OVERWRITE_MESSAGE_AMM CHAR(1)

ALTER TABLE DPA_AMMINISTRA
ADD CHA_ENABLE_CONS	VARCHAR(1)
