CREATE TABLE DPA_ALERT_CONSERVAZIONE
(
SYSTEM_ID				NUMBER 	NOT NULL,
ID_AMM					NUMBER,
ID_PEOPLE				NUMBER,
ID_GRUPPO				NUMBER,
VAR_CODICE				VARCHAR2(250 BYTE),
NUM_OPERAZIONI			NUMBER,
DTA_INIZIO_MONITORAGGIO	DATE
);