<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Pi3.App.Search.WebApi</RootNamespace>
    <UserSecretsId>a9cc8f97-2d24-4d1d-a4e0-460f33315ccb</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Application\Commands\**" />
    <Compile Remove="Application\DomainEventHandlers\**" />
    <Compile Remove="Application\Exceptions\**" />
    <Content Remove="Application\Commands\**" />
    <Content Remove="Application\DomainEventHandlers\**" />
    <Content Remove="Application\Exceptions\**" />
    <EmbeddedResource Remove="Application\Commands\**" />
    <EmbeddedResource Remove="Application\DomainEventHandlers\**" />
    <EmbeddedResource Remove="Application\Exceptions\**" />
    <None Remove="Application\Commands\**" />
    <None Remove="Application\DomainEventHandlers\**" />
    <None Remove="Application\Exceptions\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="6.4.1" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.10" />
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.Queries" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00016" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.5.0-dev-00359" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.1-dev-00947" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <ProjectReference Include="..\..\pi3.infrastructure.aac-main\Pi3.Infrastructure.AAC\Pi3.Infrastructure.AAC.csproj" />
    <ProjectReference Include="..\..\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativo\Pi3.Infrastructure.Legacy.EF.DocumentoAmministrativoAggregate.csproj" />
    <ProjectReference Include="..\..\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.EF.Oracle\Pi3.Infrastructure.Legacy.EF.Oracle.csproj" />
    <ProjectReference Include="..\..\pi3.infrastructure.legacy-main\Pi3.Infrastructure.Legacy.EF.Services\Pi3.Infrastructure.Legacy.EF.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Application\Queries\Elements\GetElements\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>
  <ItemGroup>
    <InternalsVisibleTo Include="Pi3.App.Search.WebApi.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doc.Application.Search.DocumentoAmministrativo\Doc.Application.Search.DocumentoAmministrativo.csproj" />
    <ProjectReference Include="..\Doc.Search.DocumentoAmministrativo\Doc.Search.DocumentoAmministrativo.csproj" />
    <ProjectReference Include="..\pi3.Core.Contracts\pi3.Core.Contracts.csproj" />
    <ProjectReference Include="..\Pi3.Infrastructure.Elastic\Pi3.Infrastructure.Elastic.csproj" />
  </ItemGroup>
</Project>