ALTER TABLE DPA_SCHEMA_PROCESSO_FIRMA
ADD CHA_MODELLO CHAR(1) DEFAULT '0' 

ALTER TABLE DPA_SCHEMA_PROCESSO_FIRMA
ADD ID_AMM NUMBER

ALTER TABLE DOCUMENTTYPES
ADD LABEL VARCHAR(200) DEFAULT NULL

UPDATE DOCUMENTTYPES SET LABEL= 'IS' where type_id = 'SIMPLIFIEDINTEROPERABILITY'

UPDATE DPA_RAGIONE_TRASM SET VAR_DESC_RAGIONE = 'INTEROPERABILITA SEMPLIFICATA', VAR_NOTE = 'Ragione per trasmissione interoperabilita'' Semplificata' where VAR_DESC_RAGIONE = 'INTEROPERABILITA PITRE'

UPDATE DPA_ANAGRAFICA_LOG
SET VAR_CODICE = 'TRASM_DOC_INTEROPERABILITA_SEMPLIFICATA',
VAR_METODO = 'TRASM_DOC_INTEROPERABILITA_SEMPLIFICATA',
VAR_DESCRIZIONE = 'Effettuata trasmissione documento con ragione INTEROPERABILITA SEMPLIFICATA'
WHERE VAR_CODICE = 'TRASM_DOC_INTEROPERABILITA_PITRE'