--------------------------------------------------------
--  DDL for View RDE_UTENTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ITCOLL_6GIU12"."RDE_UTENTE" ("IDUTENTE", "IDUTENTEREMOTO", "PASSWORD", "IDAMMINISTRAZIONEREMOTO", "COGNOME", "NOME") AS 
  SELECT DISTINCT A.USER_ID  AS IdUtente, A.SYSTEM_ID  AS IdUtenteRemoto, A.USER_PASSWORD AS Password,  B.ID_AMM  AS IdAmministrazioneRemoto, B.VAR_COGNOME AS Cognome, B.VAR_NOME AS Nome FROM   DPA_CORR_GLOBALI B, PEOPLEGROUPS C, PEOPLE A WHERE A.SYSTEM_ID = B.ID_PEOPLE AND (B.CHA_TIPO_URP = 'P')  AND (B.CHA_TIPO_IE = 'I') AND (B.DTA_FINE IS NULL) AND   (A.SYSTEM_ID = C.PEOPLE_SYSTEM_ID AND C.GROUPS_SYSTEM_ID IN (SELECT N.ID_GRUPPO FROM DPA_TIPO_F_RUOLO M, DPA_CORR_GLOBALI N WHERE ID_TIPO_FUNZ IN (select id_tipo_funzione from DPA_FUNZIONI where cod_funzione = 'PROTO_EME') AND M.ID_RUOLO_IN_UO = N.SYSTEM_ID));
