// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: AGPL-3.0-or-later
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.Legacy.WebApi.Application.Handlers.CheckMailBox.Daticert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.Legacy.WebApi.Application.Handlers.CheckMailBox.Daticert.ErrorDescription" +
                            "", typeof(ErrorDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errore nella creazioen del tipo allegato: {0}.
        /// </summary>
        internal static string AttCreationError {
            get {
                return ResourceManager.GetString("AttCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel metodo aggiungiAllegato per l&apos;allegato n. {0}.
        /// </summary>
        internal static string CantAddAttachment {
            get {
                return ResourceManager.GetString("CantAddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel reperimento del file allegato: {0}.
        /// </summary>
        internal static string CantPullAttachmentFile {
            get {
                return ResourceManager.GetString("CantPullAttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante il salvataggio delle informazioni relative al tipo della ricevuta. La Mail e i suoi allegati risultano salvata.
        /// </summary>
        internal static string CantSaveNot {
            get {
                return ResourceManager.GetString("CantSaveNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel file Daticert.xml.
        /// </summary>
        internal static string ErrDatiCert {
            get {
                return ResourceManager.GetString("ErrDatiCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;inserimento delle notifiche..
        /// </summary>
        internal static string ErrInsNot {
            get {
                return ResourceManager.GetString("ErrInsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile scaricare una mail inoltrata.
        /// </summary>
        internal static string MailInoltrata {
            get {
                return ResourceManager.GetString("MailInoltrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ricevuta non viene salvata perche manca il riferimento al documento.
        /// </summary>
        internal static string RiferimentoAlDocumentoNonTrovato {
            get {
                return ResourceManager.GetString("RiferimentoAlDocumentoNonTrovato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errore nella ricerca del docnumer:  .
        /// </summary>
        internal static string XmlCantFindDocNumber {
            get {
                return ResourceManager.GetString("XmlCantFindDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mail viene sospesa perche&apos; il  file daticert.xml non e&apos; valido .
        /// </summary>
        internal static string XmlDatiCertInvalid {
            get {
                return ResourceManager.GetString("XmlDatiCertInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante la lettura del file daticert.
        /// </summary>
        internal static string XmlDatiCertReading {
            get {
                return ResourceManager.GetString("XmlDatiCertReading", resourceCulture);
            }
        }
    }
}
