--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Desktop\sp_itcoll\ADDNUOVAVERSIONE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\ADD_REGISTRO_IN_DPA_REG_FASC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\BLOCCA_DA_CONV_PDF.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CALCULATEATIPDELROLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CARICA_DOCUMENTI_RISERVATI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CARICA_DPA_REG_FASC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CARICA_FORMATO_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CARICA_TIPO_DOC_RIS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CLEAR_SECURITY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\COMPUTEATIPICITA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\COMPUTEATIPICITAINSROLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\COPYSECURITY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\COPYSECURITYWITHOUTATIPICI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\COUNT_UTENTI_LOGGATI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CREA_KEYS_AMMINISTRA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CREATEALLEGATO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CREATEDOCSP.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CREATE_NEW_NODO_TITOLARIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\CREATEPROJECTSP.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DELETEREGISTROREPERTORIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DEL_REC_DUPL_SECURITY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_DEL_UT_RUOLO_IN_MOD_TRASM.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_INS_TX_NEW_UT_RUOLO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_INS_UT_RUOLO_IN_MOD_TRASM.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_SETDIRITTORUOLOPROP.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_SETNUMFASC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA_UPD_TODOLIST_DOC_CESTINO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA3_GET_CHILDREN.sql
@C:\Users\Francesco\Desktop\sp_itcoll\DPA3_GET_HIERARCHY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\EXTENDVISIBILITYTOHIGHERROLES.sql
@C:\Users\Francesco\Desktop\sp_itcoll\HISTORICIZEROLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INITIALIZEROLEHISTORY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INITPEC3.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INITREGREPERTORIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INSERTDATAINHISTORYPROF.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INSERTREGISTROREPERTORIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INSERTREPERTORIOFROMCODE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\INS_OCC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_INSERTDATAINRECEIVEDMSG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_INSERTDATAINSIMPINTEROPLOG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_ISELEMENTINTEROPERABLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_LOADRECEIVEDPRIVATEFLAG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_LOADSETTINGS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_LOADSIMPINTEROPRECORDINFO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\I_SMISTAMENTO_DOCVISTO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\I_SMISTAMENTO_SETVISIBSUP.sql
@C:\Users\Francesco\Desktop\sp_itcoll\I_SMISTAMENTO_SMISTADOC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\I_SMISTAMENTO_SMISTADOC_R_2.sql
@C:\Users\Francesco\Desktop\sp_itcoll\I_SMISTAMENTO_SMISTADOC_U.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_SAVESETTINGS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\IS_SETIDPROFFORSIMPINTEROPMSG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\LIBERA_ACL_DOC_TRASMESSI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\MIGRA_TEMPLATE_TRASM.sql
@C:\Users\Francesco\Desktop\sp_itcoll\MOD_ANAGRAFICA_FUNZIONI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\OPTIMIZE_TEXT_INDEX.sql
@C:\Users\Francesco\Desktop\sp_itcoll\PUTFILE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\REMOVETRANSMODELVISIBILETOROLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\REORG_TEXT_INDEX.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SAVECOUNTERSETTINGS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SETDATAREG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SET_MEZZO_INTEROP_FOR_RC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SETRIGHTSFORROLE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SETSECURITYRUOLOREG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_CLEAN_DPA_T_CANALE_CORR.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DELETE_CORR_ESTERNO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DPA_COUNT_TODOLIST.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DPA_COUNT_TODOLIST_NO_REG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DPA_PR_DOCXSEDE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DPA_SETLARGETEXT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_DPA_UO_REG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_EREDITA_VIS_DOC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_EREDITA_VIS_DOC_ATIPICITA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_EREDITA_VIS_FASC.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_EREDITA_VIS_FASC_ATIPICITA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_FILL_DPA_UO_REG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_GET_RUOLO_RESP_UO_FROM_UO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_AUTHOR_IN_PROJECT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_DOCUMENTYPE_IN_PROFILE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_DPA_STATO_INVIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INSERT_AREA_CONS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INSERT_DOC_ARCHIVIO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INSERT_DPA_DETT_GLOBALI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INSERT_DPA_SUPPORTO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INSERT_ORDINAMENTO_ORG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_EXT_IN_COMPONENTS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_MODELLI_DEST_NOTIFICA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_RUOLO_CREATORE_PROJECT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_INS_UO_CREATORE_PROJECT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_MODIFY_CORR_ESTERNO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_MODIFY_CORR_ESTERNO_IS.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_MODIFY_CORR_ESTERNO_V1.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_MODIFY_UO_INTERNA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_RIMUOVI_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SPSETDATAVISTA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SPSETDATAVISTASMISTAMENTO.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SPSETDATAVISTA_TV.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SPSETDATAVISTA_V2.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_STORICIZZA_LOG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\SP_TRASM_RIF_TORNA_MITT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\TMP_DEBUGANNUALEDOCTABLEF.sql
@C:\Users\Francesco\Desktop\sp_itcoll\TMP_DOCUOTABLEFUNCTION.sql
@C:\Users\Francesco\Desktop\sp_itcoll\TMP_PRINT_DOCCLASSCOMPTABLEF.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UPDATE_CODLIV1.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UPDATE_MOD_DEST_CON_NOTIFICA.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_ADD_COLUMN.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_ADD_FOREIGN_KEY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_ADD_INDEX.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_ADD_PRIMARY_KEY.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_DROP_COLUMN.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_INSERT_CHIAVE_CONFIG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_INSERT_LOG.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_MODIFY_COLUMN.sql
@C:\Users\Francesco\Desktop\sp_itcoll\UTL_RENAME_COLUMN.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_DOC_ANOMALA_CUSTOM.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_DOC_ANOMALA_DOC_NUMBER.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_DOC_ANOMALA_INT_DATE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_FASC_ANOMALA_CUSTOM.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_FASC_ANOMALA_ID_PROJECT.sql
@C:\Users\Francesco\Desktop\sp_itcoll\VIS_FASC_ANOMALA_INT_DATE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\WRITE_DATE_IN_LOG_FILE.sql
@C:\Users\Francesco\Desktop\sp_itcoll\WRITE_STAT_IN_LOG_FILE.sql
