DECLARE
  @CODICE VARCHAR(100),
  @DESCRIZIONE VARCHAR(2000),
  @VALORE VARCHAR(128) ,
  @TIPO_CHIAVE Varchar(1),
  @VISIBILE VARCHAR(1),
  @MODIFICABILE VARCHAR(1) ,
  @GLOBALE VARCHAR(1),
  @MYVERSIONE_CD  Varchar(32),
  @CODICE_OLD_WEBCONFIG Varchar(128),
  @FORZA_UPDATE VARCHAR(1),
  @RFU  VARCHAR(10)
  

BEGIN
  set @CODICE = 'BE_ENABLE_REPORT_POLICY_PARER'
  set @DESCRIZIONE = 'Abilita l''invio del report di esecuzione delle policy per l''amministrazione'
  set @VALORE = '1'
  set @TIPO_CHIAVE = 'B'
  set @VISIBILE = '1'
  set @MODIFICABILE = '1'
  set @GLOBALE = '0'
  set @MYVERSIONE_CD = '3.2.7'
  set @CODICE_OLD_WEBCONFIG = NULL
  set @FORZA_UPDATE = '1'
  set @RFU = NULL
 
   exec DOCSADM.Utl_Insert_Chiave_Config @CODICE, @DESCRIZIONE, @VALORE, @TIPO_CHIAVE, @VISIBILE, @MODIFICABILE, @GLOBALE, @MYVERSIONE_CD, @CODICE_OLD_WEBCONFIG, @FORZA_UPDATE, @RFU
END