CREATE TABLE DPA_DESCRIZIONI_FASC
(
 SYSTEM_ID NUMBER NOT NULL, 
 VAR_DESCRIZIONE VARCHAR(2000 BYTE),
 VAR_CODICE VARCHAR(50 BYTE),
 ID_REGISTRO NUMBER,
 ID_AMM NUMBER
);

CREATE SEQUENCE SEQ_DPA_DESCRIZIONI_FASC INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCACHE;


ALTER TABLE DPA_MAIL_REGISTRI 
ADD (VAR_MESSAGE_SEND_MAIL VARCHAR2(2000) );

ALTER TABLE DPA_MAIL_REGISTRI 
ADD (CHA_OVERWRITE_MESSAGE_AMM CHAR(1) );

ALTER TABLE DPA_AMMINISTRA
ADD (CHA_ENABLE_CONS	VARCHAR2(1) );