--------------------------------------------------------
--  Constraints for Table DPA_CHIAVI_CONFIGURAZIONE
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" ADD CONSTRAINT "DPA_CHIAVI_CONFIGURAZIONE_C01" CHECK (nvl(cha_globale,1) + nvl(id_amm,1) > 0) ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("VAR_CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("VAR_VALORE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("CHA_VISIBILE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("CHA_MODIFICABILE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIGURAZIONE" MODIFY ("CHA_GLOBALE" NOT NULL ENABLE);
