--------------------------------------------------------
--  Ref Constraints for Table DPA_PROFIL_FASC_STO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD CONSTRAINT "FK_DP_PRF_FSC_ST_ID_OGG_CUSTOM" FOREIGN KEY ("ID_OGG_CUSTOM")
	  REFERENCES "ITCOLL_6GIU12"."DPA_OGGETTI_CUSTOM_FASC" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD CONSTRAINT "FK_DP_PRF_FSC_ST_ID_PEOPLE" FOREIGN KEY ("ID_PEOPLE")
	  REFERENCES "ITCOLL_6GIU12"."PEOPLE" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD CONSTRAINT "FK_DP_PRF_FSC_ST_ID_PROJECT" FOREIGN KEY ("ID_PROJECT")
	  REFERENCES "ITCOLL_6GIU12"."PROJECT" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD CONSTRAINT "FK_DP_PRF_FSC_ST_ID_RU_UO" FOREIGN KEY ("ID_RUOLO_IN_UO")
	  REFERENCES "ITCOLL_6GIU12"."DPA_CORR_GLOBALI" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD CONSTRAINT "FK_DP_PRF_FSC_ST_ID_TEMPLATE" FOREIGN KEY ("ID_TEMPLATE")
	  REFERENCES "ITCOLL_6GIU12"."DPA_TIPO_FASC" ("SYSTEM_ID") ENABLE NOVALIDATE;
