--------------------------------------------------------
--  Constraints for Table DPA_LDAP_SYNC_HISTORY
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_LDAP_SYNC_HISTORY" ADD CONSTRAINT "DPA_LDAP_SYNC_HISTORY_PK" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LDAP_SYNC_HISTORY" MODIFY ("ID_AMM" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LDAP_SYNC_HISTORY" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LDAP_SYNC_HISTORY" MODIFY ("SYNC_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LDAP_SYNC_HISTORY" MODIFY ("ITEMS_SYNCRONIZED" NOT NULL ENABLE);
