--------------------------------------------------------
--  Constraints for Table DPA_CORR_ABILITATI
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CORR_ABILITATI" ADD CONSTRAINT "DPA_CORR_ABILITATI_PK" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CORR_ABILITATI" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CORR_ABILITATI" MODIFY ("ID_CORR_GLOBALE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CORR_ABILITATI" MODIFY ("CHA_TIPO_URP" NOT NULL ENABLE);
