--------------------------------------------------------
--  Constraints for Table DPA_CLIENT_MODEL_PROCESSORS
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CLIENT_MODEL_PROCESSORS" ADD CONSTRAINT "DPA_CLIENT_MODEL_PROCESSORS_PK" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CLIENT_MODEL_PROCESSORS" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CLIENT_MODEL_PROCESSORS" MODIFY ("CLASS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CLIENT_MODEL_PROCESSORS" MODIFY ("SUPPORTED_EXTENSIONS" NOT NULL ENABLE);
