--------------------------------------------------------
--  Constraints for Table DPA_LETTERE_DOCUMENTI
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_LETTERE_DOCUMENTI" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LETTERE_DOCUMENTI" MODIFY ("CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LETTERE_DOCUMENTI" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LETTERE_DOCUMENTI" MODIFY ("ETICHETTA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LETTERE_DOCUMENTI" ADD PRIMARY KEY ("SYSTEM_ID") ENABLE;
