--------------------------------------------------------
--  Constraints for Table DPA_MODELLI_DELEGA
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" ADD CONSTRAINT "DPA_MODELLI_DELEGA_PK" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" MODIFY ("ID_PEOPLE_DELEGANTE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" MODIFY ("ID_PEOPLE_DELEGATO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" MODIFY ("ID_RUOLO_DELEGATO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_MODELLI_DELEGA" MODIFY ("NOME" NOT NULL ENABLE);
