--------------------------------------------------------
--  Constraints for Table DPA_LOG_STORICO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("ID_PEOPLE_OPERATORE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("DTA_AZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("VAR_OGGETTO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("VAR_COD_AZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("VAR_DESC_AZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_STORICO" MODIFY ("CHA_ESITO" NOT NULL ENABLE);
