--------------------------------------------------------
--  Constraints for Table DPA_LOG_INSTALL
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_INSTALL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_INSTALL" MODIFY ("DATA_OPERAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_INSTALL" MODIFY ("COMANDO_RICHIESTO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_INSTALL" MODIFY ("VERSIONE_CD" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_LOG_INSTALL" MODIFY ("ESITO_OPERAZIONE" NOT NULL ENABLE);
