--------------------------------------------------------
--  Constraints for Table DPA_ROLE_HISTORY
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ORIGINAL_CORR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ACTION" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ROLE_DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ROLE_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ACTION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("UO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ROLE_HISTORY" MODIFY ("ROLE_ID" NOT NULL ENABLE);
