--------------------------------------------------------
--  Constraints for Table DPA_FORMATI_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" ADD CONSTRAINT "PK_DPA_FORMATI_DOCUMENTO" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("FILE_TYPE_USED" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("FILE_EXTENSION" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("MAX_FILE_SIZE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("MAX_FILE_SIZE_ALERT_MODE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("CONTAINS_FILE_MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_FORMATI_DOCUMENTO" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);
