--------------------------------------------------------
--  Ref Constraints for Table DPA_TRASM_SINGOLA
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_TRASM_SINGOLA" ADD CONSTRAINT "FK_DPA_TRASM_SINGOLA_R01" FOREIGN KEY ("ID_TRASMISSIONE")
	  REFERENCES "ITCOLL_6GIU12"."DPA_TRASMISSIONE" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TRASM_SINGOLA" ADD CONSTRAINT "FK_DPA_TRASM_SINGOLA_R02" FOREIGN KEY ("ID_RAGIONE")
	  REFERENCES "ITCOLL_6GIU12"."DPA_RAGIONE_TRASM" ("SYSTEM_ID") ENABLE NOVALIDATE;
