--------------------------------------------------------
--  Constraints for Table DPA_CHIAVI_CONFIG_TEMPLATE
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" ADD CONSTRAINT "DPA_CHIAVI_CONFIG_TEMPLATE_PK" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" ADD CONSTRAINT "DPA_CHIAVI_CONFIG_TEMPLATE_U01" UNIQUE ("VAR_CODICE") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" MODIFY ("VAR_CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" MODIFY ("VAR_VALORE" NOT NULL ENABLE);
