--------------------------------------------------------
--  Constraints for Table DPA_REGISTRI_REPERTORIO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" MODIFY ("TIPOLOGYID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" MODIFY ("COUNTERID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" MODIFY ("COUNTERSTATE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" MODIFY ("PRINTFREQ" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" MODIFY ("TIPOLOGYKIND" NOT NULL ENABLE);
