--------------------------------------------------------
--  Constraints for Table DPA_COLL_MSPEDIZ_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_COLL_MSPEDIZ_DOCUMENTO" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_COLL_MSPEDIZ_DOCUMENTO" MODIFY ("IDAMM" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_COLL_MSPEDIZ_DOCUMENTO" MODIFY ("ID_DOCUMENTTYPES" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_COLL_MSPEDIZ_DOCUMENTO" MODIFY ("ID_PROFILE" NOT NULL ENABLE);
