--------------------------------------------------------
--  Constraints for Table DR$INDX_OGG_TEXT$I
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" MODIFY ("TOKEN_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" MODIFY ("TOKEN_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" MODIFY ("TOKEN_FIRST" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" MODIFY ("TOKEN_LAST" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DR$INDX_OGG_TEXT$I" MODIFY ("TOKEN_COUNT" NOT NULL ENABLE);
