--------------------------------------------------------
--  Constraints for Table PUBLISHER_INSTANCES
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" ADD CONSTRAINT "PUBLISHER_INSTANCES_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" MODIFY ("SUBSCRIBERSERVICEURL" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" MODIFY ("PUBLISHEDOBJECTS" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" MODIFY ("EXECUTIONTYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."PUBLISHER_INSTANCES" MODIFY ("EXECUTIONTICKS" NOT NULL ENABLE);
