--------------------------------------------------------
--  Constraints for Table SUBSCRIBER_HISTORY
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_HISTORY" ADD CONSTRAINT "PUBLISH_HISTORY_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_HISTORY" MODIFY ("IDOBJECT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_HISTORY" MODIFY ("COMPUTED" NOT NULL ENABLE);
