--------------------------------------------------------
--  Constraints for Table UTL_SYSTEM_LOG
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."UTL_SYSTEM_LOG" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTL_SYSTEM_LOG" MODIFY ("DATA_OPERAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTL_SYSTEM_LOG" MODIFY ("COMANDO_RICHIESTO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTL_SYSTEM_LOG" MODIFY ("CATEGORIA_COMANDO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTL_SYSTEM_LOG" MODIFY ("ESITO_OPERAZIONE" NOT NULL ENABLE);
