
ALTER TABLE DPA_ANAGRAFICA_EVENTI 
ADD (CHA_AUTOMATICO CHAR(1) );

UPDATE DPA_ANAGRAFICA_EVENTI SET CHA_AUTOMATICO = '1' WHERE VAR_COD_AZIONE IN ('DOCUMENTO_REPERTORIATO','RECORD_PREDISPOSED','DOCUMENTOSPEDISCI');

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (CHA_AUTOMATICO CHAR(1) );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (ID_AOO NUMBER );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (ID_RF NUMBER );

ALTER TABLE DPA_PASSO_DI_FIRMA 
ADD (ID_MAIL_REGISTRO NUMBER );

ALTER TABLE DPA_ISTANZA_PROCESSO_FIRMA 
ADD (NOTIFICA_ERRORE CHAR(1));

ALTER TABLE DPA_ISTANZA_PROCESSO_FIRMA 
ADD (NOTIFICA_DEST_NON_INTEROP CHAR(1));

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (CHA_AUTOMATICO CHAR(1) );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (ID_AOO NUMBER );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (ID_RF NUMBER );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (ID_MAIL_REGISTRO NUMBER );

ALTER TABLE DPA_ISTANZA_PASSO_FIRMA 
ADD (VAR_ERRORE CLOB );

ALTER TABLE PEOPLE 
ADD (CHA_AUTOMATICO CHAR(1));

ALTER TABLE DPA_PROCESSO_FIRMA_VISIBILITA
ADD (CHA_TIPO_VISIBILITA CHAR(1));

UPDATE DPA_PROCESSO_FIRMA_VISIBILITA SET CHA_TIPO_VISIBILITA = 'P';

--MELINI
ALTER TABLE DPA_POLICY_PARER ADD NUM_GIORNI_FIRMA INTEGER;


CREATE TABLE DPA_INFO_FIRMA_DIGITALE
(
SYSTEM_ID                                                                  NUMBER NOT NULL,
ID_PROFILE                                                                 NUMBER,
VERSION_ID                                                                NUMBER,
DATA_APPOSIZIONE                                   DATE
);