CREATE OR REPLACE
FUNCTION CONVERTTONUMBER (P_STRING IN VARCHAR2)
RETURN INT
IS
   V_NEW_NUM INT;
BEGIN
    BEGIN
         V_NEW_NUM := TO_NUMBER(NVL(p_string, '0'));
      EXCEPTION
      WHEN OTHERS THEN
         V_NEW_NUM := 0;
      END;
    RETURN V_NEW_NUM;
END CONVERTTONUMBER;
    