<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocsPaDB\DocsPaDB.csproj" />
    <ProjectReference Include="..\DocsPaDocumentale_Interfaces\DocsPaDocumentale_Interfaces.csproj" />
    <ProjectReference Include="..\DocsPaLdapServices\DocsPaLdapServices.csproj" />
    <ProjectReference Include="..\DocsPaPwdServices\DocsPaPwdServices.csproj" />
  </ItemGroup>
</Project>