<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DocsPaVO</AssemblyName>
    <RootNamespace>DocsPaVO</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="addressbook\DettagliCorrispondente.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DettagliCorrispondente.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="addressbook\DettagliCorrispondente.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DettagliCorrispondente.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>