--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_PASSI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE_TIME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DTA_EME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_OGGETTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE12.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_DELEGHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TIPOFUNRUOLO2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_ULTIMO_DOC_SCARICATO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_CONV_PDF_SERVER.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_TODOLIST_PEOPLE_DEST.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASSOCIAZIONE_TEMPLATES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_AREA_CONS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_ELEMENTIRUBRICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_VAR_PROF_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE13.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\U_SALVARIC_NOME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ANAFUNZ1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DEL_SEC5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORR_GLOB_TIPO_CORR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_INDX_SIS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DOCARRPAR3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_SEC6.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_VERSIONS2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMSING4.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_SEC5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE9.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_RUOLOREG1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CONS_VERIFICA_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PEOPLEGROUP2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_OGG_CUSTOM_COMP_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ10.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDEX_MV_PROSPETTI_DOCGRIGI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ASS_TEMPL_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORR_GLOB_TIPO_IE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMSING1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\EMAIL_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_OGG_TEXT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ8.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DOCARRPAR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_POSIZ_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_SALVA_RICERCHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_A_R_OGG_CUSTOM_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB9.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_ASS_GRIDS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IDX_PEOPLE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_CHECKIN_CHECKOUT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ_UNIQUE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_PEOPLE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CHIAVI_CONFIG_TEMPLATE_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROTO_EME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_UTENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ9.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IND_NOTIFICA_K3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CLIENT_MODEL_PROCESSORS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMSING2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_A_R_DOC1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_FORMATI_DOCUMENTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_DIAGRAMMI_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_AREALAV.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASS_TEMPLATES_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_MODELLI_DEST_CON_NOTIFI_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE8.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DR$INDX_DESC_CORR_TEXT$X.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ASS_TEMPL1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IDX_PGU_ENTI_NOME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_DIAGRAMMI_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_VIS_TIPO_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_VAR_DESC_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\NETWORK_ALIASESU.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB8.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CHA_APPLICAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_VAR_CODICE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_LDAP_SYNC_HISTORY_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_ASSOCIAZIONE_TEMPL_INDX01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PGU_ENTI_UTENTI_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DTA_ULTIMO_SCARICO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_VAR_COD_RUBRICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TIPO_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TIMESTAMP_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_RUOLO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PEOPLE_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJECTCOMP1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_CARAT_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\UIPROF.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE_DATA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_LO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_TIPO_SUPPORTO_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_UT_NOME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_VOCI_MENU_ADMIN_U01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ELENCO_NOTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CHIAVI_CONFIG_TEMPLATE_U01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ11.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_TESTO_NOTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_COMP2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASSOCIAZIONE_VALORI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DOCTYPESCU.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMUTE1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ6.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_COLORE_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DR$INDX_OGG_TEXT$X.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISH_INSTANCES_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_UTENTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_COMP1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DETTGLOB2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_VAR_SEGN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\GROUPS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISHER_EVENTS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ7.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE4.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\UPPER_APPL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CORR_ABILITATI_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_PGU_UTENTI_NAME.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROF_PAROLE1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_CHIAVI_CONFIG_IDX.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IDX_DPA_DOC_ARRIVO_PAR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISH_ERRORS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_PARENT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_VIS_TIPO_FASC_R01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMSING3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASS_VALORI_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_OGG_CUSTOM_COMP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_VERSIONS3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TESTO_NOTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PEOPLE3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPASTATOINVIO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASS_INDX_SIS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_VOCI_MENU_ADMIN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASMUTE2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DTA_CREAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FASC_CARTACEA_PROJ_VERS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CANALECORR1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISH_RULES_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DESC_CORR_TEXT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_COPY_LOG_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_ER_IDUTENTECREATORE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_OGGETTI_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE6.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TRASM_DIAGR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_GRIDS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TIPOFUNRUOLO1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE7.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\REMOTE_LIBSCU.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ITEMS_CONS_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE11.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE10.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_RISCONTRI_CLASSIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DOCARRPAR2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TIPODOC_DS_TEMPL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_VERSIONS1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FASC_CARTACEA_VERS_ID.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_UPPER_VAR_DESC_CORR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TIPO_OGGETTO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_OGG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PGU_UTENTI_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_VIS_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISH_HISTORY_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_ER_CODICE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_FRIEND_APPLICATION.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_SEC_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\GROUPSCU.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_A_R_FASC1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORR_TIPOURP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_ASS_RUOLO_OGG_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJECTCOMP2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IDX_DPA_OGGETTARIO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_OGG2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_DIAGRAMMI_STATO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE_DOC_PRINC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PUBLISHER_INSTANCES_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_STATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_A_R_OGG_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM6.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PK_DPA_PROTO_TIT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJECT_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROFILE2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_RUOLOREG2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FASC_CARTACEA_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FUNZ1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ4.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TS_STAMPA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_DPA_LDAP_CONFIG_ID_AMM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_MODELLI_DELEGA_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_ASS_TEMPL_FASC_INDX01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_LO2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_STAMPA1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\COD_RUBRICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM4.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PROJ5.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PEOPLE2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_TRASM_UTENTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_REG_FASC1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FASC_CARTACEA_ID_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\IX_ER_DESCRIZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DEL_SEQ_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_PEOPLEGROUP1.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_ID_CORR_GLOBALE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_SUPPORTO_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB3.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_AREALAV2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\PGU_ENTI_PK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_CORRGLOB6.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DPA_ASS_RUOLO_OGG_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_FASC_CARTACEA_PROJ_ID.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\DPA_VIS_TIPO_DOC_U01.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Indici_ITCOLL\INDX_DEL_SEC6.sql
