--------------------------------------------------------
--  File creato - mercoledì-giugno-06-2012   
--------------------------------------------------------
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\AMMINISTRAZIONI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\APPS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\COMPONENTS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DELETED_SECURITY.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DETT_DOPPI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DOCS_UNIQUE_KEYS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DOCUMENTTYPES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_AMMINISTRA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ANAGRAFICA_FUNZIONI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ANAGRAFICA_LOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_AREA_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_AREA_LAVORO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_A_R_OGG_CUSTOM_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_A_R_OGG_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_DIAGRAMMI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_DOC_MAIL_INTEROP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_GRIDS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_INDX_SIS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_LETTERE_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASSOCIAZIONE_TEMPLATES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASSOCIAZIONE_VALORI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_POLICY_PROFILAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_POLICY_TYPE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_RUOLO_OGG_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_TEMPLATES_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ASS_VALORI_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CACHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CANALI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CANALI_REG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CARAT_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CHECKIN_CHECKOUT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CHIAVI_CONF_BKP20110909.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CHIAVI_CONFIG_TEMPLATE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CHIAVI_CONFIGURAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CLIENT_MODEL_PROCESSORS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_COLL_MSPEDIZ_DOCUMENTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_COLORE_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONFIG_ANAGRAFICA_ESTERNA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONFIG_CACHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONSOLIDATED_DOCS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONS_VERIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONTATORI_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONTATORI_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CONV_PDF_SERVER.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_COPY_LOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CORR_ABILITATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CORR_GLOBALI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CORR_GLO_X_INT_TIPI_RUO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CORR_GRUPPO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_CORR_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_COUNT_TODOLIST.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DATA_ARRIVO_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DATI_SCARICATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DELEGHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DETT_GLOBALI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DETT_POLICY_ESECUZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DIAGRAMMI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DIAGRAMMI_STATO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DIAGRAMMI_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DISPOSITIVI_STAMPA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DISSERVIZI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DOC_AR_PAR_AP_S112.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DOC_ARRIVO_PAR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DOC_COLLEGAMENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_DOCSPA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ELENCO_NOTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_EL_REGISTRI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FASCICOLAZIONE_CARTACEA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FIRMATARI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FIRMA_VERS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FORMATI_DOCUMENTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FORMATTA_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FORMATTA_SEGN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FRIEND_APPLICATION.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FUNZIONI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_FUNZIONI_20120309.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_GRIDS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_INDX_SIS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ITEMS_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_L_AOO_UO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LDAP_CONFIG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LDAP_SYNC_HISTORY.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LEGISLATURE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LETTERE_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LISTE_DISTR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOCK.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOG_ATTIVATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOGIN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOG_INSTALL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_LOG_STORICO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_L_RUOLO_REG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MAIL_CORR_ESTERNI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MAIL_ELABORATE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MAIL_REGISTRI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MODELLI_DELEGA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MODELLI_DEST_CON_NOTIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MODELLI_MITT_DEST.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_MODELLI_TRASM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_NOTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_NOTIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OBJECTS_SYNC_PENDING.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGG_CUSTOM_COMP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGG_CUSTOM_COMP_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGGETTARIO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGGETTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGGETTI_CUSTOM_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_OGGETTI_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PAROLE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PASSI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PEOPLEGROUPS_QUALIFICHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_POLICY_ESECUZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_POSIZ_TIMBRO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PR_DOCXSEDE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PROFIL_FASC_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PROFIL_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PROF_PAROLE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_PROTO_TIT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_QUALIFICA_CORRISPONDENTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_QUALIFICHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_RAGIONE_TRASM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_REG_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_REGISTRI_REPERTORIO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_REGISTRO_STO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_REG_PROTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_RISCONTRI_CLASSIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_ROLE_HISTORY.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_RUOE_UTENTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_SALVA_RICERCHE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_SERVER_POSTA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_STAMPAREGISTRI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_STAMPA_REPERTORI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_STATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_STATO_INVIO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_SUPPORTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_T_CANALE_CORR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TEMPLATES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TEMPL_TRASM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_THEMES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIMESTAMP_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_ATTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_F_RUOLO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_FUNZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_FUNZIONE_20120309.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_NOTIFICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_OGGETTO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_RUOLO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TIPO_SUPPORTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TODOLIST.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TRASM_DIAGR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TRASMISSIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TRASM_SINGOLA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_TRASM_UTENTE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_UO_REG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_UO_SMISTAMENTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_USERADMIN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_USERADMIN_REGISTRI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_USERADMIN_VOCI_MENU.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_VIS_ANOMALA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_VIS_MAIL_REGISTRI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_VIS_TIPO_DOC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_VIS_TIPO_FASC.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DPA_VOCI_MENU_ADMIN.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_DESC_CORR_TEXT$I.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_DESC_CORR_TEXT$K.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_DESC_CORR_TEXT$N.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_DESC_CORR_TEXT$R.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_OGG_TEXT$I.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_OGG_TEXT$K.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_OGG_TEXT$N.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\DR$INDX_OGG_TEXT$R.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\ELEMENTIRUBRICA.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\EMAILS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\GROUPS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\INTEROPERABILITYSETTINGS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_ASSOCIAZIONE_TEM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_CORR_GLOBALI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_DOC_ARRIVO_PAR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_OGG_CUSTOM_COMP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_OGGETTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_TIPO_ATTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MLOG$_DPA_TIPO_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_DOCUMENTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCCLASS_ALL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCCLASSCOMP_ALL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCGRIGI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCGRIGICLASS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCUMENTICLASS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\MV_PROSPETTI_DOCUMENTICLASSUO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NETWORK_ALIASES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONCHANNEL.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONINSTANCE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONINSTANCECHANNELS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONITEM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONITEMCATEGORIES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\NOTIFICATIONUSER.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\OUTPUT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PEOPLE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PEOPLEGROUPS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PGU_ENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PGU_ENTI_UTENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PGU_UTENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\POLICY_CONSERVAZIONE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PROFILE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PROJECT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PROJECT_APPO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PROJECT_COMPONENTS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PROJECT2.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PUBBLICAZIONI_DOCUMENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PUBLISHER_ERRORS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PUBLISHER_EVENTS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\PUBLISHER_INSTANCES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\REMOTE_LIBRARIES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_ASSOCIAZIONE_TEM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_CORR_GLOBALI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_DOC_ARRIVO_PAR.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_OGG_CUSTOM_COMP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_OGGETTI_CUSTOM.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_TIPO_ATTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\RUPD$_DPA_TIPO_OGGETTO.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SEC_LOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SECURITY.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SIMPINTEROPDBLOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SIMPINTEROPRECEIVEDMESSAGE.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SUBSCRIBER_HISTORY.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SUBSCRIBER_INSTANCES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\SUBSCRIBER_RULES.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\TEMP_LOG_JOBS.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\TMP_LOG_REPORT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\TMP_PRJ.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\TMP_SECURITY_PREV.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\UTENTI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\UTENTI_LOGGATI.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\UTL_OUTPUT.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\UTL_SYSTEM_LOG.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\UTL_TRACK_AOORUOLORESP.sql
@C:\Users\Francesco\Desktop\ORACLE_ITCOLL\Tabelle_ITCOLL_DEF\VERSIONS.sql
