
-- =============================================
-- Author:		FRANCESCO FONZO
-- Create date: 21/02/2013
-- Description:	CONVERSIONE DA ORACLE A SQL SERVER
--				CREAZIONE NUOVA TABELLA DPA_ASS_RUOLO_STATI_DIAGRAMMA 		
-- =============================================

DECLARE @CNT INT
  
SET @CNT = (SELECT COUNT(*) FROM SYS.tables WHERE name = 'DPA_ASS_RUOLO_STATI_DIAGRAMMA')    
  
IF (@CNT = 0)
BEGIN
	CREATE TABLE [DOCSADM].[DPA_ASS_RUOLO_STATI_DIAGRAMMA]
	(
		[SYSTEM_ID]				INT		IDENTITY(1,1)	NOT NULL,
		[ID_GRUPPO]				INT						NOT NULL,
		[ID_DIAGRAMMA]			INT						NOT NULL,
		[ID_STATO]				INT						NOT NULL,
		[CHA_NOT_VIS]			VARCHAR(1)				NOT NULL,
		
				
		PRIMARY KEY CLUSTERED 
		(
			[SYSTEM_ID] ASC
		)
		WITH 
		(
			PAD_INDEX  = OFF
			, STATISTICS_NORECOMPUTE  = OFF
			, IGNORE_DUP_KEY = OFF
			, ALLOW_ROW_LOCKS  = ON
			, ALLOW_PAGE_LOCKS  = ON
		) ON [PRIMARY]
	) ON [PRIMARY]
	
	
	ALTER TABLE [DOCSADM].[DPA_ASS_RUOLO_STATI_DIAGRAMMA] ADD  DEFAULT ('1') FOR [CHA_NOT_VIS]

END 


