<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.Queries" Version="4.8.0-beta00016" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00016" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.11.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doc.Application.Search.DocumentoAmministrativo\Doc.Application.Search.DocumentoAmministrativo.csproj" />
    <ProjectReference Include="..\pi3.Core.Contracts\pi3.Core.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ErrorDescriptions.Designer.cs">
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="ErrorDescriptions.resx">
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>