DROP TABLE DPA_HSMPARAMETERS;

CREATE TABLE DPA_HSMPARAMETERS
(
  ID_AMM NUMBER(10) NOT NULL,
  DOMINIO VARCHAR2(250 BYTE) NOT NULL,
  TSAURL VARCHAR2(1000 BYTE),
  TSAUSER VARCHAR2(250 BYTE),
  TSAPASSWORD VARCHAR2(250 BYTE),
  USERAPPLICATIVA VARCHAR2(250 BYTE) NOT NULL,
  PASSWORDAPPLICATIVA VARCHAR2(250 BYTE) NOT NULL,
  SERVERURL VARCHAR2(1000 BYTE) NOT NULL
)
TABLESPACE PITRE_INFOTN_DATA_COLL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;