DECLARE 
  CODICE VARCHAR2(32767);
  DESCRIZIONE VARCHAR2(32767);
  VALORE VARCHAR2(32767);
  TIPO_CHIAVE VARCHAR2(32767);
  VISIBILE VARCHAR2(32767);
  MODIFICABILE VARCHAR2(32767);
  GLOBALE VARCHAR2(32767);
  MYVERSIONE_CD VARCHAR2(32767);
  CODICE_OLD_WEBCONFIG VARCHAR2(32767);
  FORZA_UPDATE VARCHAR2(32767);
  RFU VARCHAR2(32767);

BEGIN 
  CODICE := 'BE_PROJECT_STRUCTURE';
  DESCRIZIONE := 'Gestione dei template della struttura';
  VALORE := '1';
  TIPO_CHIAVE := 'B';
  VISIBILE := '1';
  MODIFICABILE := '1';
  GLOBALE := '1';
  MYVERSIONE_CD := ' ';
  CODICE_OLD_WEBCONFIG := '';
  FORZA_UPDATE := '';
  RFU := '';

  SVILUPPO_PITRE.UTL_INSERT_CHIAVE_CONFIG ( CODICE, DESCRIZIONE, VALORE, TIPO_CHIAVE, VISIBILE, MODIFICABILE, GLOBALE, MYVERSIONE_CD, CODICE_OLD_WEBCONFIG, FORZA_UPDATE, RFU );
  COMMIT; 
END; 
