SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


if exists (select * from dbo.sysobjects where id = object_id(N'[docsadm].[Del_Rec_Dupl_In_Security]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [docsadm].[Del_Rec_Dupl_In_Security]
GO

CREATE  PROCEDURE Del_Rec_Dupl_In_Security AS

/*
--------------------------------------------------------
Ripulisce la tabella SECURITY dei record duplicati
--------------------------------------------------------
*/

DECLARE @fc_THING int
DECLARE @fc_PERSONORGROUP int
DECLARE @fc_ACCESSRIGHTS int
DECLARE @fc_COUNT int

DECLARE @f_THING int
DECLARE @f_PERSONORGROUP int
DECLARE @f_ACCESSRIGHTS int
DECLARE @f_ID_GRUPPO_TRASM int
DECLARE @f_CHA_TIPO_DIRITTO nvarchar(1)

BEGIN
	DECLARE cursor_A
	CURSOR LOCAL FOR
		SELECT DISTINCT
		   THING,PERSONORGROUP,ACCESSRIGHTS,COUNT(*)
		FROM SECURITY		
		GROUP BY THING,PERSONORGROUP,ACCESSRIGHTS		
		HAVING COUNT(*) > 1
		
	OPEN cursor_A
	
	FETCH NEXT FROM cursor_A
	INTO 	@fc_THING,@fc_PERSONORGROUP,@fc_ACCESSRIGHTS,@fc_COUNT 
	
	WHILE @@FETCH_STATUS = 0
		BEGIN						 		
			SELECT TOP 1 
				@f_THING = THING, 
				@f_PERSONORGROUP = PERSONORGROUP, 
				@f_ACCESSRIGHTS = ACCESSRIGHTS, 
				@f_ID_GRUPPO_TRASM = ID_GRUPPO_TRASM, 
				@f_CHA_TIPO_DIRITTO = CHA_TIPO_DIRITTO
			FROM 
				SECURITY
			WHERE 
				thing = @fc_THING
				AND PERSONORGROUP = @fc_PERSONORGROUP
				AND ACCESSRIGHTS = @fc_ACCESSRIGHTS
			ORDER BY ACCESSRIGHTS DESC, CHA_TIPO_DIRITTO DESC
			
							
			BEGIN TRANSACTION

			-- ELIMINA TUTTI I RECORD
			DELETE FROM SECURITY
			WHERE THING = @fc_THING AND PERSONORGROUP = @fc_PERSONORGROUP

			-- QUINDI INSERISCE IL RECORD MEMORIZZATO PRIMA
			INSERT INTO SECURITY
				(THING, PERSONORGROUP, ACCESSRIGHTS, ID_GRUPPO_TRASM, CHA_TIPO_DIRITTO)
			VALUES
				(@f_THING,@f_PERSONORGROUP,@f_ACCESSRIGHTS,@f_ID_GRUPPO_TRASM,@f_CHA_TIPO_DIRITTO)
			
			IF(@@ERROR <> 0)
				ROLLBACK
			ELSE
				COMMIT
														

			-- Posizionamento sul record successivo del cursore
			FETCH NEXT FROM cursor_A
			INTO 	@fc_THING,@fc_PERSONORGROUP,@fc_ACCESSRIGHTS,@fc_COUNT								
		END
	
	-- Chiusura e deallocazione cursore	
	CLOSE cursor_A
	DEALLOCATE cursor_A

	RETURN 0
END

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
