BEGIN
    ALTER TABLE    DPA_TIPO_ATTO
    ADD CHA_INVIO_CONSERVAZIONE varchar(1)
    ALTER TABLE
    DPA_OGGETTI_CUSTOM
    ADD CHA_CONSOLIDAMENTO varchar(1)
    ALTER TABLE
    DPA_OGGETTI_CUSTOM
    ADD CHA_CONSERVAZIONE varchar(1)
    
    ALTER TABLE
    DPA_OGGETTI_CUSTOM
    ADD CHA_CONS_REPERTORIO varchar(1)
    
    COMMIT;
END;