/*
Script per l'inserimento della chiave di DB 'BE_INTEROP_CAMBIA_TIPO_MITT'
*/

  DECLARE 
  CODICE VARCHAR2(200);
  DESCRIZIONE VARCHAR2(200);
  VALORE VARCHAR2(200);
  TIPO_CHIAVE VARCHAR2(200);
  VISIBILE VARCHAR2(200);
  MODIFICABILE VARCHAR2(200);
  GLOBALE VARCHAR2(200);
  MYVERSIONE_CD VARCHAR2(200);
  CODICE_OLD_WEBCONFIG VARCHAR2(200);
  FORZA_UPDATE VARCHAR2(200);
  RFU VARCHAR2(200);

BEGIN 
  CODICE := 'BE_INTEROP_CAMBIA_TIPO_MITT';
  DESCRIZIONE := 'Cambia il tipo di Mittente se Codice Amministrazione della segnatura è lo stesso del registro in fase di scarico casella';
  VALORE := 'true';
  TIPO_CHIAVE := 'B';
  VISIBILE := '1';
  MODIFICABILE := '1';
  GLOBALE := '0';
  MYVERSIONE_CD := '3.30.0';
  CODICE_OLD_WEBCONFIG := NULL;
  FORZA_UPDATE := '1';
  RFU := NULL;

  UTL_INSERT_CHIAVE_CONFIG ( CODICE, DESCRIZIONE, VALORE, TIPO_CHIAVE, VISIBILE, MODIFICABILE, GLOBALE, MYVERSIONE_CD, CODICE_OLD_WEBCONFIG, FORZA_UPDATE, RFU );
  COMMIT; 
END; 