<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.3.46</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ChilkatDnCore" Version="9.50.99" />
    <ProjectReference Include="..\..\..\core\pi3.core\Pi3.Core\Pi3.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\BoxScanner\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\BoxScanner\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\Email\Sender\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Services\File\PAdES\ErrorDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDescriptions.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\BoxScanner\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\BoxScanner\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\Email\Sender\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Services\File\PAdES\ErrorDescriptions.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>