--------------------------------------------------------
--  DDL for Trigger TR_UPDATE_DPA_TODOLIST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ITCOLL_6GIU12"."TR_UPDATE_DPA_TODOLIST" 
AFTER UPDATE
OF CHA_IN_TODOLIST
ON DPA_TRASM_UTENTE REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
if( :NEW.CHA_IN_TODOLIST='0')
THEN
DELETE /*+ ALL_ROWS */ DPA_TODOLIST WHERE ID_TRASM_UTENTE = :NEW.SYSTEM_ID;
END IF;
END; 
/
ALTER TRIGGER "ITCOLL_6GIU12"."TR_UPDATE_DPA_TODOLIST" ENABLE;
