-- STAMPE REGISTRI DI PROTOCOLLO
INSERT INTO DPA_VERSAMENTO
(SYSTEM_ID,ID_PROFILE,ID_PEOPLE,ID_RUOLO,CHA_STATO,DTA_INVIO,ID_AMM,VAR_FILE_METADATI,VAR_FILE_RISPOSTA)
SELECT
SEQ_DPA_VERSAMENTO.NEXTVAL,
P.DOCNUMBER,
(SELECT ID_UTENTE_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=R.ID_AMM),
(SELECT ID_RUOLO_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=R.ID_AMM),
'V',
SYSDATE,
R.ID_AMM,
empty_clob(),
empty_clob()
FROM PROFILE P, DPA_EL_REGISTRI R
WHERE P.CHA_TIPO_PROTO IN ('R')
AND P.ID_REGISTRO=R.SYSTEM_ID
--AND TO_DATE(TO_CHAR(P.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') = TO_DATE(TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 'DD/MM/YYYY')
AND P.CREATION_TIME BETWEEN (TRUNC(SYSDATE-1)+1/12) AND (TRUNC(SYSDATE)+1/12-1/86400)
AND R.ID_AMM IN (SELECT SYSTEM_ID FROM DPA_AMMINISTRA);

INSERT INTO SECURITY
(THING, PERSONORGROUP, ACCESSRIGHTS, CHA_TIPO_DIRITTO, TS_INSERIMENTO)
SELECT
P.DOCNUMBER,
(SELECT ID_RUOLO_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=R.ID_AMM),
'63', 'C', SYSTIMESTAMP
FROM PROFILE P, DPA_EL_REGISTRI R
WHERE P.CHA_TIPO_PROTO IN ('R') 
AND P.ID_REGISTRO=R.SYSTEM_ID
--AND TO_DATE(TO_CHAR(P.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') = TO_DATE(TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 'DD/MM/YYYY')
AND P.CREATION_TIME BETWEEN (TRUNC(SYSDATE-1)+1/12) AND (TRUNC(SYSDATE)+1/12-1/86400)
AND R.ID_AMM IN (SELECT SYSTEM_ID FROM DPA_AMMINISTRA);



-- STAMPE REGISTRI DI REPERTORIO
-- Seleziono solo le stampe dei repertori configurati per la conservazione
INSERT INTO DPA_VERSAMENTO
(SYSTEM_ID,ID_PROFILE,ID_PEOPLE,ID_RUOLO,CHA_STATO,DTA_INVIO,ID_AMM, VAR_FILE_METADATI, VAR_FILE_RISPOSTA)
SELECT
SEQ_DPA_VERSAMENTO.NEXTVAL,
P.DOCNUMBER,
(SELECT ID_UTENTE_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=T.ID_AMM),
(SELECT ID_RUOLO_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=T.ID_AMM),
'V',
SYSDATE,
T.ID_AMM,
empty_clob(),
empty_clob()
FROM PROFILE P, DPA_TIPO_ATTO T, DPA_REGISTRI_REPERTORIO R, DPA_STAMPA_REPERTORI S, DPA_OGGETTI_CUSTOM O
WHERE P.CHA_TIPO_PROTO IN ('C') 
AND P.DOCNUMBER=S.DOCNUMBER AND S.ID_REPERTORIO=R.COUNTERID AND T.SYSTEM_ID=R.TIPOLOGYID
AND (((S.REGISTRYID=R.REGISTRYID AND R.RFID IS NULL) OR (S.REGISTRYID=R.RFID AND R.REGISTRYID IS NULL)) OR (S.REGISTRYID IS NULL))
--AND TO_DATE(TO_CHAR(P.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') = TO_DATE(TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 'DD/MM/YYYY')
AND P.CREATION_TIME BETWEEN (TRUNC(SYSDATE-1)+1/12) AND (TRUNC(SYSDATE)+1/12-1/86400)
AND O.SYSTEM_ID=R.COUNTERID
AND O.CHA_CONS_REPERTORIO=1
AND T.ID_AMM IN (SELECT SYSTEM_ID FROM DPA_AMMINISTRA);


INSERT INTO SECURITY
(THING, PERSONORGROUP, ACCESSRIGHTS, CHA_TIPO_DIRITTO, TS_INSERIMENTO)
SELECT
P.DOCNUMBER,
(SELECT ID_RUOLO_RESP_CONS FROM DPA_AMMINISTRA WHERE SYSTEM_ID=T.ID_AMM),
'63', 'C', SYSTIMESTAMP
FROM PROFILE P, DPA_TIPO_ATTO T, DPA_REGISTRI_REPERTORIO R, DPA_STAMPA_REPERTORI S, DPA_OGGETTI_CUSTOM O
WHERE P.CHA_TIPO_PROTO IN ('C') 
AND P.DOCNUMBER=S.DOCNUMBER AND S.ID_REPERTORIO=R.COUNTERID AND T.SYSTEM_ID=R.TIPOLOGYID
AND (((S.REGISTRYID=R.REGISTRYID AND R.RFID IS NULL) OR (S.REGISTRYID=R.RFID AND R.REGISTRYID IS NULL)) OR (S.REGISTRYID IS NULL))
--AND TO_DATE(TO_CHAR(P.CREATION_DATE,'DD/MM/YYYY'),'DD/MM/YYYY') = TO_DATE(TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 'DD/MM/YYYY')
AND P.CREATION_TIME BETWEEN (TRUNC(SYSDATE-1)+1/12) AND (TRUNC(SYSDATE)+1/12-1/86400)
AND O.SYSTEM_ID=R.COUNTERID
AND O.CHA_CONS_REPERTORIO=1
AND T.ID_AMM IN (SELECT SYSTEM_ID FROM DPA_AMMINISTRA);


