--------------------------------------------------------
--  DDL for Table DPA_CHIAVI_CONFIG_TEMPLATE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONFIG_TEMPLATE" 
   (	"SYSTEM_ID" NUMBER, 
	"VAR_CODICE" VARCHAR2(32 BYTE), 
	"VAR_DESCRIZIONE" VARCHAR2(512 BYTE), 
	"VAR_VALORE" VARCHAR2(32 BYTE), 
	"CHA_TIPO_CHIAVE" CHAR(1 BYTE), 
	"CHA_VISIBILE" CHAR(1 BYTE) DEFAULT 1, 
	"CHA_MODIFICABILE" CHAR(1 BYTE) DEFAULT 1, 
	"CHA_INFASATO" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) ;
