--------------------------------------------------------
--  DDL for Table DPA_DETT_GLOBALI
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_DETT_GLOBALI" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"ID_CORR_GLOBALI" NUMBER(10,0), 
	"VAR_INDIRIZZO" VARCHAR2(128 BYTE), 
	"VAR_CAP" VARCHAR2(5 BYTE), 
	"VAR_PROVINCIA" VARCHAR2(2 BYTE), 
	"VAR_NAZIONE" VARCHAR2(32 BYTE), 
	"VAR_COD_FISCALE" VARCHAR2(16 BYTE), 
	"VAR_TELEFONO" VARCHAR2(16 BYTE), 
	"VAR_TELEFONO2" VARCHAR2(16 BYTE), 
	"VAR_FAX" VARCHAR2(16 BYTE), 
	"VAR_NOTE" VARCHAR2(250 BYTE), 
	"VAR_COD_FIS" VARCHAR2(128 BYTE), 
	"VAR_CITTA" VARCHAR2(64 BYTE), 
	"VAR_LOCALITA" VARCHAR2(128 BYTE), 
	"VAR_LUOGO_NASCITA" VARCHAR2(64 BYTE), 
	"DTA_NASCITA" VARCHAR2(64 BYTE), 
	"VAR_TITOLO" VARCHAR2(64 BYTE), 
	"ID_QUALIFICA_CORR" NUMBER(*,0)
   ) ;
