
--------------------------------------------------------
--  DDL for Table DPA_LOG
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_LOG" 
   (	"SYSTEM_ID" NUMBER, 
	"USERID_OPERATORE" VARCHAR2(32 BYTE), 
	"ID_PEOPLE_OPERATORE" NUMBER, 
	"ID_GRUPPO_OPERATORE" NUMBER, 
	"ID_AMM" NUMBER, 
	"DTA_AZIONE" DATE, 
	"VAR_OGGETTO" VARCHAR2(256 BYTE), 
	"ID_OGGETTO" NUMBER, 
	"VAR_DESC_OGGETTO" VARCHAR2(2000 BYTE), 
	"VAR_COD_AZIONE" VARCHAR2(32 BYTE), 
	"CHA_ESITO" CHAR(1 BYTE), 
	"VAR_DESC_AZIONE" VARCHAR2(2000 BYTE) ,
	"VAR_COD_WORKING_APPLICATION" VARCHAR2(200 BYTE)
   ) ;
