--------------------------------------------------------
--  DDL for Table DPA_FIRMATARI
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_FIRMATARI" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"VAR_COGNOME" VARCHAR2(50 BYTE), 
	"VAR_NOME" VARCHAR2(50 BYTE), 
	"VAR_COD_FISCALE" VARCHAR2(16 BYTE), 
	"VAR_TITOLARE" VARCHAR2(250 BYTE), 
	"VAR_RUOLO" VARCHAR2(250 BYTE), 
	"VAR_SERIE" VARCHAR2(64 BYTE), 
	"VAR_EMITTENTE_C" VARCHAR2(250 BYTE), 
	"VAR_EMITTENTE_O" VARCHAR2(250 BYTE), 
	"VAR_EMITTENTE_OU" VARCHAR2(250 BYTE), 
	"VAR_EMITTENTE_CN" VARCHAR2(250 BYTE)
   ) ;
