--------------------------------------------------------
--  DDL for Table DPA_REGISTRI_REPERTORIO
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_REGISTRI_REPERTORIO" 
   (	"TIPOLOGYID" NUMBER, 
	"COUNTERID" NUMBER, 
	"COUNTERSTATE" VARCHAR2(1 BYTE), 
	"SETTINGSTYPE" VARCHAR2(1 BYTE), 
	"REGISTRYID" NUMBER, 
	"RFID" NUMBER, 
	"ROLERESPID" NUMBER, 
	"PRINTERROLERESPID" NUMBER, 
	"PRINTERUSERRESPID" NUMBER, 
	"PRINTFREQ" VARCHAR2(2 BYTE), 
	"TIPOLOGYKIND" VARCHAR2(2 BYTE), 
	"DTASTART" DATE, 
	"DTAFINISH" DATE, 
	"DTANEXTAUTOMATICPRINT" DATE, 
	"DTALASTPRINT" DATE, 
	"LASTPRINTEDNUMBER" NUMBER, 
	"RESPRIGHTS" VARCHAR2(2 BYTE)
   ) ;
