--------------------------------------------------------
--  DDL for Table DPA_CONFIG_ANAGRAFICA_ESTERNA
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_CONFIG_ANAGRAFICA_ESTERNA" 
   (	"SYSTEM_ID" NUMBER(*,0), 
	"NOME_ANAGRAFICA_ESTERNA" VARCHAR2(16 BYTE), 
	"WSURL_ANAGRAFICA_ESTERNA" VARCHAR2(256 BYTE), 
	"INTEGRATION_ADAPTER_ID" VARCHAR2(50 BYTE), 
	"INTEGRATION_ADAPTER_VERSION" VARCHAR2(8 BYTE), 
	"CONFIG_PROVENIENZA" VARCHAR2(2 BYTE), 
	"CONFIG_MATRICOLA" VARCHAR2(8 BYTE), 
	"CONFIG_PASSWORD" VARCHAR2(8 BYTE), 
	"CONFIG_APPLICAZIONE" VARCHAR2(8 BYTE), 
	"CONFIG_RUOLO" VARCHAR2(6 BYTE), 
	"NOTE" VARCHAR2(516 BYTE), 
	"ENABLED" CHAR(1 BYTE) DEFAULT 1
   ) ;
