--------------------------------------------------------
--  DDL for Table DPA_AREA_CONSERVAZIONE
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_AREA_CONSERVAZIONE" 
   (	"SYSTEM_ID" NUMBER, 
	"ID_AMM" NUMBER, 
	"ID_PEOPLE" NUMBER, 
	"ID_RUOLO_IN_UO" NUMBER, 
	"CHA_STATO" CHAR(1 BYTE), 
	"VAR_TIPO_SUPPORTO" NUMBER, 
	"VAR_NOTE" VARCHAR2(500 BYTE), 
	"VAR_DESCRIZIONE" VARCHAR2(250 BYTE), 
	"DATA_APERTURA" DATE, 
	"DATA_INVIO" DATE, 
	"DATA_CONSERVAZIONE" DATE, 
	"VAR_MARCA_TEMPORALE" VARCHAR2(3000 BYTE), 
	"VAR_FIRMA_RESPONSABILE" VARCHAR2(1024 BYTE), 
	"VAR_LOCAZIONE_FISICA" VARCHAR2(512 BYTE), 
	"DATA_PROX_VERIFICA" DATE, 
	"DATA_ULTIMA_VERIFICA" DATE, 
	"DATA_RIVERSAMENTO" DATE, 
	"VAR_TIPO_CONS" VARCHAR2(32 BYTE), 
	"COPIE_SUPPORTI" NUMBER, 
	"VAR_NOTE_RIFIUTO" VARCHAR2(256 BYTE), 
	"VAR_FORMATO_DOC" VARCHAR2(10 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"ID_GRUPPO" NUMBER, 
	"ID_PROFILE_TRASMISSIONE" NUMBER, 
	"ID_POLICY" NUMBER(10,0), 
	"CONSOLIDA" CHAR(1 BYTE), 
	"ID_POLICY_VALIDAZIONE" NUMBER(10,0), 
	"VAR_FILE_CHIUSURA" CLOB, 
	"VAR_FILE_CHIUSURA_FIRMATO" CLOB, 
	"IS_PREFERRED" CHAR(1 BYTE)
   ) ;
