--------------------------------------------------------
--  DDL for Table DPA_MAIL_REGISTRI
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_MAIL_REGISTRI" 
   (	"SYSTEM_ID" NUMBER(10,0), 
	"ID_REGISTRO" NUMBER(10,0), 
	"VAR_PRINCIPALE" VARCHAR2(1 BYTE), 
	"VAR_EMAIL_REGISTRO" VARCHAR2(128 BYTE), 
	"VAR_USER_MAIL" VARCHAR2(128 BYTE), 
	"VAR_PWD_MAIL" VARCHAR2(32 BYTE), 
	"VAR_SERVER_SMTP" VARCHAR2(64 BYTE), 
	"CHA_SMTP_SSL" VARCHAR2(1 BYTE), 
	"CHA_POP_SSL" VARCHAR2(1 BYTE), 
	"NUM_PORTA_SMTP" NUMBER(10,0), 
	"CHA_SMTP_STA" VARCHAR2(1 BYTE), 
	"VAR_SERVER_POP" VARCHAR2(64 BYTE), 
	"NUM_PORTA_POP" NUMBER(10,0), 
	"VAR_USER_SMTP" VARCHAR2(128 BYTE), 
	"VAR_PWD_SMTP" VARCHAR2(128 BYTE), 
	"VAR_INBOX_IMAP" VARCHAR2(128 BYTE), 
	"VAR_SERVER_IMAP" VARCHAR2(128 BYTE), 
	"NUM_PORTA_IMAP" NUMBER(10,0), 
	"VAR_TIPO_CONNESSIONE" VARCHAR2(10 BYTE), 
	"VAR_BOX_MAIL_ELABORATE" VARCHAR2(50 BYTE), 
	"VAR_MAIL_NON_ELABORATE" VARCHAR2(50 BYTE), 
	"CHA_IMAP_SSL" VARCHAR2(1 BYTE), 
	"VAR_SOLO_MAIL_PEC" VARCHAR2(1 BYTE) DEFAULT '0', 
	"CHA_RICEVUTA_PEC" VARCHAR2(2 BYTE), 
	"VAR_NOTE" VARCHAR2(50 BYTE)
   ) ;
