--------------------------------------------------------
--  DDL for Table DPA_LDAP_CONFIG
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_LDAP_CONFIG" 
   (	"ID_AMM" NUMBER(*,0), 
	"SERVER_NAME" VARCHAR2(255 BYTE), 
	"GROUP_DN" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"USERID_ATTRIBUTE" VARCHAR2(50 BYTE), 
	"EMAIL_ATTRIBUTE" VARCHAR2(255 BYTE), 
	"MATRICOLA_ATTRIBUTE" VARCHAR2(50 BYTE), 
	"NOME_ATTRIBUTE" VARCHAR2(50 BYTE), 
	"COGNOME_ATTRIBUTE" VARCHAR2(50 BYTE), 
	"SEDE_ATTRIBUTE" VARCHAR2(255 BYTE), 
	"ID_USER" CHAR(1 BYTE)
   ) ;
