--------------------------------------------------------
--  DDL for Table PUBLISHER_EVENTS
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."PUBLISHER_EVENTS" 
   (	"PUBLISHINSTANCEID" NUMBER, 
	"EVENTNAME" NVARCHAR2(255), 
	"OBJECTTYPE" NVARCHAR2(255), 
	"OBJECTTEMPLATENAME" NVARCHAR2(255), 
	"ID" NUMBER, 
	"DATAMAPPERFULLCLASS" NVARCHAR2(2000), 
	"LOADFILEIFDOCTYPE" CHAR(1 BYTE), 
	"LOADATTATCHSIFDOCTYPE" CHAR(1 BYTE)
   ) ;
