--------------------------------------------------------
--  DDL for Table SUBSCRIBER_HISTORY
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."SUBSCRIBER_HISTORY" 
   (	"ID" NUMBER(10,0), 
	"RULEID" NUMBER(10,0), 
	"IDOBJECT" NVARCHAR2(255), 
	"OBJECTTEMPLATENAME" NVARCHAR2(255), 
	"OBJECDESCRIPTION" NVARCHAR2(2000), 
	"AUTHORNAME" NVARCHAR2(255), 
	"AUTHORID" NVARCHAR2(50), 
	"ROLENAME" NVARCHAR2(255), 
	"ROLEID" NVARCHAR2(50), 
	"OBJECTSNAPSHOT" CLOB, 
	"COMPUTED" CHAR(1 BYTE), 
	"COMPUTEDATE" DATE, 
	"ERRORID" NVARCHAR2(255), 
	"ERRORDESCRIPTION" NVARCHAR2(2000), 
	"MAILMESSAGESNAPSHOT" CLOB, 
	"OBJECTTYPE" NVARCHAR2(50), 
	"ERRORSTACK" NVARCHAR2(2000)
   ) ;
