USE [PCM_DEPOSITO_1]
GO
/****** Object:  Table [DOCSADM].[DPA_CLIENT_MODEL_PROCESSORS]    Script Date: 04/11/2013 16:41:37 ******/
--SET IDENTITY_INSERT [DOCSADM].[DPA_CLIENT_MODEL_PROCESSORS] ON
INSERT [DOCSADM].[DPA_CLIENT_MODEL_PROCESSORS] ([SYSTEM_ID], [NAME], [CLASS_ID], [SUPPORTED_EXTENSIONS]) VALUES (1, N'Microsoft Office Word 2000/XP/2003/2007', N'DocsPa_Models.WordModelProcessor', N'DOC|RTF')
INSERT [DOCSADM].[DPA_CLIENT_MODEL_PROCESSORS] ([SYSTEM_ID], [NAME], [CLASS_ID], [SUPPORTED_EXTENSIONS]) VALUES (2, N'OpenOffice.org 3.0', N'DocsPa_Models.OOModelProcessor', N'ODT|SXW')
--SET IDENTITY_INSERT [DOCSADM].[DPA_CLIENT_MODEL_PROCESSORS] OFF



USE [PCM_DEPOSITO_1]
GO
/****** Object:  Table [DOCSADM].[DPA_DISPOSITIVI_STAMPA]    Script Date: 04/11/2013 16:36:27 ******/
--SET IDENTITY_INSERT [DOCSADM].[DPA_DISPOSITIVI_STAMPA] ON
INSERT [DOCSADM].[DPA_DISPOSITIVI_STAMPA] ([Id], [Code], [Description]) VALUES (1, N'ZEBRA', N'ZEBRA')
INSERT [DOCSADM].[DPA_DISPOSITIVI_STAMPA] ([Id], [Code], [Description]) VALUES (2, N'DYMO_LABEL_WRITER_400', N'DYMO LABEL WRITER 400')
--SET IDENTITY_INSERT [DOCSADM].[DPA_DISPOSITIVI_STAMPA] OFF



USE [PCM_DEPOSITO_1]
GO
/****** Object:  Table [DOCSADM].[DPA_AMMINISTRA]    Script Date: 04/11/2013 16:15:42 ******/
--SET IDENTITY_INSERT [DOCSADM].[DPA_AMMINISTRA] ON
INSERT into [DOCSADM].[DPA_AMMINISTRA] ([SYSTEM_ID], [VAR_CODICE_AMM], [VAR_CODICE_ISTAT], [VAR_DESC_AMM], [VAR_LIBRERIA], [CHA_SEPARATORE], [CHA_STR_FISSA], [CHA_STR_SEGNATURA], [VAR_SMTP], [NUM_PORTA_SMTP], [VAR_LOGIN], [VAR_PATH], [VAR_FORMATO_SEGNATURA], [VAR_FORMATO_FASCICOLATURA], [VAR_DOMINIO], [CHA_PROTOINT], [VAR_RAGIONE_TO], [VAR_RAGIONE_CC], [VAR_USER_SMTP], [VAR_PWD_SMTP], [VAR_RAGIONE_REFERENTE], [ID_RAGIONE_TO], [ID_RAGIONE_CC], [ID_RAGIONE_REFERENTE], [NUM_GG_PERM_TODOLIST], [CHA_ATTIVA_GG_PERM_TODOLIST], [CHA_SMTP_SSL], [CHA_SMTP_STA], [ENABLE_PASSWORD_EXPIRATION], [PASSWORD_EXPIRATION_DAYS], [PASSWORD_MIN_LENGTH], [PASSWORD_SPECIAL_CHAR_LIST], [FROM_EMAIL_ADDRESS], [ID_RAGIONE_CONOSCENZA], [ID_RAGIONE_COMPETENZA], [FONTCOLOR], [NUM_RECORD], [CHA_ARCHIVIAZIONE_LOG], [VAR_FORMATO_TIMBRO], [ID_CARAT_DF], [ID_COLORE_DF], [ID_POS_DF], [ORIENTAMENTO], [TIPO_ROTAZ], [PULS_COLOR], [VAR_FORMATO_DOMINIO], [ID_CLIENT_MODEL_PROCESSOR], [CSS], [NEWS], [ENABLE_NEWS], [VAR_FORMATO_PROT_TIT], [COL_SEGN], [SPEDIZIONE_AUTO_DOC], [AVVISA_SPEDIZIONE_DOC], [TIPO_DOC_OBBL], [IS_ENABLED_SMART_CLIENT], [SMART_CLIENT_PDF_CONV_ON_SCAN], [ID_DISPOSITIVO_STAMPA], [TRASMISSIONE_AUTO_DOC], [VAR_EMAIL_RES_IPA], [VAR_CODICE_AMM_IPA]) 
VALUES (1, N'PCM', NULL, N'Presidenza del Consiglio dei Ministri', N'PCM', NULL, NULL, NULL, N'mail.palazzochigi.it', 25, NULL, NULL, N'COD_REG-NUM_PROTO-IN_OUT-DATA_COMP', N'COD_TITOLO\DATA_ANNO\NUM_PROG', N'', NULL, N'INOLTRO', N'VISIONE', N'', N'', NULL, 15, 33, NULL, NULL, N'0', N'0', N' ', NULL, NULL, NULL, NULL, N'', 33, 32, NULL, NULL, NULL, N'COD_REG-NUM_PROTO-IN_OUT-DATA_COMP-CLASSIFICA', 1, 1, 1, N'', N'', N'129^14^06', N'', 1, 1, NULL, NULL, N'', N'2', N'0', N'0', N'0', N'0', N'0', 1, N'0', NULL, NULL)
--SET IDENTITY_INSERT [DOCSADM].[DPA_AMMINISTRA] OFF

