use [PCM_DEPOSITO_FINGER]
go

DELETE FROM [ARCHIVE_Configuration]
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('NOME_SCHEMA_CORRENTE','PCM_040413')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('NOME_UTENTE_CORRENTE','DOCSADM')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('NOME_UTENTE_DEPOSITO','DOCSADM')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('ID_AUTORE_CONSOLIDAMENTO','1')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('ID_RUOLO_CONSOLIDAMENTO','1')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('ID_CORR_GLOBALI_RUOLO_CONSULTATORE','800005001')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('ID_GROUPS_RUOLO_CONSULTATORE','800005000')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('ID_CORR_GLOBALI_RUOLO_ARCHIVISTA','800000001')
GO

INSERT INTO [ARCHIVE_Configuration]([KEY],[VALUE]) VALUES('SPOSTA_FILE','1')
GO


