use [PCM_DEPOSITO_1]
go

INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (1, 'ARRIVO')
INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (2, 'PARTENZA')
INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (3, 'INTERNO')
INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (4, 'NON PROTOCOLLATO')
INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (5, 'STAMPA REGISTRO PROTOCOLLO')
INSERT INTO [DOCSADM].[ARCHIVE_ProfileType]([System_ID],[Name]) VALUES (6, 'STAMPA REPERTORIO')
GO


