//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocsPaDocumentale_HERMES.DMFileOperation {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMFileOperation.DMFileOperationSoap")]
    public interface DMFileOperationSoap {
        
        // CODEGEN: Parameter 'pDoc' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AggiungiDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoResponse AggiungiDocumento(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoRequest request);
        
        // CODEGEN: Parameter 'pDoc' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AggiungiDocumentoSec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecResponse AggiungiDocumentoSec(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecRequest request);
        
        // CODEGEN: Parameter 'pDoc' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AggiungiVersione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneResponse AggiungiVersione(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneRequest request);
        
        // CODEGEN: Parameter 'VisualizzaDocumentoResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizzaDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoResponse VisualizzaDocumento(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoRequest request);
        
        // CODEGEN: Parameter 'VisualizzaDocumentoSecResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizzaDocumentoSec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecResponse VisualizzaDocumentoSec(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellaDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancellaDocumento(string Libreria, string pDocNumber, string pNomeForm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancellaDocumentoSec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancellaDocumentoSec(string Libreria, string pDocNumber, string pNomeForm, string DMUser, string DMPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProfile(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfileSec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProfileSec(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate, string Trustee, string DMUser, string DMPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfileDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProfileDB(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizzaLookUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet VisualizzaLookUp(string pLibreria, string NomeTabellaLookUp, string DMUser, string DMPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScegliVersione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ScegliVersione(string pLibreria, string pDocnumber, string DMUser, string DMPassword);
        
        // CODEGEN: Parameter 'VisualizzaVersioneResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizzaVersione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneResponse VisualizzaVersione(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NomeForm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Titolo_Doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Appl_Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Autore;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Note;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int pDocLen;
        
        public AggiungiDocumentoRequest() {
        }
        
        public AggiungiDocumentoRequest(string Libreria, string NomeForm, string Titolo_Doc, string Appl_Id, string Autore, string Note, byte[] pDoc, int pDocLen) {
            this.Libreria = Libreria;
            this.NomeForm = NomeForm;
            this.Titolo_Doc = Titolo_Doc;
            this.Appl_Id = Appl_Id;
            this.Autore = Autore;
            this.Note = Note;
            this.pDoc = pDoc;
            this.pDocLen = pDocLen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AggiungiDocumentoResult;
        
        public AggiungiDocumentoResponse() {
        }
        
        public AggiungiDocumentoResponse(string AggiungiDocumentoResult) {
            this.AggiungiDocumentoResult = AggiungiDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiDocumentoSec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiDocumentoSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NomeForm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Titolo_Doc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Appl_Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Autore;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Note;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Trustee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string DMUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string DMPassword;
        
        public AggiungiDocumentoSecRequest() {
        }
        
        public AggiungiDocumentoSecRequest(string Libreria, string NomeForm, string Titolo_Doc, string Appl_Id, string Autore, string Note, byte[] pDoc, string Trustee, string DMUser, string DMPassword) {
            this.Libreria = Libreria;
            this.NomeForm = NomeForm;
            this.Titolo_Doc = Titolo_Doc;
            this.Appl_Id = Appl_Id;
            this.Autore = Autore;
            this.Note = Note;
            this.pDoc = pDoc;
            this.Trustee = Trustee;
            this.DMUser = DMUser;
            this.DMPassword = DMPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiDocumentoSecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiDocumentoSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AggiungiDocumentoSecResult;
        
        public AggiungiDocumentoSecResponse() {
        }
        
        public AggiungiDocumentoSecResponse(string AggiungiDocumentoSecResult) {
            this.AggiungiDocumentoSecResult = AggiungiDocumentoSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiVersione", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiVersioneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NomeForm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int Docnumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string fVersione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string DMUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string DMPassword;
        
        public AggiungiVersioneRequest() {
        }
        
        public AggiungiVersioneRequest(string Libreria, string NomeForm, byte[] pDoc, int Docnumber, string fVersione, string DMUser, string DMPassword) {
            this.Libreria = Libreria;
            this.NomeForm = NomeForm;
            this.pDoc = pDoc;
            this.Docnumber = Docnumber;
            this.fVersione = fVersione;
            this.DMUser = DMUser;
            this.DMPassword = DMPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AggiungiVersioneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AggiungiVersioneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AggiungiVersioneResult;
        
        public AggiungiVersioneResponse() {
        }
        
        public AggiungiVersioneResponse(string AggiungiVersioneResult) {
            this.AggiungiVersioneResult = AggiungiVersioneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaDocumento", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pDocNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string estensione;
        
        public VisualizzaDocumentoRequest() {
        }
        
        public VisualizzaDocumentoRequest(string Libreria, string pDocNumber, string estensione) {
            this.Libreria = Libreria;
            this.pDocNumber = pDocNumber;
            this.estensione = estensione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaDocumentoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] VisualizzaDocumentoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string estensione;
        
        public VisualizzaDocumentoResponse() {
        }
        
        public VisualizzaDocumentoResponse(byte[] VisualizzaDocumentoResult, string estensione) {
            this.VisualizzaDocumentoResult = VisualizzaDocumentoResult;
            this.estensione = estensione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaDocumentoSec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaDocumentoSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pDocNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string estensione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string DMUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string DMPassword;
        
        public VisualizzaDocumentoSecRequest() {
        }
        
        public VisualizzaDocumentoSecRequest(string Libreria, string pDocNumber, string estensione, string DMUser, string DMPassword) {
            this.Libreria = Libreria;
            this.pDocNumber = pDocNumber;
            this.estensione = estensione;
            this.DMUser = DMUser;
            this.DMPassword = DMPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaDocumentoSecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaDocumentoSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] VisualizzaDocumentoSecResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string estensione;
        
        public VisualizzaDocumentoSecResponse() {
        }
        
        public VisualizzaDocumentoSecResponse(byte[] VisualizzaDocumentoSecResult, string estensione) {
            this.VisualizzaDocumentoSecResult = VisualizzaDocumentoSecResult;
            this.estensione = estensione;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaVersione", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaVersioneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Libreria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pDocNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Version_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string estensione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string DMUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string DMPassword;
        
        public VisualizzaVersioneRequest() {
        }
        
        public VisualizzaVersioneRequest(string Libreria, string pDocNumber, string Version_id, string estensione, string DMUser, string DMPassword) {
            this.Libreria = Libreria;
            this.pDocNumber = pDocNumber;
            this.Version_id = Version_id;
            this.estensione = estensione;
            this.DMUser = DMUser;
            this.DMPassword = DMPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VisualizzaVersioneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VisualizzaVersioneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] VisualizzaVersioneResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string estensione;
        
        public VisualizzaVersioneResponse() {
        }
        
        public VisualizzaVersioneResponse(byte[] VisualizzaVersioneResult, string estensione) {
            this.VisualizzaVersioneResult = VisualizzaVersioneResult;
            this.estensione = estensione;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DMFileOperationSoapChannel : DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMFileOperationSoapClient : System.ServiceModel.ClientBase<DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap>, DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap {
        
        public DMFileOperationSoapClient() {
        }
        
        public DMFileOperationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMFileOperationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMFileOperationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMFileOperationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.AggiungiDocumento(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoRequest request) {
            return base.Channel.AggiungiDocumento(request);
        }
        
        public string AggiungiDocumento(string Libreria, string NomeForm, string Titolo_Doc, string Appl_Id, string Autore, string Note, byte[] pDoc, int pDocLen) {
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoRequest();
            inValue.Libreria = Libreria;
            inValue.NomeForm = NomeForm;
            inValue.Titolo_Doc = Titolo_Doc;
            inValue.Appl_Id = Appl_Id;
            inValue.Autore = Autore;
            inValue.Note = Note;
            inValue.pDoc = pDoc;
            inValue.pDocLen = pDocLen;
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).AggiungiDocumento(inValue);
            return retVal.AggiungiDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.AggiungiDocumentoSec(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecRequest request) {
            return base.Channel.AggiungiDocumentoSec(request);
        }
        
        public string AggiungiDocumentoSec(string Libreria, string NomeForm, string Titolo_Doc, string Appl_Id, string Autore, string Note, byte[] pDoc, string Trustee, string DMUser, string DMPassword) {
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecRequest();
            inValue.Libreria = Libreria;
            inValue.NomeForm = NomeForm;
            inValue.Titolo_Doc = Titolo_Doc;
            inValue.Appl_Id = Appl_Id;
            inValue.Autore = Autore;
            inValue.Note = Note;
            inValue.pDoc = pDoc;
            inValue.Trustee = Trustee;
            inValue.DMUser = DMUser;
            inValue.DMPassword = DMPassword;
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiDocumentoSecResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).AggiungiDocumentoSec(inValue);
            return retVal.AggiungiDocumentoSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.AggiungiVersione(DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneRequest request) {
            return base.Channel.AggiungiVersione(request);
        }
        
        public string AggiungiVersione(string Libreria, string NomeForm, byte[] pDoc, int Docnumber, string fVersione, string DMUser, string DMPassword) {
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneRequest();
            inValue.Libreria = Libreria;
            inValue.NomeForm = NomeForm;
            inValue.pDoc = pDoc;
            inValue.Docnumber = Docnumber;
            inValue.fVersione = fVersione;
            inValue.DMUser = DMUser;
            inValue.DMPassword = DMPassword;
            DocsPaDocumentale_HERMES.DMFileOperation.AggiungiVersioneResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).AggiungiVersione(inValue);
            return retVal.AggiungiVersioneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.VisualizzaDocumento(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoRequest request) {
            return base.Channel.VisualizzaDocumento(request);
        }
        
        public byte[] VisualizzaDocumento(string Libreria, string pDocNumber, ref string estensione) {
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoRequest();
            inValue.Libreria = Libreria;
            inValue.pDocNumber = pDocNumber;
            inValue.estensione = estensione;
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).VisualizzaDocumento(inValue);
            estensione = retVal.estensione;
            return retVal.VisualizzaDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.VisualizzaDocumentoSec(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecRequest request) {
            return base.Channel.VisualizzaDocumentoSec(request);
        }
        
        public byte[] VisualizzaDocumentoSec(string Libreria, string pDocNumber, ref string estensione, string DMUser, string DMPassword) {
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecRequest();
            inValue.Libreria = Libreria;
            inValue.pDocNumber = pDocNumber;
            inValue.estensione = estensione;
            inValue.DMUser = DMUser;
            inValue.DMPassword = DMPassword;
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaDocumentoSecResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).VisualizzaDocumentoSec(inValue);
            estensione = retVal.estensione;
            return retVal.VisualizzaDocumentoSecResult;
        }
        
        public string CancellaDocumento(string Libreria, string pDocNumber, string pNomeForm) {
            return base.Channel.CancellaDocumento(Libreria, pDocNumber, pNomeForm);
        }
        
        public string CancellaDocumentoSec(string Libreria, string pDocNumber, string pNomeForm, string DMUser, string DMPassword) {
            return base.Channel.CancellaDocumentoSec(Libreria, pDocNumber, pNomeForm, DMUser, DMPassword);
        }
        
        public string UpdateProfile(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate) {
            return base.Channel.UpdateProfile(pLibreria, pNomeForm, pDocNumber, pStringUpdate);
        }
        
        public string UpdateProfileSec(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate, string Trustee, string DMUser, string DMPassword) {
            return base.Channel.UpdateProfileSec(pLibreria, pNomeForm, pDocNumber, pStringUpdate, Trustee, DMUser, DMPassword);
        }
        
        public string UpdateProfileDB(string pLibreria, string pNomeForm, string pDocNumber, string pStringUpdate) {
            return base.Channel.UpdateProfileDB(pLibreria, pNomeForm, pDocNumber, pStringUpdate);
        }
        
        public System.Data.DataSet VisualizzaLookUp(string pLibreria, string NomeTabellaLookUp, string DMUser, string DMPassword) {
            return base.Channel.VisualizzaLookUp(pLibreria, NomeTabellaLookUp, DMUser, DMPassword);
        }
        
        public System.Data.DataSet ScegliVersione(string pLibreria, string pDocnumber, string DMUser, string DMPassword) {
            return base.Channel.ScegliVersione(pLibreria, pDocnumber, DMUser, DMPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneResponse DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap.VisualizzaVersione(DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneRequest request) {
            return base.Channel.VisualizzaVersione(request);
        }
        
        public byte[] VisualizzaVersione(string Libreria, string pDocNumber, string Version_id, ref string estensione, string DMUser, string DMPassword) {
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneRequest inValue = new DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneRequest();
            inValue.Libreria = Libreria;
            inValue.pDocNumber = pDocNumber;
            inValue.Version_id = Version_id;
            inValue.estensione = estensione;
            inValue.DMUser = DMUser;
            inValue.DMPassword = DMPassword;
            DocsPaDocumentale_HERMES.DMFileOperation.VisualizzaVersioneResponse retVal = ((DocsPaDocumentale_HERMES.DMFileOperation.DMFileOperationSoap)(this)).VisualizzaVersione(inValue);
            estensione = retVal.estensione;
            return retVal.VisualizzaVersioneResult;
        }
    }
}
