--------------------------------------------------------
--  Constraints for Table DPA_NOTE
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("DATACREAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("IDUTENTECREATORE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("IDRUOLOCREATORE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("TIPOVISIBILITA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("TIPOOGGETTOASSOCIATO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_NOTE" MODIFY ("IDOGGETTOASSOCIATO" NOT NULL ENABLE);
