--------------------------------------------------------
--  Ref Constraints for Table DPA_PROFIL_STO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_STO" ADD CONSTRAINT "FK_DP_PRF_STO_ID_PEOPLE" FOREIGN KEY ("ID_PEOPLE")
	  REFERENCES "ITCOLL_6GIU12"."PEOPLE" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_STO" ADD CONSTRAINT "FK_DP_PRF_STO_ID_PROFILE" FOREIGN KEY ("ID_PROFILE")
	  REFERENCES "ITCOLL_6GIU12"."PROFILE" ("SYSTEM_ID") DISABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_STO" ADD CONSTRAINT "FK_DP_PRF_STO_ID_RUOLO_IN_UO" FOREIGN KEY ("ID_RUOLO_IN_UO")
	  REFERENCES "ITCOLL_6GIU12"."DPA_CORR_GLOBALI" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_STO" ADD CONSTRAINT "FK_DP_PRF_STO_ID_TEMPLATE" FOREIGN KEY ("ID_TEMPLATE")
	  REFERENCES "ITCOLL_6GIU12"."DPA_TIPO_ATTO" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_STO" ADD CONSTRAINT "FK_DP_PRF_ST_ID_OGG_CUSTOM" FOREIGN KEY ("ID_OGG_CUSTOM")
	  REFERENCES "ITCOLL_6GIU12"."DPA_OGGETTI_CUSTOM" ("SYSTEM_ID") ENABLE NOVALIDATE;
