--------------------------------------------------------
--  Constraints for Table DPA_CHIAVI_CONF_BKP20110909
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("VAR_CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("VAR_VALORE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("CHA_VISIBILE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("CHA_MODIFICABILE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHIAVI_CONF_BKP20110909" MODIFY ("CHA_GLOBALE" NOT NULL ENABLE);
