--------------------------------------------------------
--  Constraints for Table DPA_CHECKIN_CHECKOUT
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" ADD CONSTRAINT "PK_DPA_CHECKIN_CHECKOUT" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("ID_DOCUMENT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("DOCUMENT_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("ID_ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_CHECKIN_CHECKOUT" MODIFY ("CHECK_OUT_DATE" NOT NULL ENABLE);
