--------------------------------------------------------
--  Ref Constraints for Table DPA_ASS_GRIDS
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_GRIDS" ADD CONSTRAINT "DPA_ASS_GRIDS_R01" FOREIGN KEY ("USER_ID")
	  REFERENCES "ITCOLL_6GIU12"."PEOPLE" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_GRIDS" ADD CONSTRAINT "DPA_ASS_GRIDS_R02" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ITCOLL_6GIU12"."GROUPS" ("SYSTEM_ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_GRIDS" ADD CONSTRAINT "DPA_ASS_GRIDS_R03" FOREIGN KEY ("GRID_ID")
	  REFERENCES "ITCOLL_6GIU12"."DPA_GRIDS" ("SYSTEM_ID") ENABLE NOVALIDATE;
