--------------------------------------------------------
--  Constraints for Table DPA_VIS_TIPO_FASC
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_VIS_TIPO_FASC" ADD CONSTRAINT "DPA_VIS_TIPO_FASC_R01" UNIQUE ("ID_TIPO_FASC", "ID_RUOLO") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_VIS_TIPO_FASC" ADD CONSTRAINT "PK_DPA_VIS_TIPO_FASC" PRIMARY KEY ("SYSTEM_ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_VIS_TIPO_FASC" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
