--------------------------------------------------------
--  Constraints for Table DPA_TODOLIST
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_TRASMISSIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_TRASM_SINGOLA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_TRASM_UTENTE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("DTA_INVIO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_PEOPLE_MITT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_RUOLO_MITT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_PEOPLE_DEST" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("ID_RAGIONE_TRASM" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_TODOLIST" MODIFY ("DTA_VISTA" NOT NULL ENABLE);
