--------------------------------------------------------
--  Constraints for Table DPA_DATA_ARRIVO_STO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_DATA_ARRIVO_STO" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_DATA_ARRIVO_STO" MODIFY ("DOCNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_DATA_ARRIVO_STO" MODIFY ("ID_GROUP" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_DATA_ARRIVO_STO" MODIFY ("ID_PEOPLE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_DATA_ARRIVO_STO" ADD PRIMARY KEY ("SYSTEM_ID") ENABLE;
