--------------------------------------------------------
--  Constraints for Table ELEMENTIRUBRICA
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" ADD CONSTRAINT "PK_ELEMENTIRUBRICA" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("CODICE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("DATACREAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("DATAULTIMAMODIFICA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."ELEMENTIRUBRICA" MODIFY ("IDUTENTECREATORE" NOT NULL ENABLE);
