--------------------------------------------------------
--  Ref Constraints for Table PEOPLE
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."PEOPLE" ADD CONSTRAINT "FK_PEOPLEID_DISPOSITIVO_STAMPA" FOREIGN KEY ("ID_DISPOSITIVO_STAMPA")
	  REFERENCES "ITCOLL_6GIU12"."DPA_DISPOSITIVI_STAMPA" ("ID") ON DELETE SET NULL ENABLE NOVALIDATE;
 
  ALTER TABLE "ITCOLL_6GIU12"."PEOPLE" ADD CONSTRAINT "PEOPLE_R01" FOREIGN KEY ("ID_CLIENT_MODEL_PROCESSOR")
	  REFERENCES "ITCOLL_6GIU12"."DPA_CLIENT_MODEL_PROCESSORS" ("SYSTEM_ID") ON DELETE SET NULL ENABLE NOVALIDATE;
