--------------------------------------------------------
--  Constraints for Table SUBSCRIBER_RULES
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_RULES" ADD CONSTRAINT "PUBLISH_RULES_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_RULES" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_RULES" MODIFY ("ENABLED" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."SUBSCRIBER_RULES" MODIFY ("ORDINAL" NOT NULL ENABLE);
