CREATE TABLE DPA_PHASES
(
  SYSTEM_ID           	 int primary key IDENTITY(1,1) NOT NULL,
  DESCRIPTION     	 	 VARCHAR(100)      NOT NULL
)


CREATE TABLE DPA_ASSOCIAZIONE_STATI_PHASES
(
  SYSTEM_ID           	 INT primary key IDENTITY(1,1) NOT NULL,
  ID_STATO    	 		 INT  NOT NULL,
  ID_PHASES				 INT  NOT NULL,
  ID_DIAGRAMMA			 INT NOT NULL,
  CONSTRAINT STATO_PHASES_UNIQUE UNIQUE (ID_STATO, ID_PHASES)
)


