BEGIN

	--AGGIORNAMENTO PER ACCEPTTRASMDOCUMENT
	UPDATE dpa_anagrafica_log SET notification = '1', notification_recipients = 'SENDER_TRANSMISSION', multiplicity = 'ONE' 
	WHERE VAR_METODO = 'ACCEPTTRASMDOCUMENT';

	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_METODO = 'ACCEPTTRASMDOCUMENT');
	
	UPDATE DPA_LOG_ATTIVATI 
	SET NOTIFY = 'OBB'
	WHERE SYSTEM_ID_ANAGRAFICA IN (select SYSTEM_ID from dpa_anagrafica_log where VAR_METODO = 'ACCEPTTRASMDOCUMENT');
	
	
	--AGGIORNAMENTO PER ACCEPTTRASMFOLDER
	UPDATE dpa_anagrafica_log SET notification = '1', notification_recipients = 'SENDER_TRANSMISSION', multiplicity = 'ONE' 
	WHERE VAR_METODO = 'ACCEPTTRASMFOLDER';
	
	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_METODO = 'ACCEPTTRASMFOLDER');
	
	UPDATE DPA_LOG_ATTIVATI 
	SET NOTIFY = 'OBB'
	WHERE SYSTEM_ID_ANAGRAFICA IN (select SYSTEM_ID from dpa_anagrafica_log where VAR_METODO = 'ACCEPTTRASMFOLDER');
	

	--CLOSE_TASK_DOCUMENT
	INSERT INTO DPA_ANAGRAFICA_LOG (SYSTEM_ID, VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO, MULTIPLICITY, ID_AMM, NOTIFICATION, CONFIGURABLE, NOTIFICATION_RECIPIENTS, COLOR )
	SELECT seq.nextval, 'CLOSE_TASK_DOCUMENT', 'Chiusura del task', 'DOCUMENTO', 'CLOSE_TASK_DOCUMENT', 'ONE', a.system_id, '1', '1', 'SENDER_TRANSMISSION', 'BLUE' 
	FROM DPA_AMMINISTRA a ;
	   
	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_CODICE = 'CLOSE_TASK_DOCUMENT');

	INSERT INTO DPA_LOG_ATTIVATI ( SYSTEM_ID_ANAGRAFICA, ID_AMM, NOTIFY )
	SELECT L.SYSTEM_ID, L.ID_AMM, 'CON' 
	FROM DPA_ANAGRAFICA_LOG L
	WHERE L.VAR_CODICE = 'CLOSE_TASK_DOCUMENT';
	
	
	--CLOSE_TASK_FOLDER
	INSERT INTO DPA_ANAGRAFICA_LOG (SYSTEM_ID, VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO, MULTIPLICITY, ID_AMM, NOTIFICATION, CONFIGURABLE, NOTIFICATION_RECIPIENTS, COLOR )
	SELECT seq.nextval, 'CLOSE_TASK_FOLDER', 'Chiusura del task', 'FASCICOLO', 'CLOSE_TASK_FOLDER', 'ONE', a.system_id, '1', '1', 'SENDER_TRANSMISSION', 'BLUE' 
	FROM DPA_AMMINISTRA a ;
	   
	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_CODICE = 'CLOSE_TASK_FOLDER');

	INSERT INTO DPA_LOG_ATTIVATI ( SYSTEM_ID_ANAGRAFICA, ID_AMM, NOTIFY )
	SELECT L.SYSTEM_ID, L.ID_AMM, 'CON' 
	FROM DPA_ANAGRAFICA_LOG L
	WHERE L.VAR_CODICE = 'CLOSE_TASK_FOLDER';
	
	
	--CANCEL_TASK_DOCUMENT
	INSERT INTO DPA_ANAGRAFICA_LOG (SYSTEM_ID, VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO, MULTIPLICITY, ID_AMM, NOTIFICATION, CONFIGURABLE, NOTIFICATION_RECIPIENTS, COLOR )
	SELECT seq.nextval, 'CANCEL_TASK_DOCUMENT', 'Annullamento del task', 'DOCUMENTO', 'CANCEL_TASK_DOCUMENT', 'ONE', a.system_id, '1', '1', 'USER_RECIPIENT_TASK', 'BLUE' 
	FROM DPA_AMMINISTRA a ;
	   
	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_CODICE = 'CANCEL_TASK_DOCUMENT');

	INSERT INTO DPA_LOG_ATTIVATI ( SYSTEM_ID_ANAGRAFICA, ID_AMM, NOTIFY )
	SELECT L.SYSTEM_ID, L.ID_AMM, 'CON' 
	FROM DPA_ANAGRAFICA_LOG L
	WHERE L.VAR_CODICE = 'CANCEL_TASK_DOCUMENT';
	
	
	--CANCEL_TASK_FOLDER
	INSERT INTO DPA_ANAGRAFICA_LOG (SYSTEM_ID, VAR_CODICE, VAR_DESCRIZIONE, VAR_OGGETTO, VAR_METODO, MULTIPLICITY, ID_AMM, NOTIFICATION, CONFIGURABLE, NOTIFICATION_RECIPIENTS, COLOR )
	SELECT seq.nextval, 'CANCEL_TASK_FOLDER', 'Annullamento del task', 'FASCICOLO', 'CANCEL_TASK_FOLDER', 'ONE', a.system_id, '1', '1', 'USER_RECIPIENT_TASK', 'BLUE' 
	FROM DPA_AMMINISTRA a ;
	   
	INSERT INTO dpa_event_type_assertions
	  (SELECT seq.NEXTVAL, L.SYSTEM_ID,  L.var_descrizione, a.system_id, a.var_codice_amm, 'AMM', 'I', '1', a.system_id
		 FROM DPA_ANAGRAFICA_LOG L JOIN DPA_AMMINISTRA A ON L.ID_AMM = A.SYSTEM_ID
		 WHERE L.VAR_CODICE = 'CANCEL_TASK_FOLDER');

	INSERT INTO DPA_LOG_ATTIVATI ( SYSTEM_ID_ANAGRAFICA, ID_AMM, NOTIFY )
	SELECT L.SYSTEM_ID, L.ID_AMM, 'CON' 
	FROM DPA_ANAGRAFICA_LOG L
	WHERE L.VAR_CODICE = 'CANCEL_TASK_FOLDER';
END;
/
COMMIT;