// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: AGPL-3.0-or-later
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.Legacy.WebApi.Application.Handlers.ExportDistributionList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.Legacy.WebApi.Application.Handlers.ExportDistributionList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azione.
        /// </summary>
        internal static string HeaderAction {
            get {
                return ResourceManager.GetString("HeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubrica.
        /// </summary>
        internal static string HeaderAddressBook {
            get {
                return ResourceManager.GetString("HeaderAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod.Amm..
        /// </summary>
        internal static string HeaderAdministraion {
            get {
                return ResourceManager.GetString("HeaderAdministraion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod. Corrispondente.
        /// </summary>
        internal static string HeaderCorrespondentCode {
            get {
                return ResourceManager.GetString("HeaderCorrespondentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione Corrispondente.
        /// </summary>
        internal static string HeaderCorrespondentName {
            get {
                return ResourceManager.GetString("HeaderCorrespondentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod. Lista.
        /// </summary>
        internal static string HeaderListCode {
            get {
                return ResourceManager.GetString("HeaderListCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione Lista.
        /// </summary>
        internal static string HeaderListDescription {
            get {
                return ResourceManager.GetString("HeaderListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilità.
        /// </summary>
        internal static string HeaderPermissions {
            get {
                return ResourceManager.GetString("HeaderPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice RF.
        /// </summary>
        internal static string HeaderRF {
            get {
                return ResourceManager.GetString("HeaderRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo.
        /// </summary>
        internal static string HeaderRole {
            get {
                return ResourceManager.GetString("HeaderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente.
        /// </summary>
        internal static string HeaderUser {
            get {
                return ResourceManager.GetString("HeaderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.{0}.
        /// </summary>
        internal static string ReportFileName {
            get {
                return ResourceManager.GetString("ReportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista di distribuzione.
        /// </summary>
        internal static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
    }
}
