use [PCM_DEPOSITO_1]
go

--1 - RICERCA
--2 - ANALISI
--3 - ESECUZIONE

INSERT INTO [DOCSADM].[ARCHIVE_JobType]([System_ID],[Nome]) VALUES(1,'RICERCA')
GO

INSERT INTO [DOCSADM].[ARCHIVE_JobType]([System_ID],[Nome]) VALUES(2,'ANALISI')
GO

INSERT INTO [DOCSADM].[ARCHIVE_JobType]([System_ID],[Nome]) VALUES(3,'ESECUZIONE')
GO


