--------------------------------------------------------
--  DDL for Index INDX_ASS_TEMPL_FASC
--------------------------------------------------------

  CREATE INDEX "ITCOLL_6GIU12"."INDX_ASS_TEMPL_FASC" ON "ITCOLL_6GIU12"."DPA_ASS_TEMPLATES_FASC" (TO_NUMBER("ID_PROJECT")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PITRE_INFOTN_DATA_COLL" ;
