--------------------------------------------------------
--  Constraints for Table DPA_ASS_LETTERE_DOCUMENTI
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_LETTERE_DOCUMENTI" MODIFY ("ID_AMM" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_LETTERE_DOCUMENTI" MODIFY ("ID_LETTERADOC" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_LETTERE_DOCUMENTI" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_ASS_LETTERE_DOCUMENTI" MODIFY ("ETICHETTA" NOT NULL ENABLE);
