--------------------------------------------------------
--  Constraints for Table DPA_PROFIL_FASC_STO
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("SYSTEMID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("ID_TEMPLATE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("DTA_MODIFICA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("ID_PROJECT" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("ID_OGG_CUSTOM" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("ID_PEOPLE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" MODIFY ("ID_RUOLO_IN_UO" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."DPA_PROFIL_FASC_STO" ADD PRIMARY KEY ("SYSTEMID") ENABLE;
