--------------------------------------------------------
--  Constraints for Table PGU_UTENTI
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."PGU_UTENTI" ADD CONSTRAINT "PGU_UTENTI_PK" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."PGU_UTENTI" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."PGU_UTENTI" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."PGU_UTENTI" MODIFY ("AMMINISTRATORE" NOT NULL ENABLE);
