--------------------------------------------------------
--  Constraints for Table UTENTI
--------------------------------------------------------

  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" ADD CONSTRAINT "PK_UTENTI" PRIMARY KEY ("ID") ENABLE;
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("NOME" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("DATACREAZIONE" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("DATAULTIMAMODIFICA" NOT NULL ENABLE);
 
  ALTER TABLE "ITCOLL_6GIU12"."UTENTI" MODIFY ("AMMINISTRATORE" NOT NULL ENABLE);
