// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: AGPL-3.0-or-later
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace DocsPaVO.Conservazione.PARER.SIP
{

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ProfiloArchivisticoFascicolo
    {

        private SegnaturaArchivisticaType segnaturaArchivisticaField;

        private FascicoloCollegatoTypeFascicoloCollegato[] collegamentiField;

        /// <remarks/>
        public SegnaturaArchivisticaType SegnaturaArchivistica
        {
            get
            {
                return this.segnaturaArchivisticaField;
            }
            set
            {
                this.segnaturaArchivisticaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("FascicoloCollegato", IsNullable = false)]
        public FascicoloCollegatoTypeFascicoloCollegato[] Collegamenti
        {
            get
            {
                return this.collegamentiField;
            }
            set
            {
                this.collegamentiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SegnaturaArchivisticaType
    {

        private ProfiloArchivisticoClassificazioneType classificazioneField;

        private ChiaveType chiaveFascicoloDiAppartenenzaField;

        /// <remarks/>
        public ProfiloArchivisticoClassificazioneType Classificazione
        {
            get
            {
                return this.classificazioneField;
            }
            set
            {
                this.classificazioneField = value;
            }
        }

        /// <remarks/>
        public ChiaveType ChiaveFascicoloDiAppartenenza
        {
            get
            {
                return this.chiaveFascicoloDiAppartenenzaField;
            }
            set
            {
                this.chiaveFascicoloDiAppartenenzaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProfiloArchivisticoClassificazioneType
    {

        private string indiceClassificazioneField;

        private VoceClassificazioneType[] descrizioneIndiceClassificazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string IndiceClassificazione
        {
            get
            {
                return this.indiceClassificazioneField;
            }
            set
            {
                this.indiceClassificazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("VoceClassificazione", IsNullable = false)]
        public VoceClassificazioneType[] DescrizioneIndiceClassificazione
        {
            get
            {
                return this.descrizioneIndiceClassificazioneField;
            }
            set
            {
                this.descrizioneIndiceClassificazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoceClassificazioneType
    {

        private string codiceVoceField;

        private string descrizioneVoceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string CodiceVoce
        {
            get
            {
                return this.codiceVoceField;
            }
            set
            {
                this.codiceVoceField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneVoce
        {
            get
            {
                return this.descrizioneVoceField;
            }
            set
            {
                this.descrizioneVoceField = value;
            }
        }
    }

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //public partial class ChiaveType
    //{

    //    private string annoField;

    //    private string numeroField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
    //    public string Anno
    //    {
    //        get
    //        {
    //            return this.annoField;
    //        }
    //        set
    //        {
    //            this.annoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Numero
    //    {
    //        get
    //        {
    //            return this.numeroField;
    //        }
    //        set
    //        {
    //            this.numeroField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FascicoloCollegatoTypeFascicoloCollegato
    {

        private ChiaveType chiaveCollegamentoField;

        private string descrizioneCollegamentoField;

        /// <remarks/>
        public ChiaveType ChiaveCollegamento
        {
            get
            {
                return this.chiaveCollegamentoField;
            }
            set
            {
                this.chiaveCollegamentoField = value;
            }
        }

        /// <remarks/>
        public string DescrizioneCollegamento
        {
            get
            {
                return this.descrizioneCollegamentoField;
            }
            set
            {
                this.descrizioneCollegamentoField = value;
            }
        }
    }

}