// SPDX-FileCopyrightText: 2025 Provincia Autonoma di Trento <https://www.provincia.tn.it>
// SPDX-License-Identifier: EUPL-1.2
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pi3.App.Legacy.WebApi.Application.Handlers.HSM_SignMultiSignSession {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pi3.App.Legacy.WebApi.Application.Handlers.HSM_SignMultiSignSession.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false: Errore creando la nuova versione firmata.
        /// </summary>
        internal static string ErrorInNewVersion {
            get {
                return ResourceManager.GetString("ErrorInNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false: Filerequest nullo.
        /// </summary>
        internal static string NullFileRequestError {
            get {
                return ResourceManager.GetString("NullFileRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento è stato firmato digitalmente HSM CADES..
        /// </summary>
        internal static string SignDescriptionCADES {
            get {
                return ResourceManager.GetString("SignDescriptionCADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento è stato firmato digitalmente HSM PADES..
        /// </summary>
        internal static string SignDescriptionPADES {
            get {
                return ResourceManager.GetString("SignDescriptionPADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione firmata.
        /// </summary>
        internal static string SignedAttachment {
            get {
                return ResourceManager.GetString("SignedAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versione firmata.
        /// </summary>
        internal static string SignedVersion {
            get {
                return ResourceManager.GetString("SignedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false: Errore firmando remotamente il documento.
        /// </summary>
        internal static string SignError {
            get {
                return ResourceManager.GetString("SignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true: Versione creata con successo.
        /// </summary>
        internal static string VersionCreated {
            get {
                return ResourceManager.GetString("VersionCreated", resourceCulture);
            }
        }
    }
}
