using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace StampaRegistri.DocsPaWR305
{
	[GeneratedCode("System.Xml", "2.0.50727.42"), XmlType(Namespace = "http://localhost")]
	[Serializable]
	public enum FiltriTrasmissioneNascosti
	{
		TIPO_OGGETTO,
		NO_CERCA_INFERIORI,
		ASSEGNAZIONI_PENDENTI,
		TODO_LIST,
		IN_RISPOSTA,
		ID_TRASMISSIONE,
		ATTIVITA_NON_CONCLUSE,
		TRASMISSIONE_DOC_PROTOCOLLATI,
		TRASMISSIONE_DOC_PROT_ARRIVO,
		TRASMISSIONE_DOC_PROT_PARTENZA,
		TRASMISSIONE_DOC_NON_PROTOCOLLATI,
		ID_UO,
		COD_RUBR_DEST_UTENTE,
		COD_RUBR_DEST_RUOLO,
		ID_UO_DEST,
		COD_RUBR_MITT_UTENTE,
		COD_RUBR_MITT_RUOLO,
		ID_UO_MITT,
		DESTINATARIO_UTENTE,
		DESTINATARIO_RUOLO,
		DESTINATARIO_UO,
		MITTENTE_UTENTE,
		MITTENTE_RUOLO,
		MITTENTE_UO,
		TRASMISSIONE_IL,
		TRASMISSIONE_SUCCESSIVA_AL,
		TRASMISSIONE_PRECEDENTE_IL,
		RAGIONE,
		STATO
	}
}
