--------------------------------------------------------
--  DDL for Table DPA_COUNT_TODOLIST
--------------------------------------------------------

  CREATE TABLE "ITCOLL_6GIU12"."DPA_COUNT_TODOLIST" 
   (	"ID_PEOPLE" NUMBER, 
	"TS_STAMPA" DATE, 
	"TOT_DOC" NUMBER DEFAULT 0, 
	"TOT_DOC_NO_LETTI" NUMBER DEFAULT 0, 
	"TOT_DOC_NO_ACCETTATI" NUMBER DEFAULT 0, 
	"TOT_FASC" NUMBER DEFAULT 0, 
	"TOT_FASC_NO_LETTI" NUMBER DEFAULT 0, 
	"TOT_FASC_NO_ACCETTATI" NUMBER DEFAULT 0, 
	"TOT_DOC_PREDISPOSTI" NUMBER DEFAULT 0
   ) ;
